# test_initial_state.py
#
# This pytest suite validates the **initial** filesystem state before the
# student starts working on the “database-reliability engineer” exercise.
#
# Rules respected:
#   • Only stdlib + pytest are used.
#   • Nothing about the *output* artefacts (/compressed/, manifest, etc.)
#     is checked – we limit ourselves strictly to the required initial files.
#   • Every failure message explains exactly what is missing or unexpected.
#   • Absolute paths are used throughout.

import os
import pytest

RAW_DIR = "/home/user/db_backups/raw"
EXPECTED_FILES = {
    "employees_2023-07-10.sql": "Alice",
    "employees_2023-07-11.sql": "Bob",
}

@pytest.fixture(scope="module")
def raw_listing():
    """Return the list of items currently inside the raw directory.

    The fixture fails early if the directory itself is missing.
    """
    if not os.path.isdir(RAW_DIR):
        pytest.fail(
            f"Required directory {RAW_DIR} does not exist.\n"
            "Create it first and place the .sql dumps inside it."
        )
    return os.listdir(RAW_DIR)


def test_raw_directory_contains_exactly_expected_sql_files(raw_listing):
    """The raw directory must contain *exactly* the two expected .sql files."""
    # Filter for .sql files only
    sql_files = {f for f in raw_listing if f.endswith(".sql")}
    missing = EXPECTED_FILES.keys() - sql_files
    extra   = sql_files - EXPECTED_FILES.keys()

    if missing:
        pytest.fail(
            f"Missing .sql file(s) in {RAW_DIR}: {', '.join(sorted(missing))}"
        )
    if extra:
        pytest.fail(
            f"Unexpected extra .sql file(s) in {RAW_DIR}: {', '.join(sorted(extra))}\n"
            "The initial state should only contain the two provided dumps."
        )


@pytest.mark.parametrize("filename,unique_substring", EXPECTED_FILES.items())
def test_each_sql_file_has_expected_content(filename, unique_substring):
    """
    Each expected .sql file must:
      • exist as a regular file,
      • contain the standard header line generated by pg_dump,
      • contain a row that is unique to the specific dump
        (so we know the files are not duplicates).
    """
    full_path = os.path.join(RAW_DIR, filename)

    if not os.path.isfile(full_path):
        pytest.fail(f"Expected file {full_path} is missing or not a regular file.")

    with open(full_path, "r", encoding="utf-8") as f:
        content = f.read()

    generic_phrase = "Backup generated by pg_dump"
    if generic_phrase not in content:
        pytest.fail(
            f"File {full_path} does not contain the expected header "
            f"line: '{generic_phrase}'."
        )

    if unique_substring not in content:
        pytest.fail(
            f"File {full_path} does not contain the expected unique value "
            f"('{unique_substring}') that differentiates the dumps."
        )