# test_initial_state.py
#
# This test-suite validates that the operating-system / filesystem is in the
# expected *initial* state, i.e. *before* the student starts solving the task.
# It checks:
#   • the presence and exact contents of the raw log files;
#   • that the summary artefacts do *not* yet exist.
#
# If any of these tests fail it means the exercise sandbox was not provisioned
# correctly or somebody has already started working on the task.

import os
from pathlib import Path
import pytest

# ---------- Constants ---------------------------------------------------------

HOME            = Path("/home/user")
RAW_DIR         = HOME / "api_logs" / "raw"
SUMMARY_DIR     = HOME / "api_logs" / "summary"

RAW_FILE_1      = RAW_DIR / "service_2023-05-12.log"
RAW_FILE_2      = RAW_DIR / "service_2023-05-13.log"

SUMMARY_CSV     = SUMMARY_DIR / "service_status_report.csv"
SUMMARY_ERRORS  = SUMMARY_DIR / "unique_errors.txt"

EXPECTED_RAW_CONTENT = {
    RAW_FILE_1: (
        "2023-05-12T14:23:11Z - "
        '{"service":"user","endpoint":"/v1/register","status":200,"response_time_ms":132}\n'
        "2023-05-12T14:25:46Z - "
        '{"service":"auth","endpoint":"/v1/login","status":500,"error":"DB_TIMEOUT","response_time_ms":987}\n'
        "2023-05-12T14:28:09Z - "
        '{"service":"user","endpoint":"/v1/profile","status":200,"response_time_ms":84}\n'
        "2023-05-12T14:31:55Z - "
        '{"service":"payment","endpoint":"/v1/pay","status":500,"error":"CARD_DECLINED","response_time_ms":453}\n'
    ),
    RAW_FILE_2: (
        "2023-05-13T07:12:44Z - "
        '{"service":"payment","endpoint":"/v1/refund","status":200,"response_time_ms":211}\n'
        "2023-05-13T07:15:02Z - "
        '{"service":"auth","endpoint":"/v1/login","status":200,"response_time_ms":153}\n'
        "2023-05-13T07:18:27Z - "
        '{"service":"user","endpoint":"/v1/delete","status":500,"error":"UNKNOWN_USER","response_time_ms":674}\n'
        "2023-05-13T07:20:19Z - "
        '{"service":"payment","endpoint":"/v1/pay","status":500,"error":"INSUFFICIENT_FUNDS","response_time_ms":502}\n'
    ),
}

# ---------- Helper ------------------------------------------------------------

def read_file(path: Path) -> str:
    """
    Read a UTF-8 text file exactly as is.
    """
    with path.open("r", encoding="utf-8") as fh:
        return fh.read()

# ---------- Tests -------------------------------------------------------------

def test_raw_directory_exists():
    assert RAW_DIR.is_dir(), (
        f"Expected directory {RAW_DIR} to exist. "
        "It should contain the raw API log files shipped with the exercise."
    )


@pytest.mark.parametrize("path", [RAW_FILE_1, RAW_FILE_2])
def test_each_raw_file_exists(path: Path):
    assert path.is_file(), f"Missing required raw log file: {path}"


def test_raw_file_contents_are_exact():
    """
    The initial fixture files must match *exactly*; otherwise the statistical
    checks performed later will be meaningless.
    """
    mismatches = []
    for path, expected in EXPECTED_RAW_CONTENT.items():
        if not path.is_file():
            mismatches.append(f"{path} is missing")
            continue
        actual = read_file(path)
        if actual != expected:
            mismatches.append(
                f"Content mismatch in {path}:\n"
                "---- Expected ----\n"
                f"{expected}"
                "---- Actual ----\n"
                f"{actual}"
            )
    assert not mismatches, ";\n".join(mismatches)


def test_no_summary_directory_or_files_yet():
    """
    At the very beginning the summary artefacts must *not* be present.
    The student is supposed to create them.
    """
    assert not SUMMARY_CSV.exists(), (
        f"{SUMMARY_CSV} already exists — the summary must be generated by the student."
    )
    assert not SUMMARY_ERRORS.exists(), (
        f"{SUMMARY_ERRORS} already exists — the summary must be generated by the student."
    )

    # The summary directory itself may or may not exist; if it does exist it
    # must be empty to avoid confusion.
    if SUMMARY_DIR.exists():
        unexpected = [p for p in SUMMARY_DIR.iterdir() if p.name not in {".gitkeep"}]
        assert (
            not unexpected
        ), f"The directory {SUMMARY_DIR} should be empty at the start, found: {unexpected}"


def test_only_expected_raw_files_present():
    """
    The raw directory should contain exactly the two fixture files — nothing more,
    nothing less — so that later aggregation is deterministic.
    """
    expected_names = {RAW_FILE_1.name, RAW_FILE_2.name}
    actual_names   = {p.name for p in RAW_DIR.iterdir() if p.is_file()}

    extra   = actual_names - expected_names
    missing = expected_names - actual_names

    assert not extra,   f"Unexpected extra files in {RAW_DIR}: {sorted(extra)}"
    assert not missing, f"Missing files in {RAW_DIR}: {sorted(missing)}"