# test_initial_state.py
"""
Pytest suite to validate the machine *before* the student begins work.

We confirm that:
1. The working home directory (/home/user) already exists.
2. The virtual-environment directory the student must create **does NOT** yet exist.
3. The log file the student must create **does NOT** yet exist.

If any of these checks fail, the environment is not in the expected pristine
state and the assignment should not proceed.
"""

import os
from pathlib import Path

HOME_DIR = Path("/home/user")
VENV_DIR = HOME_DIR / "scan_venv"
LOG_FILE = HOME_DIR / "venv_check.log"


def test_home_directory_present():
    """
    /home/user must exist so the student has a location in which to work.
    """
    assert HOME_DIR.is_dir(), (
        f"Expected home directory {HOME_DIR} to exist and be a directory, "
        "but it is missing."
    )


def test_virtualenv_absent_initially():
    """
    The virtual environment directory should NOT exist before the student
    creates it.  Its presence would indicate a contaminated starting state.
    """
    assert not VENV_DIR.exists(), (
        f"Found unexpected path {VENV_DIR}. "
        "The virtual environment must be created by the student, "
        "so it should not be present at the outset."
    )


def test_log_file_absent_initially():
    """
    The verification log file should NOT exist before the student creates it.
    """
    assert not LOG_FILE.exists(), (
        f"Found unexpected file {LOG_FILE}. "
        "The log file must be generated by the student, "
        "so it should not be present at the outset."
    )