# test_initial_state.py
#
# Pytest suite to verify the *initial* filesystem state for the
# “ExampleCorp” firewall-draft exercise.  These tests are executed
# before the learner performs any actions.  They intentionally **fail**
# if the target artefacts already exist, guaranteeing that the student
# begins from a clean slate.
#
# The checks are simple:
#
#   1. /home/user          — must exist (it is the learner’s HOME).
#   2. /home/user/firewall — may or may not exist, but
#      ‑ it must *not* already contain `firewall.rules`
#      ‑ it must *not* already contain `firewall_config.log`
#
# Any pre-existing artefact would invalidate the exercise because the
# student is supposed to create them from scratch.

from pathlib import Path
import pytest


HOME_DIR = Path("/home/user")
FIREWALL_DIR = HOME_DIR / "firewall"
RULES_FILE = FIREWALL_DIR / "firewall.rules"
LOG_FILE = FIREWALL_DIR / "firewall_config.log"


def test_home_directory_exists_and_is_directory():
    """The base home directory must already exist and be a directory."""
    assert HOME_DIR.exists(), (
        f"Expected base directory {HOME_DIR} to exist, "
        "but it is missing."
    )
    assert HOME_DIR.is_dir(), (
        f"Expected {HOME_DIR} to be a directory, "
        "but something else is present."
    )


def test_firewall_rules_file_absent():
    """
    The rules file must NOT exist before the student starts.
    Presence would indicate work was done prematurely.
    """
    assert not RULES_FILE.exists(), (
        f"{RULES_FILE} already exists. "
        "It should be created by the student during the exercise, "
        "not before it begins."
    )


def test_firewall_log_file_absent():
    """
    The log file must NOT exist before the student starts.
    """
    assert not LOG_FILE.exists(), (
        f"{LOG_FILE} already exists. "
        "It should be generated by the student during the exercise."
    )


def test_firewall_directory_state():
    """
    If /home/user/firewall exists already, it must not contain the target
    files.  The directory itself may be present (e.g., from a previous
    unrelated task), but the exercise artefacts must be absent.
    """
    if FIREWALL_DIR.exists():
        assert FIREWALL_DIR.is_dir(), (
            f"Expected {FIREWALL_DIR} to be a directory, "
            "but found a non-directory object."
        )

        unwanted_files = [
            p for p in (RULES_FILE, LOG_FILE) if p.exists()
        ]
        assert not unwanted_files, (
            "The following file(s) already exist inside "
            f"{FIREWALL_DIR}: {', '.join(map(str, unwanted_files))}. "
            "They must **not** be present before the exercise starts."
        )