# test_initial_state.py
#
# Pytest suite that verifies the *initial* filesystem / OS state
# before the student starts working on the task.
#
# Rules we enforce:
#   • /home/user/raw_dataset.csv must already exist and have the
#     exact expected structure (header + 5 data rows, 4 comma-separated
#     columns per row).
#   • The task output directory /home/user/optimizer_data and any
#     files inside it **must not exist yet**.

import os
import csv
import pytest

RAW_CSV = "/home/user/raw_dataset.csv"
OPT_DIR = "/home/user/optimizer_data"
SOLVER_TSV = "/home/user/optimizer_data/solver_input.tsv"
LOG_PATH = "/home/user/optimizer_data/generation.log"


@pytest.mark.describe("Initial raw CSV presence and structure")
class TestRawCSV:
    def test_raw_csv_exists(self):
        """raw_dataset.csv should already be present before the task starts."""
        assert os.path.isfile(
            RAW_CSV
        ), f"Expected raw CSV at {RAW_CSV!r}, but the file is missing."

    def test_raw_csv_content(self):
        """
        raw_dataset.csv must contain exactly 6 lines (header + 5 data rows),
        with the header 'id,feature1,feature2,label' and four comma-separated
        columns per row.
        """
        with open(RAW_CSV, newline="") as fh:
            reader = list(csv.reader(fh))
        # Check line count
        assert len(reader) == 6, (
            f"{RAW_CSV!r} should contain 6 lines (header + 5 data rows), "
            f"found {len(reader)} lines."
        )

        # Validate header
        expected_header = ["id", "feature1", "feature2", "label"]
        assert (
            reader[0] == expected_header
        ), f"Header mismatch: expected {expected_header}, got {reader[0]}."

        # Validate each data row has exactly 4 columns
        for idx, row in enumerate(reader[1:], start=1):
            assert len(row) == 4, (
                f"Row {idx} in {RAW_CSV!r} should have 4 columns; "
                f"found {len(row)} columns: {row}"
            )


@pytest.mark.describe("Output artefacts must NOT pre-exist")
class TestNoPrematureOutput:
    def test_optimizer_directory_absent(self):
        """The output directory must not exist before the student creates it."""
        assert not os.path.exists(
            OPT_DIR
        ), f"The directory {OPT_DIR!r} already exists; it should *not* exist yet."

    def test_solver_input_tsv_absent(self):
        """solver_input.tsv must not exist prior to task execution."""
        assert not os.path.exists(
            SOLVER_TSV
        ), f"The file {SOLVER_TSV!r} already exists; it should be generated by the student."

    def test_generation_log_absent(self):
        """generation.log must not exist prior to task execution."""
        assert not os.path.exists(
            LOG_PATH
        ), f"The file {LOG_PATH!r} already exists; it should be generated by the student."