# test_initial_state.py
#
# Pytest suite that validates the initial, pre-task filesystem state
# for the “dataset summary” exercise.  These tests make sure the
# expected data directories and CSV files already exist *before* the
# student writes any solution code.
#
# Rules honoured:
#   • Uses only stdlib + pytest.
#   • Does NOT inspect /home/user/output or any artefacts that will be
#     generated by the student’s solution.
#   • Provides clear failure messages on what is missing / incorrect.

import os
from pathlib import Path

BASE_DIR = Path("/home/user/data_experiments")
DATASETS = {
    "dataset_A": {
        "file1.csv": 2,  # expected number of data rows (excluding header)
        "file2.csv": 3,
    },
    "dataset_B": {
        "measurements.csv": 4,
    },
}


def test_base_directory_exists():
    """Ensure /home/user/data_experiments exists and is a directory."""
    assert BASE_DIR.exists(), f"Expected directory {BASE_DIR} to exist."
    assert BASE_DIR.is_dir(), f"{BASE_DIR} exists but is not a directory."


def test_expected_dataset_directories_present_and_only_expected():
    """
    Confirm that exactly the expected top-level dataset directories are present
    underneath /home/user/data_experiments.
    """
    actual_dirs = sorted(
        p.name for p in BASE_DIR.iterdir() if p.is_dir() and not p.name.startswith(".")
    )
    expected_dirs = sorted(DATASETS.keys())
    assert actual_dirs == expected_dirs, (
        "Mismatch in dataset directories under "
        f"{BASE_DIR}.\nExpected: {expected_dirs!r}\nFound:    {actual_dirs!r}"
    )


def test_each_dataset_contains_expected_csv_files():
    """Verify every dataset folder has exactly the CSV files we expect."""
    for ds_name, files in DATASETS.items():
        ds_path = BASE_DIR / ds_name
        assert ds_path.is_dir(), f"Dataset directory {ds_path} is missing."

        actual_csvs = sorted(
            p.name for p in ds_path.iterdir() if p.is_file() and p.suffix == ".csv"
        )
        expected_csvs = sorted(files.keys())
        assert actual_csvs == expected_csvs, (
            f"CSV file list mismatch in {ds_path}.\n"
            f"Expected: {expected_csvs!r}\nFound:    {actual_csvs!r}"
        )


def _count_data_rows(csv_path: Path) -> int:
    """
    Return the number of data rows (exclude the first header line) in a CSV file.
    Assumes at least one line (the header) exists.
    """
    with csv_path.open("r", encoding="utf-8") as fh:
        lines = fh.readlines()
    assert lines, f"{csv_path} appears to be empty but should contain data."
    return max(0, len(lines) - 1)  # subtract header


def test_csv_row_counts_match_truth():
    """
    Check that each CSV file has the exact number of data rows
    (header lines are NOT counted).
    """
    for ds_name, files in DATASETS.items():
        for csv_name, expected_rows in files.items():
            csv_path = BASE_DIR / ds_name / csv_name
            assert csv_path.is_file(), f"Expected CSV file {csv_path} is missing."
            actual_rows = _count_data_rows(csv_path)
            assert (
                actual_rows == expected_rows
            ), f"{csv_path}: expected {expected_rows} data rows, found {actual_rows}."