# test_initial_state.py
"""
Pytest suite that validates the **initial** operating-system / filesystem state
_before_ the student performs any hardening steps.

It checks only the pre-existing configuration files that must be present before
the task starts.  It deliberately does **not** look for any of the output files
or directories that the student is expected to create (/home/user/hardening,
hardening_summary.log, etc.), in accordance with the grading rules.
"""

import os
import pytest

HOME = "/home/user"
CONFIG_DIR = os.path.join(HOME, "configs")

SSH_CFG_PATH = os.path.join(CONFIG_DIR, "ssh_config.yaml")
SERVICE_LIMITS_PATH = os.path.join(CONFIG_DIR, "service_limits.toml")


@pytest.fixture(scope="module")
def ssh_config_text():
    """Return the raw text of ssh_config.yaml; fail early if file is missing."""
    assert os.path.isfile(
        SSH_CFG_PATH
    ), f"Missing required file: {SSH_CFG_PATH!r}. It must exist before hardening begins."
    with open(SSH_CFG_PATH, "r", encoding="utf-8") as fh:
        return fh.read()


@pytest.fixture(scope="module")
def service_limits_text():
    """Return the raw text of service_limits.toml; fail early if file is missing."""
    assert os.path.isfile(
        SERVICE_LIMITS_PATH
    ), f"Missing required file: {SERVICE_LIMITS_PATH!r}. It must exist before hardening begins."
    with open(SERVICE_LIMITS_PATH, "r", encoding="utf-8") as fh:
        return fh.read()


def test_ssh_config_initial_contents(ssh_config_text):
    """
    ssh_config.yaml must start in its pristine 3-line state.

    Expected lines (no additional whitespace):
        # OpenSSH configuration
        PermitRootLogin: yes
        MaxSessions: 10
    """
    expected_lines = [
        "# OpenSSH configuration",
        "PermitRootLogin: yes",
        "MaxSessions: 10",
    ]

    actual_lines = ssh_config_text.splitlines()
    assert (
        actual_lines == expected_lines
    ), (
        f"{SSH_CFG_PATH} does not match the required initial contents.\n\n"
        f"Expected (3 lines):\n{expected_lines}\n\n"
        f"Found ({len(actual_lines)} lines):\n{actual_lines}\n"
        "Do not edit this file before the hardening step begins."
    )


def test_service_limits_initial_contents(service_limits_text):
    """
    service_limits.toml must start in its pristine 3-line state.

    Expected lines (no additional whitespace):
        # System service limits
        max_open_files = 1024
        max_user_processes = 512
    """
    expected_lines = [
        "# System service limits",
        "max_open_files = 1024",
        "max_user_processes = 512",
    ]

    actual_lines = service_limits_text.splitlines()
    assert (
        actual_lines == expected_lines
    ), (
        f"{SERVICE_LIMITS_PATH} does not match the required initial contents.\n\n"
        f"Expected (3 lines):\n{expected_lines}\n\n"
        f"Found ({len(actual_lines)} lines):\n{actual_lines}\n"
        "Do not edit this file before the hardening step begins."
    )