# test_initial_state.py
#
# Pytest suite that validates the pre-exercise state of the filesystem
# for the “laboratory readings standardisation” task.
#
# The student must start with
#   • an existing raw data file
#   • NO generated CSV or summary yet present
#
# This test file checks only that initial state.

import os
import re
import pytest

RAW_FILE = "/home/user/datasets/measurements_2023.txt"
CSV_FILE = "/home/user/datasets/measurements_2023.csv"
SUMMARY_FILE = "/home/user/datasets/measurements_summary.txt"
DATASET_DIR = "/home/user/datasets"


def test_dataset_directory_exists():
    """The parent directory must already be present."""
    assert os.path.isdir(DATASET_DIR), (
        f"Required directory {DATASET_DIR} is missing. "
        "Create it (or correct the path) before running the task."
    )


def test_raw_file_exists_and_permissions():
    """The raw, space-separated text file must exist and be world-readable."""
    assert os.path.isfile(RAW_FILE), f"Raw data file {RAW_FILE} is missing."
    assert os.access(RAW_FILE, os.R_OK), f"Raw data file {RAW_FILE} exists but is not readable."

    mode = os.stat(RAW_FILE).st_mode & 0o777
    expected_mode = 0o644
    assert mode == expected_mode, (
        f"Raw data file {RAW_FILE} should have permissions 644 "
        f"(-rw-r--r--), but it has {oct(mode)} instead."
    )


def test_raw_file_content_format():
    """File must contain exactly five correctly-formatted lines."""
    with open(RAW_FILE, encoding="utf-8") as fh:
        lines = fh.read().splitlines()

    assert len(lines) == 5, (
        f"{RAW_FILE} should contain exactly 5 lines, found {len(lines)}."
    )

    # Regex: <id> <float> <YYYY-MM-DD>
    line_pattern = re.compile(r"^\S+\s+\d+(?:\.\d+)?\s+\d{4}-\d{2}-\d{2}$")

    for idx, line in enumerate(lines, 1):
        assert line_pattern.match(line), (
            f"Line {idx} in {RAW_FILE} is not in the expected "
            "'experimentID value date' format:\n    {line}"
        )
        parts = line.split()
        assert len(parts) == 3, (
            f"Line {idx} in {RAW_FILE} does not contain exactly three "
            f"space-delimited fields: {line}"
        )


def test_output_files_do_not_yet_exist():
    """The CSV and summary should NOT exist before the student runs their solution."""
    for path in (CSV_FILE, SUMMARY_FILE):
        assert not os.path.exists(path), (
            f"Output file {path} already exists. "
            "It should be generated by your solution, so ensure it is absent beforehand."
        )