# test_initial_state.py
#
# This pytest suite verifies that the workspace is clean *before*
# the student creates any configuration artifacts for the
# “mock weather service” task.  Nothing related to the service should
# exist yet—neither the directory, nor the configuration file, nor the
# status log.  Should any of them already be present, the tests will
# fail with a clear, actionable message.
#
# NOTE: These tests purposefully assert the *absence* of the target
# files.  A separate test suite will later confirm their presence once
# the student has completed the exercise.

import os
from pathlib import Path

HOME = Path("/home/user")
CONFIG_DIR = HOME / ".config" / "mock_weather_service"
CONFIG_FILE = CONFIG_DIR / "service.cfg"
STATUS_LOG = HOME / "mock_weather_service_status.log"


def _pretty(p: Path) -> str:
    """Return a nicely formatted absolute path for error messages."""
    return str(p.resolve())


def test_home_directory_exists():
    """
    Sanity-check: the base home directory must exist.  If it does not,
    something is fundamentally wrong with the test environment.
    """
    assert HOME.exists() and HOME.is_dir(), (
        f"Expected home directory {_pretty(HOME)} to exist, "
        "but it was not found."
    )


def test_config_directory_absent():
    """
    The service configuration directory must *not* exist before the
    student starts the task.
    """
    assert not CONFIG_DIR.exists(), (
        f"Found unexpected directory {_pretty(CONFIG_DIR)}. "
        "The workspace should be clean before the exercise."
    )


def test_config_file_absent():
    """
    The service.cfg file must *not* exist yet.
    """
    assert not CONFIG_FILE.exists(), (
        f"Found unexpected configuration file {_pretty(CONFIG_FILE)}. "
        "It should be created by the student during the exercise."
    )


def test_status_log_absent():
    """
    The summary log must *not* exist before the student runs their
    commands.
    """
    assert not STATUS_LOG.exists(), (
        f"Found unexpected status log {_pretty(STATUS_LOG)}. "
        "It should be generated by the student during the exercise."
    )