# test_initial_state.py
#
# This test-suite validates the *initial* condition of the sandbox
# BEFORE the student performs any actions.  It asserts that
#   • the legacy pages exist with the exact byte-for-byte contents
#     (including their original encodings and <meta> declarations),
#   • no UTF-8 output directory or conversion log is present yet.
#
# If any assertion here fails, the sandbox was not provisioned
# correctly for the exercise and the follow-up tasks would be invalid.

import os
import pytest
from pathlib import Path

# ----------------------------------------------------------------------
# Constants describing the required initial state
# ----------------------------------------------------------------------

HOME = Path("/home/user")
PAGES_DIR = HOME / "dev_site" / "pages"
UTF8_DIR = HOME / "dev_site" / "pages_utf8"
LOG_FILE = HOME / "encoding_conversion.log"

# Expected exact byte content for every legacy HTML file.
# Hex strings are copied verbatim from the task description.
EXPECTED_FILES = {
    "index.html": (
        "3c6d65746120636861727365743d2277696e646f77732d31323532223e0a"
        "3c68313e4372e86d65204272fb6ce9653c2f68313e0a"
        "3c703e50726963653a203130803c2f703e0a"
    ),
    "about.html": (
        "3c6d65746120636861727365743d2269736f2d383835392d31223e0a"
        "3c703e5365f16f722061f16f206361f1f36e3c2f703e0a"
    ),
    "contact.html": (
        "3c6d65746120636861727365743d2277696e646f77732d31323532223e0a"
        "3c703e50686f6e653a202b343920303330203132333435363c2f703e0a"
        "3c703e456d61696c3a20fc626572406578616d706c652e636f6d3c2f703e0a"
    ),
}

# ----------------------------------------------------------------------
# Helper functions
# ----------------------------------------------------------------------

def hex_to_bytes(hex_str: str) -> bytes:
    """Convert a continuous hex string (no spaces/newlines) to bytes."""
    return bytes.fromhex(hex_str)

# ----------------------------------------------------------------------
# Tests
# ----------------------------------------------------------------------

def test_pages_directory_exists_and_is_correct():
    """The legacy pages directory must exist and contain the exact 3 html files."""
    assert PAGES_DIR.is_dir(), (
        f"Required directory {PAGES_DIR} is missing."
    )

    actual_files = sorted(f.name for f in PAGES_DIR.iterdir() if f.is_file())
    expected_files = sorted(EXPECTED_FILES.keys())

    assert actual_files == expected_files, (
        f"{PAGES_DIR} should contain exactly these files: {expected_files}\n"
        f"Found: {actual_files}"
    )

@pytest.mark.parametrize("filename,hex_content", EXPECTED_FILES.items())
def test_individual_file_bytes(filename, hex_content):
    """Each legacy html file must match the exact byte sequence defined in the spec."""
    file_path = PAGES_DIR / filename
    assert file_path.is_file(), f"Expected file {file_path} is missing."

    expected_bytes = hex_to_bytes(hex_content)
    actual_bytes = file_path.read_bytes()

    assert actual_bytes == expected_bytes, (
        f"File {file_path} does not match the required initial contents.\n"
        f"(Either the meta charset, encoding, or the textual data was modified.)"
    )

def test_no_utf8_directory_yet():
    """The UTF-8 output directory must NOT exist before the student runs the conversion."""
    assert not UTF8_DIR.exists(), (
        f"The directory {UTF8_DIR} already exists, but it should be created by the student."
    )

def test_no_conversion_log_yet():
    """The conversion log must NOT exist before the student runs the conversion."""
    assert not LOG_FILE.exists(), (
        f"The file {LOG_FILE} already exists, but it should be generated by the student."
    )