# test_initial_state.py
#
# This pytest suite validates the *initial* state of the operating system
# before the student carries out the “SSH credentials” task.  It confirms
# that no artefacts from the *finished* task are already present, so the
# exercise starts from a clean slate.

import os
from pathlib import Path
import pytest

HOME = Path("/home/user")
SSH_DIR = HOME / ".ssh"
PRIVATE_KEY = SSH_DIR / "id_api_test"
PUBLIC_KEY = SSH_DIR / "id_api_test.pub"
AUTHORIZED_KEYS = SSH_DIR / "authorized_keys"
LOG_FILE = HOME / "ssh_setup_log.txt"
COMMENT_STR = "api-dev@example.com"


def _read_text_if_exists(path: Path) -> str:
    """
    Helper: return the text content of *path* if it exists and is a file,
    otherwise return an empty string.
    """
    try:
        if path.is_file():
            return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        # Any permissions or I/O error ⇒ treat as empty for test purposes.
        pass
    return ""


def test_key_files_absent():
    """The task-specific key pair must not exist yet."""
    assert not PRIVATE_KEY.exists(), (
        f"Pre-task check failed: {PRIVATE_KEY} already exists; "
        "the key should be generated by the student, not pre-existing."
    )
    assert not PUBLIC_KEY.exists(), (
        f"Pre-task check failed: {PUBLIC_KEY} already exists; "
        "the public key should be generated by the student, not pre-existing."
    )


def test_log_file_absent():
    """The verification log must not be present before the task is executed."""
    assert not LOG_FILE.exists(), (
        f"Pre-task check failed: {LOG_FILE} already exists; "
        "it must be created by the student's script, not supplied in advance."
    )


def test_authorized_keys_does_not_contain_comment():
    """
    If ~/.ssh/authorized_keys exists, it must *not* already contain a key
    with the designated comment.  (The student will append it later.)
    """
    if not AUTHORIZED_KEYS.exists():
        pytest.skip("authorized_keys does not yet exist — OK for initial state.")

    content = _read_text_if_exists(AUTHORIZED_KEYS)
    assert COMMENT_STR not in content, (
        "Pre-task check failed: ~/.ssh/authorized_keys already contains a key "
        f"with the comment '{COMMENT_STR}'.  The student must add this key "
        "during the exercise, so it must not be present beforehand."
    )