# test_initial_state.py
#
# Pytest suite that validates the **initial** operating-system / filesystem
# state for the “Symlink Management & 404-Error Summary for Archived Web Logs”
# task.  These tests run *before* the student’s solution and therefore
# intentionally assert that:
#
#   • The archived log hierarchy already exists and contains the expected files.
#   • Each log file contains the correct number of HTTP 404 entries.
#   • No solution artefacts (working directory, symlinks, summary report, etc.)
#     are present yet.
#
# Only the Python stdlib and pytest are used.

import os
import re
from pathlib import Path

ARCHIVE_BASE = Path("/home/user/archive_logs")
WORK_DIR = Path("/home/user/log_analysis")
LATEST_SYMLINK = Path("/home/user/latest_analysis")

# Expected data for each day: directory name, path to log file, expected 404 count
ARCHIVE_EXPECTATIONS = {
    "2023-07-01": {
        "dir": ARCHIVE_BASE / "2023-07-01",
        "log": ARCHIVE_BASE / "2023-07-01" / "access.log",
        "expected_404": 5,
    },
    "2023-07-02": {
        "dir": ARCHIVE_BASE / "2023-07-02",
        "log": ARCHIVE_BASE / "2023-07-02" / "access.log",
        "expected_404": 3,
    },
    "2023-07-03": {
        "dir": ARCHIVE_BASE / "2023-07-03",
        "log": ARCHIVE_BASE / "2023-07-03" / "access.log",
        "expected_404": 8,
    },
}


def count_404s_in_file(path: Path) -> int:
    """
    Return the number of lines in *path* where the HTTP status code is 404.

    A very small parser is implemented: find the numeric status code that
    immediately follows the closing quote of the request string.  This is
    robust enough for standard combined/common Apache log formats.
    """
    status_re = re.compile(r'"\s+(\d{3})\s')
    count = 0
    with path.open("r", encoding="utf-8") as fh:
        for line in fh:
            match = status_re.search(line)
            if match and match.group(1) == "404":
                count += 1
    return count


def test_archive_directories_exist_and_are_directories():
    for day, meta in ARCHIVE_EXPECTATIONS.items():
        dir_path = meta["dir"]
        assert dir_path.exists(), (
            f"Expected directory {dir_path!s} for {day} does not exist."
        )
        assert dir_path.is_dir(), (
            f"Expected {dir_path!s} to be a directory, but it is not."
        )


def test_log_files_exist_and_are_regular_files():
    for day, meta in ARCHIVE_EXPECTATIONS.items():
        log_path = meta["log"]
        assert log_path.exists(), (
            f"Expected log file {log_path!s} for {day} does not exist."
        )
        assert log_path.is_file(), (
            f"Expected {log_path!s} to be a regular file, but it is not."
        )


def test_log_files_contain_expected_number_of_404s():
    for day, meta in ARCHIVE_EXPECTATIONS.items():
        log_path = meta["log"]
        expected = meta["expected_404"]
        actual = count_404s_in_file(log_path)
        assert actual == expected, (
            f"{log_path!s} should contain exactly {expected} lines with status 404, "
            f"but {actual} were found."
        )


def test_solution_artifacts_do_not_exist_yet():
    """
    The student has not executed their solution yet, so none of the following
    should exist:

        • /home/user/log_analysis          (working directory)
        • /home/user/log_analysis/links    (symlinks directory)
        • /home/user/log_analysis/report_404_summary.txt (summary file)
        • /home/user/latest_analysis       (convenience symlink)
    """
    assert not WORK_DIR.exists(), (
        f"Working directory {WORK_DIR!s} already exists; "
        "it should be created by the student’s solution."
    )

    links_dir = WORK_DIR / "links"
    assert not links_dir.exists(), (
        f"Links directory {links_dir!s} unexpectedly exists. "
        "No solution artefacts should be present at this stage."
    )

    summary_file = WORK_DIR / "report_404_summary.txt"
    assert not summary_file.exists(), (
        f"Summary report {summary_file!s} already exists; "
        "it must be generated by the student."
    )

    assert not LATEST_SYMLINK.exists(), (
        f"Symlink {LATEST_SYMLINK!s} already exists; "
        "it should be created by the student."
    )