# test_initial_state.py
#
# Pytest suite that validates the operating-system / filesystem
# BEFORE the student performs any action for the “customer snapshot
# encryption + audit-log” task.
#
# It checks that:
#   • Required input file and directories already exist.
#   • Encrypted output and audit-log are NOT yet present.
#   • GPG and sha256sum are available.
#
# Any failure message pin-points what is missing or unexpected.

import os
import stat
import shutil
from pathlib import Path

import pytest


# ---------- Constant reference paths ----------
HOME = Path("/home/user")
INPUT_DIR = HOME / "etl" / "input"
ENCRYPTED_DIR = HOME / "etl" / "encrypted"

PLAINTEXT_FILE = INPUT_DIR / "customer_snapshot.csv"
CIPHERTEXT_FILE = ENCRYPTED_DIR / "customer_snapshot.csv.asc"
LOG_FILE = ENCRYPTED_DIR / "customer_snapshot_sha256.log"

# Expected contents of the plaintext CSV (including final newline)
EXPECTED_CSV = (
    "customer_id,name,signup_date\n"
    "101,Alice,2023-01-02\n"
    "102,Bob,2023-01-10\n"
    "103,Charlie,2023-01-15\n"
)


# ---------- Helper functions ----------
def _is_writable_dir(path: Path) -> bool:
    """Return True if `path` is a directory and the current user can create a file in it."""
    if not path.is_dir():
        return False
    test_file = path / ".pytest_write_test"
    try:
        with open(test_file, "w"):
            pass
        return True
    except (IOError, OSError):
        return False
    finally:
        try:
            test_file.unlink()
        except Exception:
            pass


# ---------- Tests ----------
def test_input_directory_exists_and_has_correct_file_structure():
    assert INPUT_DIR.is_dir(), f"Required directory {INPUT_DIR} does not exist."
    assert PLAINTEXT_FILE.is_file(), (
        f"Input CSV {PLAINTEXT_FILE} is missing – it must be present before the task starts."
    )


def test_plaintext_file_contents_exact_match():
    content = PLAINTEXT_FILE.read_text()
    assert content == EXPECTED_CSV, (
        f"Contents of {PLAINTEXT_FILE} differ from the expected fixture.\n"
        "Check for missing lines, wrong values or newline at EOF."
    )


def test_encrypted_directory_state_before_task_starts():
    # Directory must exist
    assert ENCRYPTED_DIR.is_dir(), f"Directory {ENCRYPTED_DIR} is required but missing."
    # Directory must be writable
    assert _is_writable_dir(ENCRYPTED_DIR), f"Directory {ENCRYPTED_DIR} is not writable by the current user."
    # Directory must be empty before the task begins
    existing_items = list(ENCRYPTED_DIR.iterdir())
    assert (
        len(existing_items) == 0
    ), f"Encrypted directory {ENCRYPTED_DIR} should be empty before the task starts, found: {existing_items}"


def test_no_output_files_exist_yet():
    assert not CIPHERTEXT_FILE.exists(), (
        f"Encrypted file {CIPHERTEXT_FILE} already exists – "
        "the task should start from a clean slate."
    )
    assert not LOG_FILE.exists(), (
        f"Audit log {LOG_FILE} already exists – "
        "it must be generated by the student's solution."
    )


@pytest.mark.parametrize("binary_name", ["gpg", "sha256sum"])
def test_required_binaries_available_in_path(binary_name):
    path = shutil.which(binary_name)
    assert path is not None, (
        f"Required binary '{binary_name}' is not found in $PATH. "
        "Ensure it is installed and accessible."
    )