# test_initial_state.py
#
# Pytest suite that verifies the machine is in its
# pristine “pre-exercise” state.  None of the artefacts
# the student is asked to create should be present yet.

from pathlib import Path

WORKSPACE_DIR = Path("/home/user/pentest-workspace")
TARGET_LIST   = WORKSPACE_DIR / "targets.txt"
ALIAS_FILE    = Path("/home/user/.bash_aliases")
BASHRC_FILE   = Path("/home/user/.bashrc")
CHECK_LOG     = Path("/home/user/pentest_config_check.log")

ALIAS_LINE = (
    "alias vulnscan='nmap -sV -iL /home/user/pentest-workspace/targets.txt "
    "-oN /home/user/pentest-workspace/latest_scan.log'"
)

EXPORT_LINE = 'export PENTEST_DIR="/home/user/pentest-workspace"'


def test_workspace_directory_absent():
    """
    The workspace directory must NOT exist before the student starts.
    """
    assert not WORKSPACE_DIR.exists(), (
        f"Directory {WORKSPACE_DIR} already exists, "
        "but the exercise expects it to be created by the student."
    )


def test_target_list_absent():
    """
    The target list file must NOT exist beforehand.
    """
    assert not TARGET_LIST.exists(), (
        f"File {TARGET_LIST} already exists, "
        "but it should be created by the student."
    )


def test_alias_not_preconfigured():
    """
    The specific alias line must NOT be present yet.
    The file itself may or may not exist, but the exact line must be absent.
    """
    if not ALIAS_FILE.exists():
        # File absent is fine; the student will create or append to it.
        return

    lines = ALIAS_FILE.read_text().splitlines()
    assert ALIAS_LINE not in lines, (
        f"The alias line is already present in {ALIAS_FILE}; "
        "it should only appear after the student configures it."
    )


def test_export_not_preconfigured():
    """
    The export line must NOT be present in ~/.bashrc yet.
    (The file may legitimately be absent or contain other lines.)
    """
    if not BASHRC_FILE.exists():
        return

    lines = BASHRC_FILE.read_text().splitlines()
    assert EXPORT_LINE not in lines, (
        f"The export line is already present in {BASHRC_FILE}; "
        "it should only appear after the student adds it."
    )


def test_check_log_absent():
    """
    The final self-check log must NOT exist before the student runs their commands.
    """
    assert not CHECK_LOG.exists(), (
        f"File {CHECK_LOG} already exists, "
        "but it is supposed to be generated by the student at the end."
    )