# test_initial_state.py
#
# This pytest suite validates that the operating-system state **before**
# the student’s script is executed matches the specification handed to
# the automatic grader.  It checks only the *initial* inputs and never
# refers to any artefacts that should be produced by the student.

import os
import stat
import pytest
from pathlib import Path

HOME = Path("/home/user")
DATASET_DIR = HOME / "datasets"

# Expected files and their exact byte sizes
EXPECTED_FILES = {
    "sample1.csv": 21,
    "sample2.csv": 14,
    "sample3.csv": 13,
    "config.json": 22,
    "meta.json":   20,
}


def _full(path: Path) -> str:
    """Return the path as string for nice pytest error messages."""
    return str(path.resolve())


def test_datasets_directory_exists():
    """
    The root datasets directory must exist and be a directory.
    """
    assert DATASET_DIR.exists(), (
        f"Required directory {_full(DATASET_DIR)} is missing."
    )
    assert DATASET_DIR.is_dir(), (
        f"{_full(DATASET_DIR)} exists but is not a directory."
    )


@pytest.mark.parametrize("filename,expected_size", EXPECTED_FILES.items())
def test_expected_file_presence_and_size(filename, expected_size):
    """
    Every expected dataset file must be present directly in
    /home/user/datasets and must have the exact byte size specified by
    the pre-task description.
    """
    file_path = DATASET_DIR / filename
    assert file_path.exists(), (
        f"Required file {_full(file_path)} is missing."
    )
    assert file_path.is_file(), (
        f"{_full(file_path)} exists but is not a regular file."
    )

    # Verify byte size via os.stat for portability / performance
    actual_size = os.stat(file_path).st_size
    assert actual_size == expected_size, (
        f"{_full(file_path)} has size {actual_size} bytes, "
        f"but {expected_size} bytes were expected."
    )


def test_no_unexpected_directories_already_present():
    """
    The task specification states that the student will *create* the
    csv/ and json/ sub-directories.  They must therefore *not* already
    exist at this stage.  (We only check for directories; files with
    those names are also disallowed.)
    """
    for sub in ("csv", "json"):
        sub_path = DATASET_DIR / sub
        assert not sub_path.exists(), (
            f"{_full(sub_path)} already exists, but it should be created "
            "by the student’s script, not be present in the initial state."
        )


def test_no_summary_log_yet():
    """
    The summary log should be generated by the student’s script and must
    therefore be absent in the initial state.
    """
    log_path = HOME / "dataset_summary.log"
    assert not log_path.exists(), (
        f"{_full(log_path)} already exists, but it should be created by "
        "the student’s script."
    )