# test_initial_state.py
#
# This pytest suite verifies that the workspace is *clean* before the
# student starts working on the “query_optimization” exercise.
#
# WHAT WE CHECK
# -------------
# 1. The main workspace directory  /home/user/query_optimization
#    must NOT exist yet.
# 2. Consequently, none of the artefacts that are supposed to be
#    created later in the workflow (sample_queries.log, env/, the
#    analysis script, or the final report) may be present.
#
# If any of these things already exist, the tests will fail with a
# descriptive error message that tells the student / grader what needs
# to be cleaned up.

import os
from pathlib import Path

# Absolute paths that must not exist before the student starts
BASE_DIR = Path("/home/user/query_optimization")
SAMPLE_LOG = BASE_DIR / "sample_queries.log"
VENV_DIR = BASE_DIR / "env"
SCRIPT_FILE = BASE_DIR / "optimize_sql.py"
REPORT_FILE = BASE_DIR / "report.json"


def _explain(path: Path) -> str:
    """Return a human-readable explanation for assertion failures."""
    if path.is_dir():
        kind = "directory"
    elif path.is_file():
        kind = "file"
    else:
        kind = "path"
    return f"Unexpected pre-existing {kind}: {path}"


def test_workspace_directory_does_not_exist():
    """The /home/user/query_optimization directory must not exist yet."""
    assert not BASE_DIR.exists(), (
        f"{_explain(BASE_DIR)}\n"
        "The workspace should be created by the student, not be present beforehand."
    )


def test_sample_log_absent():
    """sample_queries.log must not be present before the student creates it."""
    assert not SAMPLE_LOG.exists(), (
        f"{_explain(SAMPLE_LOG)}\n"
        "The sample log file must be generated by the student."
    )


def test_virtualenv_absent():
    """No Python virtual environment should be present before the exercise starts."""
    assert not VENV_DIR.exists(), (
        f"{_explain(VENV_DIR)}\n"
        "The virtual environment must be created by the student."
    )


def test_analysis_script_absent():
    """optimize_sql.py must not exist yet."""
    assert not SCRIPT_FILE.exists(), (
        f"{_explain(SCRIPT_FILE)}\n"
        "The analysis script should be written by the student."
    )


def test_report_absent():
    """report.json must not be present at the beginning of the exercise."""
    assert not REPORT_FILE.exists(), (
        f"{_explain(REPORT_FILE)}\n"
        "The report must be generated by the student's script."
    )