# test_initial_state.py
"""
Pytest suite that validates the *initial* state of the OS / filesystem
BEFORE the student runs any commands for the CSV-cleaning task.

What we check:
1. Presence of the input directory and file.
2. Exact byte-for-byte content of the source CSV (LF line endings only).
3. Absence of any output/processed artefacts.

Only stdlib + pytest are used.
"""

from pathlib import Path
import pytest

HOME = Path("/home/user")
DATA_DIR = HOME / "data"
RAW_CSV = DATA_DIR / "raw_customer_churn.csv"

PROCESSED_DIR = DATA_DIR / "processed"
CHURN_TSV = PROCESSED_DIR / "churn_labels.tsv"
PROCESS_LOG = PROCESSED_DIR / "process.log"

# ----- Expected CSV content (LF line-endings, final newline included) -----
EXPECTED_CSV_CONTENT = (
    "customer_id,name,age,churn,signup_date\n"
    "1,Alice,30,0,2020-01-01\n"
    "2,Bob,45,1,2019-11-21\n"
    "3,Charlie,25,0,2021-06-12\n"
    "4,Denise,33,1,2020-07-30\n"
    "5,Evan,28,0,2022-02-14\n"
)


def test_data_directory_exists():
    """The /home/user/data directory must exist."""
    assert DATA_DIR.is_dir(), (
        f"Required directory missing: {DATA_DIR}. "
        "Create it before running the task."
    )


def test_raw_csv_exists():
    """The raw_customer_churn.csv file must exist and be a regular file."""
    assert RAW_CSV.is_file(), (
        f"Required input file missing: {RAW_CSV}. "
        "Make sure you have placed the raw CSV in the correct location."
    )


def test_raw_csv_content_and_line_endings():
    """
    The CSV file must match the exact expected content, including:
    • Six lines (header + 5 data rows)
    • LF line endings only (\\n, no \\r)
    • Final newline at the end of file
    """
    # Read in binary to detect stray CR characters
    raw_bytes = RAW_CSV.read_bytes()
    text = raw_bytes.decode("utf-8")

    # 1. No CR characters allowed
    assert b"\r" not in raw_bytes, (
        "The CSV file contains CR (\\r) characters; "
        "it must use Unix LF (\\n) line endings only."
    )

    # 2. Exact content check
    assert text == EXPECTED_CSV_CONTENT, (
        "The CSV content does not match the expected template.\n"
        "Expected:\n"
        "----------------------------------------\n"
        f"{EXPECTED_CSV_CONTENT}"
        "----------------------------------------\n"
        "Found:\n"
        "----------------------------------------\n"
        f"{text}"
        "----------------------------------------"
    )

    # 3. Additional structural sanity-check
    lines = text.splitlines()
    assert len(lines) == 6, "CSV must contain exactly 6 lines (header + 5 rows)."


def test_processed_artifacts_absent():
    """
    No processed artefacts should exist yet: the student is meant to create
    them. Fail early if they are already present so the learner starts from
    a clean slate.
    """
    assert not PROCESSED_DIR.exists(), (
        f"Directory {PROCESSED_DIR} already exists. "
        "Start with a clean state so the tests can verify the creation step."
    )
    assert not CHURN_TSV.exists(), (
        f"File {CHURN_TSV} already exists. "
        "It should be generated by your single awk/sed command."
    )
    assert not PROCESS_LOG.exists(), (
        f"File {PROCESS_LOG} already exists. "
        "It should be generated by your single awk/sed command."
    )