# test_initial_state.py
#
# Pytest suite that validates the expected starting conditions *before*
# the student performs any transformation work for the “API → CSV” task.
#
# It checks that:
#   • The three stub JSON response files are present, readable and well-formed.
#   • Each JSON file contains the exact number of records described
#     in the task text.
#   • The /home/user/output path (and any artefacts inside it) do **not** yet
#     exist, guaranteeing that the workspace is clean for the student.
#
# Only Python’s stdlib is used; no third-party modules are required.

import json
from pathlib import Path

import pytest

# --------------------------------------------------------------------------- #
# Constants                                                                   #
# --------------------------------------------------------------------------- #
HOME = Path("/home/user")
API_DIR = HOME / "api_responses"

CUSTOMERS_JSON = API_DIR / "customers.json"
ORDERS_JSON = API_DIR / "orders.json"
PAYMENTS_JSON = API_DIR / "payments.json"

OUTPUT_DIR = HOME / "output"
OUTPUT_CSV = OUTPUT_DIR / "sales_summary_v1.csv"
OUTPUT_LOG = OUTPUT_DIR / "transform.log"


# --------------------------------------------------------------------------- #
# Helper functions                                                            #
# --------------------------------------------------------------------------- #
def _load_json(path: Path):
    """Load JSON file and return the parsed Python object.

    Raises a pytest failure with a helpful message if the file
    cannot be read or parsed.
    """
    assert path.exists(), f"Required file not found: {path}"
    assert path.is_file(), f"Expected a file at {path}, but found something else."

    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except UnicodeDecodeError as exc:
        pytest.fail(f"File {path} is not valid UTF-8: {exc}")
    except json.JSONDecodeError as exc:
        pytest.fail(f"File {path} contains invalid JSON: {exc}")

    return data


def _assert_record_keys(records, expected_keys, *, file_path):
    """Verify each dict in records has exactly the expected_keys set."""
    for idx, rec in enumerate(records):
        assert isinstance(
            rec, dict
        ), f"Record {idx} in {file_path} is not a JSON object: {rec!r}"
        missing = expected_keys - rec.keys()
        extra = rec.keys() - expected_keys
        assert not missing, (
            f"Record {idx} in {file_path} is missing keys: {sorted(missing)}"
        )
        assert not extra, (
            f"Record {idx} in {file_path} has unexpected keys: {sorted(extra)}"
        )


# --------------------------------------------------------------------------- #
# Tests                                                                       #
# --------------------------------------------------------------------------- #
def test_api_directory_present():
    assert API_DIR.exists(), f"Directory missing: {API_DIR}"
    assert API_DIR.is_dir(), f"{API_DIR} exists but is not a directory."


@pytest.mark.parametrize(
    "json_path, expected_len, expected_keys",
    [
        (CUSTOMERS_JSON, 3, {"customer_id", "name", "country"}),
        (ORDERS_JSON, 4, {"order_id", "customer_id", "item", "quantity"}),
        (PAYMENTS_JSON, 4, {"payment_id", "order_id", "amount", "currency"}),
    ],
)
def test_json_files_well_formed(json_path, expected_len, expected_keys):
    data = _load_json(json_path)
    assert isinstance(
        data, list
    ), f"Top-level JSON structure in {json_path} must be an array (list)."
    assert (
        len(data) == expected_len
    ), f"{json_path} should contain {expected_len} records, found {len(data)}."
    _assert_record_keys(data, expected_keys, file_path=json_path)


def test_output_directory_does_not_exist_yet():
    assert not OUTPUT_DIR.exists(), (
        f"The directory {OUTPUT_DIR} already exists. "
        "The workspace should start clean; please remove it before running the transformation."
    )


def test_output_artifacts_absent():
    for path in (OUTPUT_CSV, OUTPUT_LOG):
        assert not path.exists(), (
            f"Unexpected file {path} already present. "
            "Output artefacts must be generated by the student’s solution, "
            "so they should not exist at the initial state."
        )