# test_initial_state.py
"""
Pytest suite that validates the *initial* state of the operating-system
prior to any student action.

DO NOT edit this file when solving the exercise — it exists solely to
document and test the starting conditions.

What we check:
1. /home/user/evidence must exist and be a directory (mode 0755).
2. /home/user/evidence/suspicious.bin must exist, be a **regular file**
   (mode 0644), be empty (0 bytes), and have the well-known SHA-256 hash
   for an empty file.
3. We intentionally do **NOT** check for the presence of
   /home/user/evidence/checksums.log, because that is the output the
   student is expected to create.
"""

import hashlib
import os
import stat
from pathlib import Path

import pytest

EVIDENCE_DIR = Path("/home/user/evidence")
SUSPICIOUS_FILE = EVIDENCE_DIR / "suspicious.bin"

# Constant SHA-256 of an empty file.
EMPTY_SHA256 = (
    "e3b0c44298fc1c149afbf4c8996fb924"
    "27ae41e4649b934ca495991b7852b855"
)


@pytest.fixture(scope="module")
def suspicious_stat():
    """
    Return os.stat_result for suspicious.bin; fail early if missing.
    """
    if not SUSPICIOUS_FILE.exists():
        pytest.fail(
            f"Required file {SUSPICIOUS_FILE} is missing. "
            "The exercise cannot be graded without it."
        )
    return SUSPICIOUS_FILE.stat()


def test_evidence_directory_exists_and_permissions():
    assert EVIDENCE_DIR.exists(), (
        f"Directory {EVIDENCE_DIR} is missing. "
        "It must exist before the exercise starts."
    )
    assert EVIDENCE_DIR.is_dir(), f"{EVIDENCE_DIR} exists but is not a directory."

    mode = EVIDENCE_DIR.stat().st_mode & 0o777
    expected_mode = 0o755
    assert mode == expected_mode, (
        f"{EVIDENCE_DIR} permissions are {oct(mode)}, expected {oct(expected_mode)}."
    )


def test_suspicious_file_exists_and_permissions(suspicious_stat):
    mode = suspicious_stat.st_mode & 0o777
    expected_mode = 0o644
    assert mode == expected_mode, (
        f"{SUSPICIOUS_FILE} permissions are {oct(mode)}, expected {oct(expected_mode)}."
    )


def test_suspicious_file_is_regular(suspicious_stat):
    assert stat.S_ISREG(suspicious_stat.st_mode), (
        f"{SUSPICIOUS_FILE} exists but is not a regular file."
    )


def test_suspicious_file_size_is_zero_bytes(suspicious_stat):
    assert suspicious_stat.st_size == 0, (
        f"{SUSPICIOUS_FILE} should be 0 bytes, "
        f"found {suspicious_stat.st_size} bytes."
    )


def test_suspicious_file_sha256_is_expected():
    """
    The SHA-256 of an empty file is well-known and should match.
    """
    sha256 = hashlib.sha256()
    with SUSPICIOUS_FILE.open("rb") as fp:
        for chunk in iter(lambda: fp.read(8192), b""):
            sha256.update(chunk)
    digest = sha256.hexdigest()

    assert digest == EMPTY_SHA256, (
        f"SHA-256 of {SUSPICIOUS_FILE} is {digest}, expected {EMPTY_SHA256}. "
        "The file may have been altered."
    )