# test_initial_state.py
#
# This test-suite verifies that the operating-system / filesystem is in the
# expected *initial* state, i.e. before the student runs any provisioning
# commands described in the assignment.  In particular, we confirm that the
# directory structure is either absent or empty of task-specific artefacts
# and that the required tooling (sqlite3 CLI) is available.

import os
import subprocess
from pathlib import Path

PROVISIONING_DIR = Path("/home/user/provisioning")
DB_FILE          = PROVISIONING_DIR / "infra.db"
EXPORT_FILE      = PROVISIONING_DIR / "server_list.txt"


def test_sqlite3_cli_is_installed_and_usable():
    """
    The SQLite CLI must be available in the PATH *before* the student starts
    working.  We do a very small sanity check by invoking `sqlite3 -version`.
    """
    try:
        completed = subprocess.run(
            ["sqlite3", "-version"],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        pytest.fail(
            "`sqlite3` executable not found in PATH – it must be installed and "
            "callable before the provisioning workflow begins."
        )

    # The command should emit a non-empty version string on stdout.
    assert completed.stdout.strip(), (
        "`sqlite3 -version` returned an empty string – unexpected output.  "
        "Ensure the SQLite CLI is functioning correctly."
    )


def test_provisioning_directory_may_or_may_not_exist_but_has_no_task_files():
    """
    The assignment allows /home/user/provisioning to *either* exist or be
    created by the student.  What must *not* be present at this stage are the
    task-specific artefacts `infra.db` and `server_list.txt`.
    """
    if not PROVISIONING_DIR.exists():
        # Directory absent: perfectly fine at this stage.
        return

    # Directory exists – it must be a directory, not a file.
    assert PROVISIONING_DIR.is_dir(), (
        f"{PROVISIONING_DIR} exists but is not a directory.  "
        "Please remove or rename the conflicting file before starting."
    )

    # The SQLite database should not yet exist.
    assert not DB_FILE.exists(), (
        f"Database file {DB_FILE} is already present.  "
        "The provisioning script must create this file itself; "
        "please start from a clean state."
    )

    # The export file should not yet exist.
    assert not EXPORT_FILE.exists(), (
        f"Export file {EXPORT_FILE} is already present.  "
        "It must be generated by the provisioning workflow; "
        "please remove it before starting."
    )