# test_initial_state.py
#
# This test-suite validates the **initial** filesystem state that is expected
# *before* the student starts working on the “cloud-costs” Makefile exercise.
#
# DO NOT edit the paths—tests must refer to absolute paths only.

import os
from pathlib import Path

RAW_DIR = Path("/home/user/cloud-costs/raw")
OUTPUT_DIR = Path("/home/user/cloud-costs/output")
MAKEFILE_PATH = Path("/home/user/cloud-costs/Makefile")

AWS_CSV = RAW_DIR / "aws_costs.csv"
GCP_CSV = RAW_DIR / "gcp_costs.csv"
AZURE_CSV = RAW_DIR / "azure_costs.csv"

EXPECTED_HEADER = "service,cost,month\n"

EXPECTED_RAW_CONTENT = {
    AWS_CSV: [
        "service,cost,month\n",
        "EC2,23.50,2023-06\n",
        "S3,30.70,2023-06\n",
    ],
    GCP_CSV: [
        "service,cost,month\n",
        "ComputeEngine,15.30,2023-06\n",
        "CloudStorage,14.50,2023-06\n",
    ],
    AZURE_CSV: [
        "service,cost,month\n",
        "VM,20.00,2023-06\n",
        "BlobStorage,21.00,2023-06\n",
    ],
}


def read_file_lines(path: Path):
    """Read file and return its lines ending with '\n' exactly as stored."""
    with path.open("r", encoding="utf-8") as fp:
        return fp.readlines()


def test_required_directories_exist():
    assert RAW_DIR.is_dir(), f"Required directory '{RAW_DIR}' is missing."
    # The output directory should exist, even if empty.
    assert OUTPUT_DIR.is_dir(), f"Required directory '{OUTPUT_DIR}' is missing."


def test_raw_csv_files_exist():
    for csv_path in (AWS_CSV, GCP_CSV, AZURE_CSV):
        assert csv_path.is_file(), f"Required raw CSV file '{csv_path}' is missing."


def test_raw_csv_headers_are_correct():
    for csv_path in (AWS_CSV, GCP_CSV, AZURE_CSV):
        header = read_file_lines(csv_path)[0]
        assert (
            header == EXPECTED_HEADER
        ), f"File '{csv_path}' header is incorrect. Expected '{EXPECTED_HEADER.strip()}', got '{header.strip()}'."


def test_raw_csv_file_contents_are_unchanged():
    """
    Guard against accidental modification to the seed data; the exercise
    depends on these exact numbers.
    """
    for path, expected_lines in EXPECTED_RAW_CONTENT.items():
        actual_lines = read_file_lines(path)
        assert (
            actual_lines == expected_lines
        ), f"File '{path}' contents have changed.\nExpected:\n{expected_lines}\nActual:\n{actual_lines}"


def test_makefile_not_present_yet():
    """
    The exercise instructions ask the student to *author* a Makefile.
    Therefore, at the starting point no Makefile should exist.
    """
    assert (
        not MAKEFILE_PATH.exists()
    ), f"Makefile '{MAKEFILE_PATH}' should not exist before the student starts."


def test_combined_summary_not_present_yet():
    """
    The consolidated summary must be generated by the student's Makefile.
    It should not pre-exist in the initial state.
    """
    combined_csv = OUTPUT_DIR / "combined_summary.csv"
    assert (
        not combined_csv.exists()
    ), f"Pre-generated output '{combined_csv}' found; it should not exist yet."