# test_initial_state.py
#
# This pytest suite verifies the *initial* filesystem state before
# the student begins their work.  It checks that the raw log file and its
# containing directory exist exactly as described, and that the output
# directory/report do *not* yet exist.

import os
import pytest
from pathlib import Path

HOME = Path("/home/user")
LOGS_DIR = HOME / "logs"
LOG_FILE = LOGS_DIR / "container_stats_2023-09-15.log"
REPORTS_DIR = HOME / "reports"
REPORT_FILE = REPORTS_DIR / "capacity_report.txt"


EXPECTED_LOG_LINES = [
    "container_id,name,cpu_percent,mem_usage_mb\n",
    "1db3aa112,web_frontend,35.5,512\n",
    "2ab4cc223,database,82.7,1500\n",
    "3cd5dd334,cache,18.2,256\n",
    "4de6ee445,worker,77.9,1100\n",
    "5ef7ff556,nginx_proxy,23.0,450\n",
    "6fa8gg667,analytics,69.4,2048\n",
]

# --------------------------------------------------------------------------- #
# Directory / File Presence
# --------------------------------------------------------------------------- #

def test_logs_directory_exists():
    assert LOGS_DIR.is_dir(), (
        f"Required directory {LOGS_DIR} is missing. "
        "The initial state must include this directory."
    )


def test_log_file_exists():
    assert LOG_FILE.is_file(), (
        f"Required log file {LOG_FILE} is missing. "
        "The task cannot proceed without this file."
    )


def test_reports_directory_absent():
    # The student is supposed to create this directory as part of the task.
    assert not REPORTS_DIR.exists(), (
        f"Directory {REPORTS_DIR} should NOT exist before the task begins. "
        "It must be created by the student's code."
    )


def test_report_file_absent():
    assert not REPORT_FILE.exists(), (
        f"Report file {REPORT_FILE} should NOT exist yet. "
        "It will be generated by the student's solution."
    )

# --------------------------------------------------------------------------- #
# Log File Content Verification
# --------------------------------------------------------------------------- #

def test_log_file_contents_exact():
    """
    The log file must contain exactly seven lines:
    one header line followed by six data lines, all matching the spec and
    all ending with a UNIX newline character ('\\n').
    """
    with LOG_FILE.open("r", encoding="utf-8") as f:
        actual_lines = f.readlines()

    # Helpful message if counts differ
    assert len(actual_lines) == len(EXPECTED_LOG_LINES), (
        f"{LOG_FILE} should contain {len(EXPECTED_LOG_LINES)} lines, "
        f"but {len(actual_lines)} line(s) were found."
    )

    # Check each line for exact match (including trailing newline)
    mismatches = [
        (idx + 1, exp_line, act_line)
        for idx, (exp_line, act_line) in enumerate(zip(EXPECTED_LOG_LINES, actual_lines))
        if exp_line != act_line
    ]

    assert not mismatches, format_mismatch_message(mismatches)


# --------------------------------------------------------------------------- #
# Helper for readable assertion failures
# --------------------------------------------------------------------------- #

def format_mismatch_message(mismatches):
    """
    Build a human-readable error message enumerating all differing lines.
    Each entry contains the line number, the expected text, and the actual text.
    """
    parts = ["The contents of the log file differ from the expected initial state:"]
    for line_no, exp, act in mismatches:
        parts.append(
            f"  Line {line_no}: expected {repr(exp)}, got {repr(act)}"
        )
    return "\n".join(parts)