# test_initial_state.py
#
# This pytest suite verifies that the starting operating-system / filesystem
# state is clean **before** the student begins the “dedicated SSH identity”
# exercise.  If any of these tests fail it means the environment has already
# been modified (keys, config stanza or audit log already present) and the
# setup is therefore NOT in its required pristine state.

import os
from pathlib import Path
import pytest

HOME = Path("/home/user")
SSH_DIR = HOME / ".ssh"
KEY_PRIVATE = SSH_DIR / "build_artifact_deploy"
KEY_PUBLIC = SSH_DIR / "build_artifact_deploy.pub"
SSH_CONFIG = SSH_DIR / "config"

AUDIT_DIR = HOME / "ssh_setup"
AUDIT_LOG = AUDIT_DIR / "ssh_key_setup.log"

STANZA_LINES = [
    "Host artifact-server",
    "HostName artifact.example.com",
    "User deploy",
    "IdentityFile /home/user/.ssh/build_artifact_deploy",
]


@pytest.mark.describe("SSH key material must NOT yet exist")
def test_key_files_absent():
    assert not KEY_PRIVATE.exists(), (
        f"Pre-flight failure: {KEY_PRIVATE} already exists – the private key "
        f"must be generated by the student, not pre-seeded."
    )
    assert not KEY_PUBLIC.exists(), (
        f"Pre-flight failure: {KEY_PUBLIC} already exists – the public key "
        f"must be generated by the student, not pre-seeded."
    )


@pytest.mark.describe("SSH config must NOT yet contain the required host stanza")
def test_config_does_not_contain_stanza():
    if not SSH_CONFIG.exists():
        # No config file yet → definitely clean.
        return

    content = SSH_CONFIG.read_text(encoding="utf-8", errors="ignore").splitlines()

    for expected_line in STANZA_LINES:
        assert expected_line not in content, (
            f"Pre-flight failure: '{expected_line}' already present in "
            f"{SSH_CONFIG}.  The exercise requires the student to append the "
            "stanza themselves."
        )


@pytest.mark.describe("Audit log must NOT yet exist")
def test_audit_log_absent():
    assert not AUDIT_LOG.exists(), (
        f"Pre-flight failure: {AUDIT_LOG} already exists – the student must "
        "create it during the exercise."
    )