# test_initial_state.py
#
# Pytest suite that validates the *initial* state of the operating system
# BEFORE the student starts working on the “timezone_debug” exercise.
#
# These tests guarantee that no artefacts required by the assignment
# already exist.  If any of the expected output directories/files are found
# beforehand, the environment is considered “tainted” and the suite will
# fail with a clear, actionable message.
#
# NOTE:  • Uses only the Python standard library + pytest.
#        • Relies exclusively on absolute paths.
#        • Does *not* test for the final output, only for its absence.

import os
from pathlib import Path

import pytest

# Constant paths that the student is supposed to create.
BASE_DIR = Path("/home/user/timezone_debug")
ENV_SNAPSHOT = BASE_DIR / "env_snapshot.log"
TZ_CONVERSION = BASE_DIR / "tz_conversion.log"


def _pretty_mode(mode_bits: int) -> str:
    """
    Helper: return an octal permission string such as '0o755'.
    """
    return oct(mode_bits & 0o777)


@pytest.fixture(scope="module")
def existing_paths():
    """
    Collect information about whether the directory and/or files already
    exist.  This fixture runs once per test module to avoid redundant
    filesystem calls.
    """
    return {
        "base_dir_exists": BASE_DIR.exists(),
        "env_snapshot_exists": ENV_SNAPSHOT.exists(),
        "tz_conversion_exists": TZ_CONVERSION.exists(),
    }


def test_base_directory_absent(existing_paths):
    """
    The parent directory must *not* exist yet.  The assignment explicitly
    tells the student to create /home/user/timezone_debug if it does not
    already exist, therefore a pre-existing directory would indicate that
    the environment is not pristine.
    """
    assert (
        not existing_paths["base_dir_exists"]
    ), (
        f"Unexpected directory found at '{BASE_DIR}'.\n"
        "The initial state must be clean so that the student can create it "
        "during the exercise.  Please remove/rename this directory or start "
        "the grader in a fresh environment."
    )


def test_env_snapshot_absent(existing_paths):
    """
    env_snapshot.log must not be present before the student’s commands run.
    """
    assert (
        not existing_paths["env_snapshot_exists"]
    ), (
        f"Unexpected file found at '{ENV_SNAPSHOT}'.\n"
        "This file is supposed to be generated by the student; its presence "
        "indicates that the workspace is already populated."
    )


def test_tz_conversion_absent(existing_paths):
    """
    tz_conversion.log must not be present before the student’s commands run.
    """
    assert (
        not existing_paths["tz_conversion_exists"]
    ), (
        f"Unexpected file found at '{TZ_CONVERSION}'.\n"
        "This file is supposed to be generated by the student; its presence "
        "indicates that the workspace is already populated."
    )