# test_initial_state.py
#
# Pytest checks to ensure the operating-system / filesystem state is
# “clean” **before** the student performs the required hardening steps.
#
# These tests will FAIL if any of the artefacts that the student is
# supposed to create already exist or if ~/.bashrc already ends with the
# two ulimit lines.  A failure therefore signals that the playground is
# not in the expected initial state.

import os
from pathlib import Path
import pytest

HOME = Path("/home/user")
HARDEN_DIR = HOME / "hardening"
CONFIG_FILE = HARDEN_DIR / "99-security.conf"
LOG_FILE = HARDEN_DIR / "hardening_summary.log"
BASHRC = HOME / ".bashrc"


def _read_file_lines(path: Path):
    """Return a list of lines in *path* with trailing newlines stripped.
    If the file does not exist, return an empty list."""
    try:
        with path.open("r", encoding="utf-8") as fh:
            return [ln.rstrip("\n") for ln in fh.readlines()]
    except FileNotFoundError:
        return []


def test_hardening_directory_absent():
    assert not HARDEN_DIR.exists(), (
        f"Directory {HARDEN_DIR} already exists. "
        "The system must start WITHOUT this directory so the student can create it."
    )


def test_config_file_absent():
    assert not CONFIG_FILE.exists(), (
        f"Configuration file {CONFIG_FILE} already exists. "
        "It should not be present before the student’s hardening steps."
    )


def test_log_file_absent():
    assert not LOG_FILE.exists(), (
        f"Verification log {LOG_FILE} already exists. "
        "It must be generated by the student’s commands, not pre-seeded."
    )


def test_bashrc_not_already_hardened():
    """
    ~/.bashrc must NOT already end with the two expected ulimit lines.

    The check is tolerant of a missing ~/.bashrc: in that case an empty
    list of lines is returned and the assertion passes.
    """
    lines = _read_file_lines(BASHRC)

    # Compare only if there are at least two lines;
    # otherwise, it's impossible for the file to end with the target lines.
    if len(lines) >= 2:
        tail_ok = not (
            lines[-2] == "ulimit -S core 0" and lines[-1] == "ulimit -H core 0"
        )
        assert tail_ok, (
            f"{BASHRC} already ends with the required ulimit lines.\n"
            "The file must *not* contain these lines yet so the student can append them."
        )
    else:
        # File missing or too short — initial state is acceptable.
        assert True