# test_initial_state.py
#
# Pytest suite that validates the *initial* operating-system / filesystem
# state **before** the student performs any action for the “FinOps audit”
# exercise.
#
# Expectations for the pristine image:
#
# 1. The student-created directory /home/user/finops_audit must NOT exist.
# 2. The log file   /home/user/finops_audit/pip_dupes.log must NOT exist.
# 3. The canonical home directory /home/user itself MUST exist.
# 4. There must be NO duplicate pip distributions (same package name
#    installed simultaneously at two different versions).  This guarantees
#    that the student’s correct answer will be the single word “NONE”.
#
# Only the Python standard library and pytest are used.

import os
import subprocess
import sys
from pathlib import Path

HOME_DIR = Path("/home/user")
AUDIT_DIR = HOME_DIR / "finops_audit"
LOG_FILE = AUDIT_DIR / "pip_dupes.log"


def test_home_directory_exists():
    """The baseline image must provide the canonical /home/user directory."""
    assert HOME_DIR.is_dir(), (
        "Expected the home directory '/home/user' to exist in the base image. "
        "Its absence indicates an unexpected execution environment."
    )


def test_audit_directory_absent():
    """The finops_audit directory must NOT exist before the student runs their command."""
    assert not AUDIT_DIR.exists(), (
        f"Directory '{AUDIT_DIR}' already exists, but it should only be "
        "created by the student’s solution."
    )


def test_log_file_absent():
    """The pip_dupes.log file must NOT exist before the student runs their command."""
    assert not LOG_FILE.exists(), (
        f"File '{LOG_FILE}' already exists, but it should be generated by the "
        "student’s solution."
    )


def _get_duplicate_distributions():
    """
    Return a sorted list of distribution names (case-normalised to lower case)
    that are installed more than once at *different* versions.

    We intentionally rely on `pip list --format=freeze` rather than the JSON
    output because the JSON format already deduplicates packages, whereas
    `freeze` will reveal multiple lines for packages installed at multiple
    versions (the exact symptom we need to detect).
    """
    try:
        raw = subprocess.check_output(
            [sys.executable, "-m", "pip", "list", "--format=freeze"],
            text=True,
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as exc:
        pytest.fail(
            f"Unable to execute pip to inspect the environment. "
            f"Command output was:\n{exc.output}"
        )

    # Map: canonicalised (lower-case) package name -> set of versions observed
    packages = {}

    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        # Handle both 'name==version' and 'name @ git+...' style lines.
        if "==" in line:
            name, version = line.split("==", 1)
        elif " @ " in line:
            name, version = line.split(" @ ", 1)
        else:
            # Unknown / unparseable line format; ignore for duplicate purposes.
            continue

        packages.setdefault(name.lower(), set()).add(version)

    # A duplicate is a single distribution installed simultaneously
    # at *more than one* distinct version.
    duplicates = sorted(name for name, versions in packages.items() if len(versions) > 1)
    return duplicates


def test_no_duplicate_pip_packages():
    """The pristine environment must have ZERO duplicate pip distributions."""
    duplicates = _get_duplicate_distributions()
    assert not duplicates, (
        "The base image contains duplicate pip package installations:\n"
        + "\n".join(f"  - {name}" for name in duplicates)
    )