# test_initial_state.py
#
# This test-suite is executed **before** the learner runs any commands.
# It confirms that the working environment is clean and that none of the
# artefacts required by the assignment already exist.
#
# If any of the assertions below fail, it means the student (or an earlier
# process) has already created files / directories that are supposed to be
# generated *during* the exercise, and the environment is therefore in an
# unexpected state.

import os
from pathlib import Path

HOME = Path("/home/user")
AUDIT_DIR = HOME / "dns_audit"
HOSTS_OVERRIDE = AUDIT_DIR / "hosts_override"
RESOLUTION_LOG = AUDIT_DIR / "resolution.log"


def test_home_directory_exists_and_is_directory():
    """
    Sanity-check that the base home directory is present.
    This is the only path that *should* exist at this point.
    """
    assert HOME.exists(), f"Expected home directory {HOME} to exist."
    assert HOME.is_dir(), f"Expected {HOME} to be a directory."


def test_dns_audit_directory_absent():
    """
    The dns_audit directory should *not* exist before the student begins.
    """
    assert not AUDIT_DIR.exists(), (
        f"The directory {AUDIT_DIR} already exists, "
        "but it should be created by the student's solution."
    )


def test_hosts_override_absent():
    """
    The hosts_override file must not be present yet.
    """
    assert not HOSTS_OVERRIDE.exists(), (
        f"The file {HOSTS_OVERRIDE} already exists, "
        "but it should be generated by the student's solution."
    )


def test_resolution_log_absent():
    """
    The resolution.log file must not be present yet.
    """
    assert not RESOLUTION_LOG.exists(), (
        f"The file {RESOLUTION_LOG} already exists, "
        "but it should be generated by the student's solution."
    )