# test_initial_state.py
#
# These tests validate the *initial* state of the operating-system / filesystem
# before the student begins the exercise.  Nothing related to the task should
# exist yet.  If any of these assertions fail, the workspace is already “dirty”
# and would give the student an unfair (or impossible) starting point.

from pathlib import Path

HOME = Path("/home/user")
BACKUPS_DIR = HOME / "backups"
SCRIPTS_DIR = BACKUPS_DIR / "scripts"
VENV_DIR = SCRIPTS_DIR / "archive_env"
LOG_FILE = BACKUPS_DIR / "archive_env_setup.log"


def test_virtual_environment_absent():
    """
    The virtual-environment directory must *not* exist before the student
    starts the task.  If it is already present, the initial state is invalid.
    """
    assert not VENV_DIR.exists(), (
        f"Precondition failed: {VENV_DIR} already exists.\n"
        "The virtual environment should be created by the student; "
        "it must not be present in the initial state."
    )


def test_activate_script_absent():
    """
    Because the venv directory must be absent, its activate script must be
    absent as well.  This separate check gives a clearer failure reason if the
    directory structure was partially created.
    """
    activate_script = VENV_DIR / "bin" / "activate"
    assert not activate_script.exists(), (
        f"Precondition failed: {activate_script} already exists.\n"
        "The activate script indicates that a virtual environment is already "
        "in place, which violates the clean-slate requirement."
    )


def test_log_file_absent():
    """
    The setup log should also not exist yet.  Its presence would mean the task
    was already completed (or partially completed) prior to testing.
    """
    assert not LOG_FILE.exists(), (
        f"Precondition failed: {LOG_FILE} already exists.\n"
        "The log file must be generated by the student; it should not be part "
        "of the initial filesystem state."
    )