# test_initial_state.py
#
# This pytest-suite verifies the *initial* state of the filesystem and the
# Git repository *before* the student starts working on the assignment.
#
# DO NOT edit this file.  The grader relies on the expectations encoded here.
import subprocess
from pathlib import Path

import pytest

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------
REPO_PATH = Path("/home/user/edge-devices")
VERSION_FILE = REPO_PATH / "VERSION"
CHANGELOG_FILE = REPO_PATH / "CHANGELOG.md"
RELEASES_DIR = REPO_PATH / "releases"
RELEASE_LOG_FILE = RELEASES_DIR / "v0.9.5.log"
EXPECTED_VERSION_LINE = "0.9.4\n"
UNEXPECTED_NEW_VERSION_STRING = "## [0.9.5]"
NEW_TAG_NAME = "v0.9.5"


# -----------------------------------------------------------------------------
# Helper functions
# -----------------------------------------------------------------------------
def run_git(args, repo=REPO_PATH):
    """
    Execute a git command inside the repository and return its output as text.
    """
    completed = subprocess.run(
        ["git", "-C", str(repo), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
        text=True,
    )
    return completed.stdout.strip()


# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------
def test_repository_directory_exists():
    assert REPO_PATH.is_dir(), (
        f"Expected Git repository directory {REPO_PATH} to exist. "
        "It is missing."
    )
    git_dir = REPO_PATH / ".git"
    assert git_dir.is_dir(), (
        f"Directory {REPO_PATH} exists, but {git_dir} is not present. "
        "Is this a Git repository?"
    )


def test_default_branch_is_main():
    head_branch = run_git(["rev-parse", "--abbrev-ref", "HEAD"])
    assert (
        head_branch == "main"
    ), f"Default branch should be 'main' but is '{head_branch}'."


def test_version_file_has_old_version():
    assert VERSION_FILE.is_file(), (
        f"VERSION file expected at {VERSION_FILE} but was not found."
    )
    content = VERSION_FILE.read_text()
    assert (
        content == EXPECTED_VERSION_LINE
    ), (
        "VERSION file should contain the original version '0.9.4' followed by a "
        "newline. Current content:\n"
        f"{content!r}"
    )


def test_changelog_does_not_have_new_section_yet():
    assert CHANGELOG_FILE.is_file(), (
        f"CHANGELOG.md expected at {CHANGELOG_FILE} but was not found."
    )
    changelog_text = CHANGELOG_FILE.read_text()
    assert (
        UNEXPECTED_NEW_VERSION_STRING not in changelog_text
    ), (
        "CHANGELOG.md already contains the 0.9.5 section, but it should not be "
        "present before the task is performed."
    )
    assert (
        changelog_text.startswith("# Changelog") or changelog_text.startswith("## [0.9.4]")
    ), (
        "CHANGELOG.md does not appear to have the expected initial header or "
        "0.9.4 section. Please verify the starting template."
    )


def test_git_tag_for_new_version_missing():
    tags = run_git(["tag", "-l", NEW_TAG_NAME]).splitlines()
    assert (
        NEW_TAG_NAME not in tags
    ), f"Git tag '{NEW_TAG_NAME}' already exists, but it should be created by the student."


def test_release_log_file_not_yet_present():
    assert not RELEASE_LOG_FILE.exists(), (
        f"Release log file {RELEASE_LOG_FILE} already exists, but it should be "
        "created by the student during the task."
    )