# test_initial_state.py
#
# This pytest file verifies that the machine starts in the expected
# initial state *before* the student runs their one-liner command.
#
# What we check:
# 1. /home/user/scripts  – must exist, must be a directory, must be empty.
# 2. /home/user/.bashrc  – must exist and contain exactly the two default
#    lines (each terminated by a single newline) and *no* reference to
#    UTIL_SCRIPTS.
# 3. /home/user/task_completion.log  – must **not** exist yet.
#
# If any of these conditions fail, the corresponding assertion message
# will clearly explain what is wrong so the student knows how to fix it.

import os
from pathlib import Path
import pytest


SCRIPTS_DIR = Path("/home/user/scripts")
BASHRC_FILE = Path("/home/user/.bashrc")
LOG_FILE = Path("/home/user/task_completion.log")

EXPECTED_BASHRC_CONTENT = (
    "# .bashrc autogenerated for training\n"
    "# feel free to add new exports below this line\n"
)


def test_scripts_directory_exists_and_is_empty():
    """
    The /home/user/scripts directory must already exist and be empty.
    """
    assert SCRIPTS_DIR.is_dir(), (
        "Required directory /home/user/scripts does not exist "
        "or is not a directory."
    )

    # Collect non-hidden items inside /home/user/scripts
    non_hidden_contents = [
        p.name for p in SCRIPTS_DIR.iterdir() if not p.name.startswith(".")
    ]

    assert not non_hidden_contents, (
        "Directory /home/user/scripts is expected to be empty, "
        f"but contains: {', '.join(non_hidden_contents)}"
    )


def test_bashrc_initial_contents():
    """
    /home/user/.bashrc must exist and contain only the two boiler-plate lines,
    each ended by a single newline.  It must NOT yet reference UTIL_SCRIPTS.
    """
    assert BASHRC_FILE.is_file(), "Required file /home/user/.bashrc is missing."

    content = BASHRC_FILE.read_text(encoding="utf-8")

    # Exact match with expected boiler-plate (including final newline)
    assert content == EXPECTED_BASHRC_CONTENT, (
        "Unexpected content in /home/user/.bashrc.\n"
        "Expected exactly:\n"
        f"{EXPECTED_BASHRC_CONTENT!r}\n"
        "But found:\n"
        f"{content!r}"
    )

    # Redundant safety check: ensure the export line isn't already present.
    assert "export UTIL_SCRIPTS=" not in content, (
        "export UTIL_SCRIPTS line should not be present in /home/user/.bashrc "
        "before the task begins."
    )


def test_task_completion_log_absent():
    """
    The log file must not exist before the student performs the task.
    """
    assert not LOG_FILE.exists(), (
        "/home/user/task_completion.log already exists, "
        "but it should be created only after the task is completed."
    )