#!/bin/bash
set -euo pipefail

python3 - <<'PY'
import base64
import gzip
import hashlib
import io
import json
import os
import shutil
import tarfile
from collections import OrderedDict
from pathlib import Path

ROOT = Path("/app/yarn-lab")
PKG = ROOT / "packages"
MIRROR = ROOT / "mirror"
MTIME = 1782345600

def minjson(obj):
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False).encode() + b"\n"

def read(rel):
    return (PKG / rel).read_bytes()

def make_tgz(out, members):
    tar_buf = io.BytesIO()
    with tarfile.open(fileobj=tar_buf, mode="w") as tar:
        for name, data in members:
            info = tarfile.TarInfo(name)
            info.size = len(data)
            info.mtime = MTIME
            info.uid = 0
            info.gid = 0
            info.uname = ""
            info.gname = ""
            info.mode = 0o644
            tar.addfile(info, io.BytesIO(data))
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("wb") as fh:
        with gzip.GzipFile(filename="", mode="wb", compresslevel=9, mtime=0, fileobj=fh) as gz:
            gz.write(tar_buf.getvalue())

shutil.rmtree(MIRROR, ignore_errors=True)
MIRROR.mkdir(parents=True)

edge_pkg = OrderedDict([
    ("name", "@acme/edge-flags"),
    ("version", "1.2.0"),
    ("description", "Offline edge feature flags"),
    ("type", "module"),
    ("main", "src/index.js"),
    ("files", ["src", "README.md", "LICENSE"]),
    ("license", "MIT"),
])
policy_pkg = OrderedDict([
    ("name", "@acme/policy-table"),
    ("version", "0.5.1"),
    ("description", "Offline policy defaults table"),
    ("type", "module"),
    ("main", "index.js"),
    ("files", ["index.js", "data"]),
    ("dependencies", OrderedDict([("@acme/edge-flags", "1.2.0")])),
    ("license", "Apache-2.0"),
])

edge_name = "@acme-edge-flags-1.2.0.tgz"
policy_name = "@acme-policy-table-0.5.1.tgz"

make_tgz(MIRROR / edge_name, [
    ("package/package.json", minjson(edge_pkg)),
    ("package/README.md", read("edge-flags/README.md")),
    ("package/LICENSE", read("edge-flags/LICENSE")),
    ("package/src/index.js", read("edge-flags/src/index.js")),
])

make_tgz(MIRROR / policy_name, [
    ("package/package.json", minjson(policy_pkg)),
    ("package/index.js", read("policy-table/index.js")),
    ("package/data/defaults.json", read("policy-table/data/defaults.json")),
])

def digests(path):
    data = path.read_bytes()
    sha1 = hashlib.sha1(data).hexdigest()
    sha512 = base64.b64encode(hashlib.sha512(data).digest()).decode()
    return sha1, sha512

edge_sha1, edge_sha512 = digests(MIRROR / edge_name)
policy_sha1, policy_sha512 = digests(MIRROR / policy_name)

lock = (
    "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
    "# yarn lockfile v1\n"
    "\n"
    '"@acme/edge-flags@1.2.0":\n'
    '  version "1.2.0"\n'
    f'  resolved "file:mirror/{edge_name}#{edge_sha1}"\n'
    f'  integrity sha512-{edge_sha512}\n'
    "\n"
    '"@acme/policy-table@0.5.1":\n'
    '  version "0.5.1"\n'
    f'  resolved "file:mirror/{policy_name}#{policy_sha1}"\n'
    f'  integrity sha512-{policy_sha512}\n'
    "  dependencies:\n"
    '    "@acme/edge-flags" "1.2.0"\n'
)
(ROOT / "yarn.lock").write_text(lock, encoding="utf-8")
(ROOT / ".yarnrc").write_text('yarn-offline-mirror "./mirror"\nyarn-offline-mirror-pruning true\n', encoding="utf-8")
PY
