# test_initial_state.py
#
# Pytest suite that verifies the **initial** state of the workspace,
# i.e. *before* the student starts working on the task.
#
# Checked assumptions
# -------------------
# 1. The CSV source file exists and contains the exact expected data.
# 2. The SQLite database does NOT exist yet.
# 3. The output directory (and therefore the TSV file) do NOT exist yet.
#
# Any failure message should give a clear hint about what is wrong.

from pathlib import Path
import pytest

# Base paths (hard-coded absolute paths as required by the spec)
BASE_DIR = Path("/home/user/projects/sales_analysis")
CSV_FILE = BASE_DIR / "sales_q1.csv"
DB_FILE = BASE_DIR / "sales.db"
OUTPUT_DIR = BASE_DIR / "output"
TSV_FILE = OUTPUT_DIR / "region_revenue.tsv"

# Expected CSV content (without trailing newlines)
EXPECTED_CSV_CONTENT = [
    "region,product,quantity,unit_price",
    "North,Widget,10,2.5",
    "South,Gadget,5,5.25",
    "East,Widget,7,2.5",
    "West,Gizmo,3,10.00",
]


def _read_file_lines(path: Path):
    """
    Helper that returns all lines of a file with trailing '\n' stripped.
    """
    with path.open("r", encoding="utf-8") as f:
        # strip only the newline; keep any other whitespace intact
        return [line.rstrip("\n") for line in f.readlines()]


def test_csv_file_exists_with_correct_content():
    """
    The starter CSV must exist and its content must match exactly
    the lines given in the task description.
    """
    assert CSV_FILE.is_file(), (
        f"Expected CSV file not found at {CSV_FILE}. "
        "Make sure the repository contains the starter data."
    )

    # Read and validate line-by-line content
    actual_lines = _read_file_lines(CSV_FILE)
    assert actual_lines == EXPECTED_CSV_CONTENT, (
        "Content of the CSV file does not match the expected starter data.\n"
        f"Expected:\n{EXPECTED_CSV_CONTENT}\n\nGot:\n{actual_lines}"
    )


def test_database_does_not_exist_yet():
    """
    The SQLite database should NOT exist before the student creates it.
    """
    assert not DB_FILE.exists(), (
        f"The database '{DB_FILE}' already exists. "
        "Please remove it so the student can create it from scratch."
    )


def test_output_directory_does_not_exist_yet():
    """
    The output directory (and therefore its TSV file) should not exist yet.
    """
    assert not OUTPUT_DIR.exists(), (
        f"The directory '{OUTPUT_DIR}' is already present. "
        "It must be absent at the beginning so that the student can create it."
    )
    # If the directory does not exist, the TSV file certainly doesn't,
    # but the explicit assertion gives a clearer error message.
    assert not TSV_FILE.exists(), (
        f"The TSV file '{TSV_FILE}' is already present. "
        "It should be generated by the student during the exercise."
    )