# test_initial_state.py
#
# This test-suite validates that the operating-system / filesystem is in the
# REQUIRED INITIAL STATE *before* the student starts working on the exercise.
#
# NOTHING that belongs to the final solution is allowed to exist yet.
# If any of the assertions below fail, the environment is “dirty” and must be
# cleaned up before the student receives the task.

import os
from pathlib import Path

HOME = Path("/home/user")
CONF_DIR = HOME / "db_admin" / "conf"
PSQLRC = CONF_DIR / ".psqlrc"
BASHRC = HOME / ".bashrc"
SETUP_LOG = HOME / "db_admin" / "setup.log"


def test_conf_directory_absent():
    """
    The directory /home/user/db_admin/conf must NOT exist yet.
    """
    assert not CONF_DIR.exists(), (
        f"Precondition failed: '{CONF_DIR}' already exists. "
        "The exercise expects this directory to be created by the student."
    )


def test_psqlrc_absent():
    """
    The file /home/user/db_admin/conf/.psqlrc must NOT exist yet.
    """
    assert not PSQLRC.exists(), (
        f"Precondition failed: '{PSQLRC}' already exists. "
        "The exercise expects this file to be created by the student."
    )


def test_bashrc_has_no_psql_editor_export():
    """
    /home/user/.bashrc must NOT already contain the line:

        export PSQL_EDITOR="nano"

    The student will add this line exactly once.
    (An absent .bashrc is also acceptable at this point.)
    """
    if not BASHRC.exists():
        # No .bashrc yet: perfectly fine.
        return

    # Read the file safely as text; assume UTF-8.
    with BASHRC.open("r", encoding="utf-8", errors="ignore") as fh:
        bashrc_lines = [line.rstrip("\n") for line in fh]

    assert 'export PSQL_EDITOR="nano"' not in bashrc_lines, (
        f"Precondition failed: '{BASHRC}' already contains "
        'the line `export PSQL_EDITOR="nano"`. '
        "It must be absent before the student modifies the file."
    )


def test_setup_log_absent():
    """
    The verification log /home/user/db_admin/setup.log must NOT exist yet.
    """
    assert not SETUP_LOG.exists(), (
        f"Precondition failed: '{SETUP_LOG}' already exists. "
        "The exercise expects this file to be generated by the student."
    )