# test_initial_state.py
#
# Pytest suite that validates the *initial* operating-system / filesystem
# state *before* the student’s solution runs.

import os
from pathlib import Path

import pytest

HOME = Path("/home/user")
TARGETS_CSV = HOME / "data" / "targets.csv"
OUTPUT_DIR = HOME / "output"
LOGS_DIR = HOME / "logs"
SUMMARY_CSV = OUTPUT_DIR / "diagnostics_summary.csv"
DIAGNOSTICS_LOG = LOGS_DIR / "diagnostics.log"


@pytest.fixture(scope="module")
def targets_content():
    """
    Read the targets.csv content once for re-use.
    Raises with a clear message if the file is missing.
    """
    if not TARGETS_CSV.is_file():
        pytest.fail(
            f"Required file {TARGETS_CSV} is missing.\n"
            "Create the file with the exact name and location indicated."
        )
    try:
        content = TARGETS_CSV.read_text(encoding="ascii")
    except UnicodeDecodeError as exc:
        pytest.fail(
            f"File {TARGETS_CSV} must be pure ASCII text: {exc}"
        )
    return content


def test_targets_csv_exact_content(targets_content):
    """
    The initial state *must* contain /home/user/data/targets.csv with
    precisely the three lines (header + 2 data lines) specified in the
    task description, and the file must be newline-terminated.
    """
    expected = (
        "hostname,description\n"
        "127.0.0.1,local loopback\n"
        "192.0.2.1,test unreachable host\n"
    )
    assert targets_content == expected, (
        f"{TARGETS_CSV} has unexpected content.\n"
        "Expected exactly:\n"
        "------------------\n"
        f"{expected}"
        "------------------\n"
        "but got:\n"
        "------------------\n"
        f"{targets_content}"
        "------------------"
    )


@pytest.mark.parametrize("path_obj", [OUTPUT_DIR, LOGS_DIR])
def test_output_and_logs_directories_do_not_exist_yet(path_obj):
    """
    Before the student’s script runs, /home/user/output and /home/user/logs
    should *not* exist.  They will be created by the solution itself.
    """
    assert not path_obj.exists(), (
        f"Directory {path_obj} already exists, but it should be created "
        "by the student script, not present in the initial state."
    )


@pytest.mark.parametrize("path_obj", [SUMMARY_CSV, DIAGNOSTICS_LOG])
def test_result_files_do_not_exist_yet(path_obj):
    """
    Result files must not exist in the initial state.
    """
    assert not path_obj.exists(), (
        f"File {path_obj} already exists, but it must be generated by the "
        "student script during execution."
    )