# test_initial_state.py
#
# This pytest suite asserts the *initial* filesystem state that must be
# present before the student runs any commands.  It also checks that none
# of the paths the student is expected to create already exist.

import os
import stat
import pytest

HOME = "/home/user"
SRC_ROOT = os.path.join(HOME, "data_source")
BACKUP_ROOT = os.path.join(HOME, "backup_archive")
BACKUP_RUN_DIR = os.path.join(BACKUP_ROOT, "20240630_full")
BACKUP_LOG = os.path.join(BACKUP_RUN_DIR, "backup_log.txt")

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _assert_is_regular_file(path: str):
    """
    Assert that path exists and is a regular **non-symlink** file.
    """
    assert os.path.exists(path), f"Expected file '{path}' is missing."
    assert not os.path.islink(path), f"'{path}' should be a regular file, but it is a symlink."
    st = os.stat(path, follow_symlinks=False)
    assert stat.S_ISREG(st.st_mode), f"'{path}' exists but is not a regular file."


def _read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8") as fp:
        return fp.read()


# ---------------------------------------------------------------------------
# 1. Verify the source tree exists and matches expected contents
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "rel_dir",
    ["docs", "media", "configs"],
)
def test_source_subdirs_exist(rel_dir):
    abs_dir = os.path.join(SRC_ROOT, rel_dir)
    assert os.path.isdir(abs_dir), f"Source directory '{abs_dir}' is missing or not a directory."
    assert not os.path.islink(abs_dir), f"Source directory '{abs_dir}' should be a real directory, not a symlink."


@pytest.mark.parametrize(
    "rel_path, expected_content",
    [
        ("docs/readme.txt", "Project Documentation v1.0\n"),
        ("docs/guide.md", "# User Guide\n"),
        ("media/photo1.jpg", "fakejpgdata1\n"),
        ("media/photo2.png", "fakepngdata2\n"),
        ("configs/app.conf", "port=8080\n"),
    ],
)
def test_source_files_exist_and_content(rel_path, expected_content):
    abs_path = os.path.join(SRC_ROOT, rel_path)
    _assert_is_regular_file(abs_path)
    # Only compare contents for non-binary (text) files.
    if rel_path.endswith((".txt", ".md", ".conf")):
        actual = _read_file(abs_path)
        assert (
            actual == expected_content
        ), f"Content mismatch in '{abs_path}'. Expected: {expected_content!r}, found: {actual!r}"


# ---------------------------------------------------------------------------
# 2. Ensure that *no* backup directories or files are present yet
# ---------------------------------------------------------------------------

def test_backup_root_absent_or_empty():
    """
    The dedicated backup directory for the run (20240630_full) must not
    exist yet.  The top-level backup root may or may not exist; we only
    insist that the run-specific directory is absent.
    """
    if os.path.exists(BACKUP_ROOT) and os.path.islink(BACKUP_ROOT):
        pytest.fail(f"'{BACKUP_ROOT}' exists but is a symlink—expected a directory or nothing.")

    assert not os.path.exists(
        BACKUP_RUN_DIR
    ), f"Backup directory '{BACKUP_RUN_DIR}' already exists; it should be created by the student's solution."

def test_log_file_absent():
    """The log file must not pre-exist."""
    assert not os.path.exists(
        BACKUP_LOG
    ), f"Log file '{BACKUP_LOG}' already exists; it should be generated by the student's solution."