# test_initial_state.py
#
# Pytest suite that verifies the **initial** state of the operating system
# before the student has created any workflow artefacts.  The tests confirm
# that none of the required files, directories or processes already exist.
#
# If any of these tests fail it means the sandbox is *not* in the expected
# pristine condition and could give the student an unfair advantage.

import os
import subprocess
from pathlib import Path

WORKFLOWS_DIR = Path("/home/user/workflows")
SCRIPT_FILE = WORKFLOWS_DIR / "workflow.sh"
PID_FILE = WORKFLOWS_DIR / "pids.txt"
STATUS_LOG = WORKFLOWS_DIR / "workflow_status.log"

# --------------------------------------------------------------------------- #
# Helper utilities
# --------------------------------------------------------------------------- #

def _all_process_cmdlines():
    """
    Return a list with the command line (string) of every running process
    belonging to the current user.  Uses only the Python stdlib.
    """
    result = subprocess.run(
        ["ps", "-eo", "pid,cmd", "--no-headers"],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    # Return list of cmd strings (strip the leading PID and whitespace)
    cmdlines = []
    for line in result.stdout.splitlines():
        # Each line: "<pid> <cmdline...>"
        parts = line.strip().split(maxsplit=1)
        if len(parts) == 2:
            cmdlines.append(parts[1])
    return cmdlines


# --------------------------------------------------------------------------- #
# Tests for absence of files and directories
# --------------------------------------------------------------------------- #

def test_workflows_directory_absent():
    assert not WORKFLOWS_DIR.exists(), (
        f"The directory {WORKFLOWS_DIR} already exists. "
        "The sandbox should start without the workflow directory present."
    )


def test_script_file_absent():
    assert not SCRIPT_FILE.exists(), (
        f"The script {SCRIPT_FILE} already exists. "
        "It must be created by the student's solution."
    )


def test_pid_file_absent():
    assert not PID_FILE.exists(), (
        f"The PID file {PID_FILE} already exists. "
        "It must be generated by the student's script."
    )


def test_status_log_absent():
    assert not STATUS_LOG.exists(), (
        f"The status log {STATUS_LOG} already exists. "
        "It must be generated by the student's script."
    )


# --------------------------------------------------------------------------- #
# Tests for absence of running processes
# --------------------------------------------------------------------------- #

def test_no_simple_http_process_running():
    cmdlines = _all_process_cmdlines()
    offending = [
        c for c in cmdlines if "python3 -m http.server 8090" in c
    ]
    assert not offending, (
        "A process for the simple_http server "
        "'python3 -m http.server 8090' is already running:\n"
        + "\n".join(offending)
    )


def test_no_data_generator_process_running():
    cmdlines = _all_process_cmdlines()
    offending = [c for c in cmdlines if c.strip().startswith("yes workflow_running")]
    assert not offending, (
        "A data_generator process 'yes workflow_running' is already running:\n"
        + "\n".join(offending)
    )