# test_initial_state.py
#
# This test-suite validates the *starting* filesystem state that must be present
# **before** the learner performs any action for the “symlink migration” task.
#
# It deliberately DOES NOT test for the archive directory, the symlinks, nor the
# report file that will be produced later; those belong to the *post-task* state.
#
# Only Python’s stdlib and pytest are used.

import os
import pytest
from pathlib import Path

HOME = Path("/home/user")


@pytest.fixture(scope="module")
def expected_structure():
    """
    Returns a mapping of application names to the files that must exist in their
    respective logs directories together with the exact file contents that the
    exercise description guarantees.
    """
    return {
        "app1": {
            "access.log": "app1 access log stub\n",
            "error.log": "app1 error log stub\n",
        },
        "app2": {
            "2024-06-01.log": "2024-06-01 stub log\n",
            "2024-06-02.log": "2024-06-02 stub log\n",
        },
        "app3": {
            "runtime.log": "runtime stub log\n",
        },
    }


@pytest.mark.parametrize("app_name", ["app1", "app2", "app3"])
def test_logs_directory_exists_and_is_not_symlink(app_name):
    """
    Each /home/user/<app>/logs directory must exist and be a *real* directory,
    not a symlink, because the migration has not yet taken place.
    """
    logs_dir = HOME / app_name / "logs"
    assert logs_dir.exists(), f"Expected directory {logs_dir} to exist."
    assert logs_dir.is_dir(), f"{logs_dir} exists but is not a directory."
    assert not os.path.islink(logs_dir), (
        f"{logs_dir} should be a regular directory before migration, "
        "but it is already a symlink."
    )


def test_expected_log_files_and_contents(expected_structure):
    """
    Confirm that the stub log files exist **inside** the logs directories and
    that their contents match the specification.  This guarantees the grading
    environment is set up correctly before any student modification happens.
    """
    for app_name, files in expected_structure.items():
        for filename, expected_content in files.items():
            file_path = HOME / app_name / "logs" / filename
            assert file_path.exists(), f"Missing file: {file_path}"
            assert file_path.is_file(), f"{file_path} exists but is not a file."
            with file_path.open("r", encoding="utf-8") as fh:
                actual = fh.read()
            assert (
                actual == expected_content
            ), f"File {file_path} has unexpected content.\nExpected: {expected_content!r}\nActual:   {actual!r}"


def test_archive_directory_does_not_exist_yet():
    """
    The archive directory must *not* exist before the student runs their
    solution.  Its existence would indicate that the environment is already in
    the post-migration state, invalidating the exercise.
    """
    archive_dir = HOME / "archive"
    assert not archive_dir.exists(), (
        f"Directory {archive_dir} already exists, but it should be created by "
        "the student during the task."
    )


def test_symlink_migration_directory_and_report_absent():
    """
    Neither the report directory nor the report file should be present at the
    start of the exercise.
    """
    report_dir = HOME / "symlink_migration"
    report_file = report_dir / "report.tsv"

    assert not report_dir.exists(), (
        f"Directory {report_dir} already exists, but it must be created by "
        "the student during the task."
    )
    # If for some reason the directory exists but the file does not, still fail:
    assert not report_file.exists(), (
        f"File {report_file} already exists, but it must be generated by the "
        "student during the task."
    )