# test_initial_state.py
#
# This test-suite validates the *initial* filesystem state
# BEFORE the student performs any actions.
#
# What we expect right now:
# 1. The raw cost report is present at /home/user/cost_report_june_2023.csv
#    and its bytes match the canonical contents supplied in the task text.
# 2. Nothing related to the final destination
#    (/home/user/finops/june2023, cloud_costs.csv, README.txt) exists yet.
#
# If any of these assertions fail it means the environment is not in the
# pristine state that the exercise assumes.

import os
from pathlib import Path

import pytest


ORIGINAL_FILE = Path("/home/user/cost_report_june_2023.csv")
TARGET_DIR = Path("/home/user/finops/june2023")
RENAMED_FILE = TARGET_DIR / "cloud_costs.csv"
README_FILE = TARGET_DIR / "README.txt"

# The exact, canonical content for the cost report file.
EXPECTED_COST_REPORT_BYTES = (
    b"Service,Resource,Cost\n"
    b"EC2,i-1234567890abcdef0,123.45\n"
    b"S3,my-bucket,10.00\n"
)


def test_original_file_exists_and_is_correct():
    """The raw cost report must be present and byte-for-byte correct."""
    assert ORIGINAL_FILE.exists(), (
        f"Expected '{ORIGINAL_FILE}' to exist before the student starts, "
        "but it is missing."
    )
    assert ORIGINAL_FILE.is_file(), (
        f"'{ORIGINAL_FILE}' exists but is not a regular file."
    )

    actual_bytes = ORIGINAL_FILE.read_bytes()
    assert actual_bytes == EXPECTED_COST_REPORT_BYTES, (
        f"The contents of '{ORIGINAL_FILE}' do not match the expected "
        "canonical cost report."
    )


def test_target_directory_does_not_yet_exist():
    """
    The directory /home/user/finops/june2023 (and thus its contents) should
    not pre-exist.  A pre-existing directory would invalidate the exercise.
    """
    assert not TARGET_DIR.exists(), (
        f"Directory '{TARGET_DIR}' already exists. "
        "The initial state should NOT contain this directory."
    )


def test_no_renamed_file_or_readme_yet():
    """Ensure that neither the renamed CSV nor the README are present."""
    assert not RENAMED_FILE.exists(), (
        f"File '{RENAMED_FILE}' already exists. "
        "The student has nothing to move/rename."
    )
    assert not README_FILE.exists(), (
        f"File '{README_FILE}' already exists. "
        "The README must be generated by the student."
    )