# test_initial_state.py
#
# Pytest suite that validates the *initial* operating-system / filesystem
# state before the student starts implementing the ETL pipeline.
#
# DO NOT EDIT THIS FILE.
#
# The tests deliberately fail if anything that belongs to the *result* of
# the ETL job already exists, or if any of the four raw CSV files are
# missing or modified.

import os
from pathlib import Path

RAW_DIR = Path("/home/user/data/raw")
STAGING_DIR = Path("/home/user/data/staging")
OUTPUT_DIR = Path("/home/user/data/output")
LOGS_DIR = Path("/home/user/logs")

RAW_FILES_EXPECTED = {
    RAW_DIR / "sales_q1_2020.csv": (
        "Region,Country,SalesPerson,Product,Units,UnitPrice\n"
        "EMEA,Germany,Anna Schmidt,Widget A,120,25.50\n"
        "APAC,Japan,Kenji Ito,Widget B,85,30.00\n"
    ),
    RAW_DIR / "sales_q2_2020.csv": (
        "Region,Country,SalesPerson,Product,Units,UnitPrice\n"
        "EMEA,France,Jean Dupont,Widget A,95,25.50\n"
        "AMER,USA,Maria Garcia,Widget C,150,45.00\n"
    ),
    RAW_DIR / "sales_q3_2020.csv": (
        "Region,Country,SalesPerson,Product,Units,UnitPrice\n"
        "APAC,Australia,Liam Brown,Widget B,130,30.00\n"
        "AMER,Canada,Noah Wilson,Widget A,110,25.50\n"
    ),
    RAW_DIR / "sales_q4_2020.csv": (
        "Region,Country,SalesPerson,Product,Units,UnitPrice\n"
        "EMEA,Italy,Luca Rossi,Widget C,140,45.00\n"
        "APAC,China,Wei Zhang,Widget A,200,25.50\n"
    ),
}

RESULT_FILES = [
    STAGING_DIR / "all_sales_2020_enriched.csv",
    OUTPUT_DIR / "quarterly_sales_2020_summary.csv",
    LOGS_DIR / "etl_2020.log",
]


def _read_file_text(path: Path) -> str:
    """Read a file as UTF-8 text, return empty string if not found."""
    try:
        with path.open("r", encoding="utf-8") as fh:
            return fh.read()
    except FileNotFoundError:
        return ""


def test_raw_files_exist_with_expected_content():
    """
    The four raw CSV files must exist *exactly* as provided in the spec.
    A mismatch indicates the student (or a prior run) has modified them.
    """
    for path, expected in RAW_FILES_EXPECTED.items():
        assert path.exists(), f"Missing raw input file: {path}"
        assert path.is_file(), f"Expected a regular file: {path}"
        actual = _read_file_text(path)
        assert (
            actual == expected
        ), f"File {path} differs from expected initial content."


def test_no_output_directories_exist_yet():
    """
    At the starting point the staging, output and logs directories
    should not exist.  If they do, the student ran (part of) the ETL
    pipeline too early.
    """
    for directory in (STAGING_DIR, OUTPUT_DIR, LOGS_DIR):
        assert not directory.exists(), (
            f"Directory {directory} already exists but must be created "
            f"by the student's ETL script."
        )


def test_no_result_files_exist_yet():
    """
    None of the files that belong to the *output* of the ETL job may
    exist at this point.
    """
    for path in RESULT_FILES:
        assert not path.exists(), (
            f"Output file {path} already exists — the ETL job "
            f"must generate it, not the initial state."
        )