# test_initial_state.py
#
# Pytest suite that verifies the initial OS / filesystem state
# BEFORE the student’s backup-creation script is executed.
#
# What is checked:
#   • The three source data directories exist with the exact files
#     and file contents described in the task text.
#   • None of the artefacts that the student must create are present
#     yet (archives directory, .tar.gz files, manifest, symlink,
#     read-me file).
#
# Only stdlib + pytest are used.

import os
import stat
import hashlib
import pytest
from pathlib import Path

HOME = Path("/home/user")

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def sha256_of_file(path: Path) -> str:
    """Return the lowercase hex SHA-256 of the given file."""
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()

# ---------------------------------------------------------------------------
# Paths / constants
# ---------------------------------------------------------------------------

DATA_DIRS = {
    "data_alpha": {
        "file1.txt": "alpha one\n",
        "file2.txt": "alpha two\n",
    },
    "data_bravo": {
        "file3.txt": "bravo three\n",
        "file4.txt": "bravo four\n",
    },
    "data_charlie": {
        "readme.md": "# Charlie Data\nSome content.\n",
    },
}

ARCHIVES_DIR = HOME / "archives"

ARCHIVE_FILENAMES = [
    "data_alpha_20231001.tar.gz",
    "data_bravo_20231001.tar.gz",
    "data_charlie_20231001.tar.gz",
]

MANIFEST_FILE = ARCHIVES_DIR / "backup_manifest_2023-10-01.log"
SYMLINK_LATEST = ARCHIVES_DIR / "latest_manifest.log"
README_FILE = ARCHIVES_DIR / "README_BACKUPS.txt"


# ---------------------------------------------------------------------------
# Tests that verify the pre-existing source data
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("dir_name, expected_files", DATA_DIRS.items())
def test_source_directories_and_files_exist(dir_name, expected_files):
    """
    Each /home/user/data_* directory must already exist and contain exactly the
    files and file contents specified in the task description.
    """
    dir_path = HOME / dir_name
    assert dir_path.is_dir(), f"Required directory {dir_path} is missing."

    actual_files = sorted(p.name for p in dir_path.iterdir() if p.is_file())
    expected_file_names = sorted(expected_files.keys())
    assert actual_files == expected_file_names, (
        f"Directory {dir_path} must contain exactly the files "
        f"{expected_file_names}, but it contains {actual_files}."
    )

    # Verify file contents verbatim
    for filename, expected_content in expected_files.items():
        file_path = dir_path / filename
        with file_path.open("r", encoding="utf-8") as fh:
            content = fh.read()
        assert content == expected_content, (
            f"File {file_path} has unexpected content.\n"
            f"Expected: {repr(expected_content)}\n"
            f"Found:    {repr(content)}"
        )


# ---------------------------------------------------------------------------
# Tests that verify nothing created by the student exists yet
# ---------------------------------------------------------------------------

def test_archives_directory_absent():
    """
    /home/user/archives/ must NOT exist before the student runs their script.
    """
    assert not ARCHIVES_DIR.exists(), (
        f"The directory {ARCHIVES_DIR} already exists, "
        "but it should be created by the student's solution."
    )


@pytest.mark.parametrize("filename", ARCHIVE_FILENAMES)
def test_archive_files_absent(filename):
    """
    Ensure that none of the required .tar.gz archives pre-exist.
    """
    archive_path = ARCHIVES_DIR / filename
    assert not archive_path.exists(), (
        f"Archive file {archive_path} already exists; "
        "it should be produced by the student's solution."
    )


def test_manifest_and_symlink_absent():
    """
    Neither the manifest file nor the symlink must be present yet.
    """
    assert not MANIFEST_FILE.exists(), (
        f"The manifest file {MANIFEST_FILE} already exists; "
        "it should be generated by the student's solution."
    )
    assert not SYMLINK_LATEST.exists(), (
        f"The symlink {SYMLINK_LATEST} already exists; "
        "it should be created by the student's solution."
    )


def test_readme_absent():
    """
    README_BACKUPS.txt must not be present before execution.
    """
    assert not README_FILE.exists(), (
        f"The README file {README_FILE} already exists; "
        "it should be created by the student's solution."
    )