# test_initial_state.py
#
# This test-suite validates the initial state of the operating system
# before the student performs any action.  It checks that the resolver
# configuration file the instructions refer to is present and contains
# exactly the expected content.  We intentionally do NOT test for the
# presence of the output file (`primary_dns.log`) because it should be
# created by the student.

import pathlib
import textwrap
import pytest

HOME_DIR = pathlib.Path("/home/user")
OBSERVABILITY_DIR = HOME_DIR / "observability"
RESOLV_FILE = OBSERVABILITY_DIR / "node.resolv"


def test_observability_directory_exists():
    """Ensure /home/user/observability exists and is a directory."""
    assert OBSERVABILITY_DIR.exists(), (
        "Missing directory: /home/user/observability\n"
        "The directory that should contain the resolver configuration "
        "file is not present."
    )
    assert OBSERVABILITY_DIR.is_dir(), (
        "/home/user/observability exists but is not a directory."
    )


def test_resolv_file_exists_and_is_file():
    """Ensure /home/user/observability/node.resolv exists and is a regular file."""
    assert RESOLV_FILE.exists(), (
        "Missing file: /home/user/observability/node.resolv\n"
        "The resolver configuration file referenced in the task description "
        "must already be present."
    )
    assert RESOLV_FILE.is_file(), (
        "/home/user/observability/node.resolv exists but is not a regular file."
    )


def test_resolv_file_content_is_exact():
    """
    Verify that the resolver file's contents match the expected text
    exactly (including newlines, spacing, and order).
    """
    expected_content = textwrap.dedent(
        """\
        # Generated by NetworkManager
        search corp.local
        nameserver 10.98.0.2
        nameserver 10.98.0.3
        options timeout:1 attempts:3
        """
    )
    actual_content = RESOLV_FILE.read_text()

    # Provide a diff-friendly message on mismatch
    assert actual_content == expected_content, (
        "The contents of /home/user/observability/node.resolv do not match the "
        "expected initial resolver configuration.\n\n"
        "Expected:\n"
        f"{expected_content!r}\n\n"
        "Actual:\n"
        f"{actual_content!r}\n"
        "Please ensure the file has not been modified."
    )