# test_initial_state.py
#
# Pytest suite that validates the INITIAL, pre-task condition of the
# operating-system filesystem for the “backup permissions” exercise.
#
# This file must be executed BEFORE the student runs any command that
# changes permissions or creates log files.  It therefore checks ONLY
# the initial resources that already exist when the task begins and
# deliberately avoids looking for any artefacts that are supposed to be
# generated by the student (e.g. /home/user/backup_fix.log).

import os
import stat
import pytest

# Constants for full absolute paths
BACKUP_DIR = "/home/user/db_backups"
BACKUP_FILE = "/home/user/db_backups/production.db"

# Expected octal (base-10) permission integers
EXPECTED_DIR_PERMS = 0o777   # rwxrwxrwx
EXPECTED_FILE_PERMS = 0o664  # rw-rw-r--

def _get_octal_mode(path):
    """
    Return the numeric (e.g., 0o755) permission bits for `path`.
    Only the lowest 12 bits (permission + sticky/SUID/SGID) are considered.
    """
    return stat.S_IMODE(os.stat(path).st_mode)


@pytest.mark.describe("Initial filesystem state for backup directory")
def test_backup_directory_exists_and_permissions():
    # 1. Directory must exist
    assert os.path.isdir(BACKUP_DIR), (
        f"Required directory {BACKUP_DIR!r} is missing. "
        "It must exist BEFORE the student begins the task."
    )

    # 2. Permissions must match the insecure starting state (777)
    actual_perms = _get_octal_mode(BACKUP_DIR)
    assert actual_perms == EXPECTED_DIR_PERMS, (
        f"Directory {BACKUP_DIR} has permissions {oct(actual_perms)[2:]}; "
        f"expected initial permissions {oct(EXPECTED_DIR_PERMS)[2:]}."
    )


@pytest.mark.describe("Initial filesystem state for backup file")
def test_backup_file_exists_and_permissions():
    # 1. File must exist
    assert os.path.isfile(BACKUP_FILE), (
        f"Required file {BACKUP_FILE!r} is missing. "
        "It must exist BEFORE the student begins the task."
    )

    # 2. Permissions must match the insecure starting state (664)
    actual_perms = _get_octal_mode(BACKUP_FILE)
    assert actual_perms == EXPECTED_FILE_PERMS, (
        f"File {BACKUP_FILE} has permissions {oct(actual_perms)[2:]}; "
        f"expected initial permissions {oct(EXPECTED_FILE_PERMS)[2:]}."
    )