# test_initial_state.py
#
# This pytest suite validates the *initial* filesystem state **before**
# the student performs any action.  According to the task description,
# no firewall-configuration artefacts should exist yet.
#
# What we check:
#   1. The directory /home/user/firewall_config must NOT exist.
#   2. Consequently, the files rules.conf and rules.log must also be absent.
#
# Any failure means the environment is already “contaminated” and does not
# match the expected clean slate.

import pathlib

FIREWALL_DIR = pathlib.Path("/home/user/firewall_config")
RULES_CONF   = FIREWALL_DIR / "rules.conf"
RULES_LOG    = FIREWALL_DIR / "rules.log"


def test_firewall_directory_absent():
    """
    The directory /home/user/firewall_config should not exist at the start
    of the task.  Its presence would indicate that somebody already created
    it, violating the expected initial state.
    """
    assert not FIREWALL_DIR.exists(), (
        f"The directory {FIREWALL_DIR} should NOT exist before the exercise begins. "
        "Remove it so the student can create it as part of the task."
    )


def test_rules_conf_absent():
    """
    The file rules.conf must be absent initially.  It will be created by the
    student during the task.
    """
    assert not RULES_CONF.exists(), (
        f"The file {RULES_CONF} should NOT exist before the exercise begins."
    )


def test_rules_log_absent():
    """
    The file rules.log must be absent initially.  It will be generated by the
    student during the task.
    """
    assert not RULES_LOG.exists(), (
        f"The file {RULES_LOG} should NOT exist before the exercise begins."
    )