# test_initial_state.py
#
# Pytest suite that verifies the required initial operating-system / file-system
# state **before** the student performs any action for the “INI audit” task.
#
# Only standard-library modules and pytest are used.

import os
from pathlib import Path
import configparser
import pytest

# ---------------------------------------------------------------------------
# CONSTANTS – paths and the expected key/value pairs in each INI file
# ---------------------------------------------------------------------------

CONFIG_DIR = Path("/home/user/configs")
INI_FILES = {
    Path("/home/user/configs/app1.ini"): {
        "ComplianceLevel": "PCI-DSS",
        "Encryption": "AES256",
        "Version": "2.0",
    },
    Path("/home/user/configs/app2.ini"): {
        "ComplianceLevel": "HIPAA",
        "Encryption": "AES128",
        "Version": "1.4",
    },
}

AUDIT_DIR = Path("/home/user/audit")
AUDIT_LOG = AUDIT_DIR / "audit_report.log"


# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

def read_ini(path: Path) -> configparser.ConfigParser:
    """
    Read an INI file and return a ConfigParser object.

    The parser is created with strict=True so duplicate keys are caught
    immediately.
    """
    parser = configparser.ConfigParser(strict=True)
    with path.open("r", encoding="utf-8") as fp:
        parser.read_file(fp)
    return parser


# ---------------------------------------------------------------------------
# TESTS
# ---------------------------------------------------------------------------

def test_configs_directory_exists():
    """/home/user/configs must exist and be a directory."""
    assert CONFIG_DIR.exists(), (
        f"Required directory {CONFIG_DIR} is missing. "
        "The two INI files must be located here."
    )
    assert CONFIG_DIR.is_dir(), f"{CONFIG_DIR} exists but is not a directory."


@pytest.mark.parametrize("ini_path", INI_FILES.keys())
def test_ini_files_exist_and_are_regular_files(ini_path: Path):
    """Ensure each required INI file exists and is a regular file."""
    assert ini_path.exists(), f"Required INI file {ini_path} is missing."
    assert ini_path.is_file(), f"{ini_path} exists but is not a regular file."


@pytest.mark.parametrize("ini_path, expected_kvs", INI_FILES.items())
def test_general_section_key_values(ini_path: Path, expected_kvs: dict):
    """
    The [General] section of each INI file must contain the three mandatory
    keys with the exact expected values *before* the student starts.
    """
    parser = read_ini(ini_path)

    # Section presence
    assert parser.has_section("General"), (
        f"{ini_path} is missing the [General] section."
    )

    # Key/value correctness
    missing_keys = []
    wrong_values = []
    for key, expected_value in expected_kvs.items():
        if not parser.has_option("General", key):
            missing_keys.append(key)
            continue

        actual_value = parser.get("General", key, raw=True)
        if actual_value != expected_value:
            wrong_values.append((key, expected_value, actual_value))

    # Construct helpful assertion messages
    msgs = []
    if missing_keys:
        msgs.append(
            f"Missing keys in [General]: {', '.join(missing_keys)}."
        )
    if wrong_values:
        msgs.extend(
            f"Key '{k}' has value '{actual}', expected '{exp}'."
            for k, exp, actual in wrong_values
        )

    assert not (missing_keys or wrong_values), (
        f"{ini_path} does not meet the required initial state:\n" +
        "\n".join(msgs)
    )


def test_audit_directory_and_log_absent():
    """
    The compliance-generation step has not run yet, so neither the audit
    directory nor audit_report.log should exist.
    """
    assert not AUDIT_DIR.exists(), (
        f"{AUDIT_DIR} already exists, but it should be created by the student "
        "solution, not be present beforehand."
    )
    # If, for some reason, the directory exists already, at the very least
    # the audit_report.log must not be present.
    if AUDIT_DIR.exists():
        assert not AUDIT_LOG.exists(), (
            f"{AUDIT_LOG} is already present; it must be generated by the "
            "student after processing the INI files."
        )