# test_initial_state.py
"""
Pytest suite that validates the **initial** state of the OS / filesystem
BEFORE the student enables HTTPS for the local-only Grafana instance.

It asserts that none of the artefacts the student is supposed to create
already exist, and that the Grafana configuration has not yet been
modified with the required `[server]` HTTPS block.

Only the Python standard library and pytest are used.
"""

import os
import textwrap
import pytest

HOME = "/home/user"
OBS_ROOT = os.path.join(HOME, "observability")
CERTS_DIR = os.path.join(OBS_ROOT, "certs")

CERT_FILE = os.path.join(CERTS_DIR, "grafana-dashboard.local.crt")
KEY_FILE = os.path.join(CERTS_DIR, "grafana-dashboard.local.key")
JSON_FILE = os.path.join(CERTS_DIR, "cert_info.json")
RENEWAL_LOG = os.path.join(CERTS_DIR, "renewal.log")

GRAFANA_INI = os.path.join(OBS_ROOT, "grafana.ini")

# The exact 4-line HTTPS block that must NOT yet exist
EXPECTED_SERVER_BLOCK = textwrap.dedent("""\
    [server]
    protocol = https
    cert_file = /home/user/observability/certs/grafana-dashboard.local.crt
    cert_key = /home/user/observability/certs/grafana-dashboard.local.key
""").splitlines(keepends=True)  # -> list including '\n'


@pytest.fixture(scope="module")
def grafana_ini_contents():
    """
    Read grafana.ini once for all tests that need it. Skip the test if the
    file does not exist; the exercise specification requires its presence
    before the student starts.
    """
    if not os.path.isfile(GRAFANA_INI):
        pytest.skip(f"Expected Grafana config at {GRAFANA_INI!s} is missing; "
                    f"the exercise requires it to exist before the student starts.")
    with open(GRAFANA_INI, "r", encoding="utf-8", errors="ignore") as fh:
        return fh.readlines()


def test_observability_base_directory_exists():
    assert os.path.isdir(OBS_ROOT), (
        f"Expected base directory {OBS_ROOT} to exist before the exercise starts."
    )


def test_certs_directory_absent_initially():
    assert not os.path.exists(CERTS_DIR), (
        f"The directory {CERTS_DIR} should NOT exist before the student begins; "
        "it must be created by the student."
    )


@pytest.mark.parametrize("path_description, path",
                         [
                             ("certificate file", CERT_FILE),
                             ("private key file", KEY_FILE),
                             ("certificate-metadata JSON file", JSON_FILE),
                             ("renewal log file", RENEWAL_LOG),
                         ])
def test_expected_files_absent_initially(path_description, path):
    assert not os.path.exists(path), (
        f"The {path_description} ({path}) should NOT exist yet; "
        "it will be generated by the student."
    )


def test_grafana_ini_does_not_yet_contain_required_https_block(grafana_ini_contents):
    """
    Ensure the exact 4-line block required by the specification is NOT
    already present in grafana.ini.
    """
    content_lines = grafana_ini_contents

    # Iterate over the ini lines and look for the 4-line sequence.
    # We store indexes where the first line matches and then verify the block.
    for i, line in enumerate(content_lines):
        if line == EXPECTED_SERVER_BLOCK[0]:  # potential start of the block
            block = content_lines[i:i + 4]
            if block == EXPECTED_SERVER_BLOCK:
                pytest.fail(
                    "The Grafana configuration already contains the required "
                    "HTTPS [server] block; it should be absent initially so "
                    "that the student can add it."
                )
    # If we finish the loop without failure, the block is not present.