# test_initial_state.py
"""
Pytest suite that verifies the operating-system / filesystem state
BEFORE the student performs any actions for the “Kubernetes Operator
documentation” exercise.

This file must be executed prior to the student’s work; if it fails,
the environment is not in the expected clean starting state.
"""
import os
from pathlib import Path

import pytest

HOME = Path("/home/user").expanduser().resolve()
OPERATOR_MANIFESTS_DIR = HOME / "operator-manifests"
OPERATOR_DOCS_DIR = HOME / "operator-docs"


@pytest.fixture(scope="module")
def deployment_yaml_expected():
    return (
        "---\n"
        "apiVersion: apps/v1\n"
        "kind: Deployment\n"
        "metadata:\n"
        "  name: sample-deployment\n"
        "  namespace: default\n"
    )


@pytest.fixture(scope="module")
def service_yaml_expected():
    return (
        "---\n"
        "apiVersion: v1\n"
        "kind: Service\n"
        "metadata:\n"
        "  name: sample-service\n"
        "  namespace: default\n"
    )


def test_operator_manifests_directory_exists():
    assert OPERATOR_MANIFESTS_DIR.is_dir(), (
        f"Required directory {OPERATOR_MANIFESTS_DIR} is missing or is "
        f"not a directory."
    )


def test_operator_manifests_contains_only_expected_files():
    expected_files = {"deployment.yaml", "service.yaml"}
    actual_files = {p.name for p in OPERATOR_MANIFESTS_DIR.iterdir() if p.is_file()}
    missing = expected_files - actual_files
    extra = actual_files - expected_files
    assert not missing, (
        f"The following required file(s) are missing from "
        f"{OPERATOR_MANIFESTS_DIR}: {', '.join(sorted(missing))}"
    )
    assert not extra, (
        f"Unexpected file(s) found in {OPERATOR_MANIFESTS_DIR}: "
        f"{', '.join(sorted(extra))}. The directory must contain "
        f"EXACTLY the two expected YAML files."
    )


@pytest.mark.parametrize(
    "filename,expected_fixture",
    [
        ("deployment.yaml", "deployment_yaml_expected"),
        ("service.yaml", "service_yaml_expected"),
    ],
)
def test_manifest_file_contents(filename, expected_fixture, request):
    expected_content = request.getfixturevalue(expected_fixture)
    file_path = OPERATOR_MANIFESTS_DIR / filename
    assert file_path.is_file(), f"Expected file {file_path} is missing."

    actual_content = file_path.read_text(encoding="utf-8")
    assert (
        actual_content == expected_content
    ), f"Content of {file_path} does not match the expected initial content."


def test_operator_docs_directory_absent_initially():
    assert not OPERATOR_DOCS_DIR.exists(), (
        f"The directory {OPERATOR_DOCS_DIR} should NOT exist before the "
        f"student starts the task."
    )


def test_other_expected_files_absent_initially():
    """
    Ensure that artefacts to be generated by the student do NOT
    already exist.
    """
    artefacts = [
        HOME / ".markdownlint.yaml",
        OPERATOR_DOCS_DIR / "operator-manifests.md",
        OPERATOR_DOCS_DIR / "lint_report.log",
    ]
    for path in artefacts:
        assert not path.exists(), (
            f"The file {path} should NOT exist before the student begins "
            f"the exercise."
        )