# test_initial_state.py
#
# This pytest suite validates that the container starts in a **clean**
# state before the student attempts the exercise described in the task.
#
# It intentionally asserts that none of the required artefacts – files,
# directories, processes, or open TCP ports – are already present.  A
# failure here means the environment was pre-populated or the student
# has already executed (part of) the solution before the automated
# grader ran.
#
# Only Python’s standard library and pytest are used, in accordance with
# the platform rules.

import os
import socket
import subprocess
import sys
from pathlib import Path

import pytest

# Constant paths used in the exercise
WEBROOT_DIR = Path("/home/user/microservices/webroot")
INDEX_HTML = WEBROOT_DIR / "index.html"
OUTPUT_LOG = Path("/home/user/output/webserver_response.log")
PORT = 8080


def _system_ps_output():
    """
    Return the full `ps -eo pid,args` output as a list of lines (stripped).
    Using `ps` avoids non-stdlib packages like psutil.
    """
    result = subprocess.run(
        ["ps", "-eo", "pid,args"],
        check=True,
        capture_output=True,
        text=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


@pytest.mark.describe("Initial filesystem state")
class TestFileSystemState:
    def test_webroot_directory_absent(self):
        """The /home/user/microservices/webroot directory must NOT yet exist."""
        assert not WEBROOT_DIR.exists(), (
            f"The directory {WEBROOT_DIR} already exists. "
            "The environment should start clean."
        )

    def test_index_html_absent(self):
        """The index.html file must NOT yet exist."""
        assert not INDEX_HTML.exists(), (
            f"The file {INDEX_HTML} already exists. "
            "It should be created by the student's solution."
        )

    def test_output_log_absent(self):
        """The output log file must NOT yet exist."""
        assert not OUTPUT_LOG.exists(), (
            f"The file {OUTPUT_LOG} already exists. "
            "It should be generated by the student's solution."
        )


@pytest.mark.describe("Initial process and networking state")
class TestProcessState:
    def test_http_server_process_absent(self):
        """
        No python -m http.server 8080 (or equivalent) process should be running.
        """
        offending_processes = []
        for line in _system_ps_output():
            if "http.server" in line and "8080" in line:
                offending_processes.append(line)

        assert not offending_processes, (
            "An HTTP server on port 8080 is already running:\n"
            + "\n".join(offending_processes)
            + "\nThe container should start without this."
        )

    def test_port_8080_not_listening(self):
        """
        TCP port 8080 must be closed (connection refused).
        A timeout or ECONNREFUSED is acceptable and expected.
        Any successful connection means somebody is already listening.
        """
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(1.0)

        try:
            # Try IPv4 localhost first.
            sock.connect(("127.0.0.1", PORT))
        except (ConnectionRefusedError, socket.timeout):
            # Expected path: nothing is listening
            return
        except OSError as exc:
            # Any other socket error (e.g., network unreachable) is also acceptable
            # because it proves nothing is listening.
            if exc.errno in {101, 111}:  # Network unreachable, connection refused
                return
            raise AssertionError(
                f"Unexpected OS error while probing port {PORT}: {exc}"
            ) from exc
        else:
            # If we get here the connect() call succeeded => port is open
            sock.close()
            pytest.fail(
                f"A process is already listening on TCP port {PORT}. "
                "The environment must be clean before the student runs their code."
            )
        finally:
            sock.close()