# test_initial_state.py
#
# This pytest module validates the system state *before* the student’s
# workspace script is executed.  The incident-response specification
# guarantees that *no* artefacts exist at the outset; the student must
# create them later.  If any artefacts already exist, the test fails and
# provides a precise, instructive error message.

import os
import stat
import pytest

HOME = "/home/user"
INCIDENT_DIR = os.path.join(HOME, "incident_logs")
LOG_FILE = os.path.join(INCIDENT_DIR, "package_triage.log")


@pytest.mark.parametrize(
    "path, should_exist",
    [
        (INCIDENT_DIR, False),
        (LOG_FILE, False),
    ],
)
def test_prerequisite_artefacts_absent(path, should_exist):
    """
    Ensure that the incident directory and the log file do *not* exist
    before the student performs the required actions.

    The incident triage workflow explicitly states that these artefacts
    must be generated by the student script.  Their presence beforehand
    would indicate either a polluted environment or that the student
    skipped essential steps.
    """
    exists = os.path.exists(path)
    assert exists is should_exist, (
        f"Pre-condition failure: '{path}' is "
        f"{'present' if exists else 'absent'} but should be "
        f"{'present' if should_exist else 'absent'}."
    )


def test_home_directory_permissions():
    """
    Sanity-check that /home/user exists and is a directory with at least
    user read/write/execute permissions; this ensures subsequent tasks
    can create artefacts underneath it.
    """
    assert os.path.isdir(HOME), (
        f"Expected home directory '{HOME}' to exist and be a directory."
    )

    st = os.stat(HOME)
    # Owner must have rwx; group/other are not important for this check.
    owner_perms = stat.S_IMODE(st.st_mode) & 0o700
    assert owner_perms == 0o700, (
        f"Home directory '{HOME}' should have owner rwx permissions "
        f"(0700). Current mode is {oct(stat.S_IMODE(st.st_mode))}."
    )