# test_initial_state.py
#
# This test-suite verifies the *initial* state of the operating system /
# file-system before the student has started to work on the assignment that
# formalises SQL optimisation.
#
# ONLY the scratch file  /home/user/db_queries/raw_queries.sql  is expected
# to exist right now; nothing else from the “expected final state” should be
# present yet.
#
# If any of these assertions fail the student is starting from an unexpected
# environment and subsequent grading will be unreliable.

import os
from pathlib import Path

import pytest

# --------------------------------------------------------------------------- #
# Constant reference paths                                                    #
# --------------------------------------------------------------------------- #

HOME = Path("/home/user")

# Virtual-environment directory that the student must create later
VENV_DIR = HOME / ".venvs" / "opt_queries"

# Directory with the database related files
DB_DIR = HOME / "db_queries"

# Paths that must already exist
RAW_QUERIES = DB_DIR / "raw_queries.sql"

# Paths that must *not* exist yet
BACKUP_RAW_QUERIES = DB_DIR / "raw_queries_backup.sql"
OPTIMIZE_SCRIPT = DB_DIR / "optimize_queries.py"
OPTIMIZED_QUERIES = DB_DIR / "optimized_queries.sql"
OPTIMIZATION_LOG = DB_DIR / "optimization.log"
REQUIREMENTS_TXT = VENV_DIR / "requirements.txt"

# --------------------------------------------------------------------------- #
# Helper                                                                      #
# --------------------------------------------------------------------------- #


def assert_not_exists(path: Path):
    """
    Assert that a file or directory does NOT exist, emitting a clear message.
    """
    assert not path.exists(), f"Path unexpectedly exists already: {path}"


# --------------------------------------------------------------------------- #
# Tests                                                                       #
# --------------------------------------------------------------------------- #


def test_raw_queries_file_exists_with_expected_content():
    """
    The raw SQL file supplied by a colleague must already be present and must
    contain the exact two ad-hoc SQL statements (case and spacing preserved).
    """
    assert RAW_QUERIES.is_file(), (
        f"Expected initial file is missing: {RAW_QUERIES}"
    )

    # Expected verbatim content (including the line-breaks shown below).
    expected_content = (
        "SELECT * from employees where salary>50000;\n"
        "select name, department from employees where department='Sales';\n"
    )

    with RAW_QUERIES.open("r", encoding="utf-8") as fh:
        actual = fh.read()

    # We allow a missing trailing newline only to avoid over-strict failures.
    assert actual.strip() == expected_content.strip(), (
        f"Content of {RAW_QUERIES} is not as expected.\n"
        f"--- expected (repr) ---\n{repr(expected_content)}\n"
        f"--- actual (repr) -----\n{repr(actual)}\n"
    )


def test_virtual_environment_does_not_yet_exist():
    """
    The dedicated user-local virtual environment must NOT exist before the
    student creates it.
    """
    assert_not_exists(VENV_DIR)


def test_no_requirements_file_yet():
    """
    requirements.txt should be generated by `pip freeze` later; it must not be
    present at the very beginning.
    """
    assert_not_exists(REQUIREMENTS_TXT)


def test_no_backup_file_yet():
    """
    The verbatim backup copy of the raw SQL must be created by the student,
    therefore it should not exist yet.
    """
    assert_not_exists(BACKUP_RAW_QUERIES)


def test_no_optimization_script_yet():
    """
    The optimisation script should not exist before the student writes it.
    """
    assert_not_exists(OPTIMIZE_SCRIPT)


def test_no_optimized_queries_file_yet():
    """
    The optimised SQL file must be produced by the optimisation script, so it
    must not exist in the initial state.
    """
    assert_not_exists(OPTIMIZED_QUERIES)


def test_no_optimization_log_yet():
    """
    The log file is generated only after a successful optimisation run; it
    should not be present beforehand.
    """
    assert_not_exists(OPTIMIZATION_LOG)