# test_initial_state.py
"""
Pytest suite that validates the *initial* OS / filesystem state for
the “endpoint-frequency” exercise *before* the student writes any
solution code.

It checks:

1. The raw log file exists at the expected absolute path and contains
   the exact 12 lines given in the specification (including order and
   trailing newlines).
2. The output directory (/home/user/migration/summary) must **not**
   exist yet.
3. Consequently, the target TSV report file must also not exist.

If any of these assertions fail, the error message will clearly tell
the student what is wrong with the starting environment.
"""

from pathlib import Path
import os
import pytest

# Constant paths
LOG_PATH = Path("/home/user/migration/service_endpoints.log")
SUMMARY_DIR = Path("/home/user/migration/summary")
SUMMARY_TSV = SUMMARY_DIR / "endpoint_frequency.tsv"

# Expected log contents (each line should end with '\n')
EXPECTED_LOG_LINES = [
    "api-us.example.com\n",
    "api-eu.example.com\n",
    "api-us.example.com\n",
    "api-us.example.com\n",
    "auth.example.com\n",
    "api-eu.example.com\n",
    "cdn.example.com\n",
    "auth.example.com\n",
    "auth.example.com\n",
    "cdn.example.com\n",
    "cdn.example.com\n",
    "cdn.example.com\n",
]


def test_log_file_exists_with_expected_content():
    """Ensure the raw log file exists and matches the exact expected content."""
    assert LOG_PATH.exists(), (
        f"Required log file not found: {LOG_PATH}. "
        "It should already be present with 12 lines."
    )
    assert LOG_PATH.is_file(), f"Expected {LOG_PATH} to be a file, but it's not."

    # Read file as bytes -> decode later to avoid newline translation issues
    with LOG_PATH.open("rb") as fp:
        contents = fp.readlines()

    # Decode assuming UTF-8 (safe for plain ASCII names)
    lines = [line.decode("utf-8") for line in contents]

    assert (
        lines == EXPECTED_LOG_LINES
    ), (
        f"{LOG_PATH} content does not match the required initial 12 lines.\n"
        "Expected:\n"
        + "".join(EXPECTED_LOG_LINES)
        + "\nActual:\n"
        + "".join(lines)
    )


def test_summary_directory_does_not_exist():
    """The summary directory must not exist before the student runs the solution."""
    assert not SUMMARY_DIR.exists(), (
        f"Directory {SUMMARY_DIR} should NOT exist at the start of the exercise. "
        "It will be created by the student's solution."
    )


def test_summary_tsv_does_not_exist():
    """The TSV report file must not pre-exist either."""
    assert not SUMMARY_TSV.exists(), (
        f"Output file {SUMMARY_TSV} must not exist yet. "
        "It should be generated by the student's pipeline."
    )