# test_initial_state.py
#
# This pytest suite validates the *initial* state of the operating system
# before the student starts working on the “network diagnostics” exercise.
# It deliberately checks that none of the artefacts the student is supposed
# to create (directories, script, log file) are present yet, so that the
# actual task can be graded unambiguously later on.

import os
from pathlib import Path

HOME = Path("/home/user")
SCRIPTS_DIR = HOME / "scripts"
LOGS_DIR = HOME / "logs"
SCRIPT_FILE = SCRIPTS_DIR / "network_diag.sh"
LOG_FILE = LOGS_DIR / "loopback_diagnostics.log"


def _fmt(p: Path) -> str:
    """Format a Path for clearer assertion messages."""
    return f"'{p.as_posix()}'"


def test_scripts_directory_absent_or_empty_of_target():
    """
    Verify that `/home/user/scripts` does not yet contain `network_diag.sh`.
    The directory may legitimately be absent altogether; either case is fine.
    """
    if not SCRIPTS_DIR.exists():
        # Directory absent is acceptable for initial state.
        assert True
    else:
        assert not SCRIPT_FILE.exists(), (
            f"{_fmt(SCRIPT_FILE)} already exists. "
            "The diagnostics script should be created by the student, "
            "not be present beforehand."
        )


def test_logs_directory_absent_or_logfile_missing():
    """
    Verify that `/home/user/logs/loopback_diagnostics.log` is not present yet.
    The parent directory may or may not exist at this stage.
    """
    if not LOGS_DIR.exists():
        assert True
    else:
        assert not LOG_FILE.exists(), (
            f"{_fmt(LOG_FILE)} already exists. "
            "The diagnostics log file must be generated by running the "
            "student's script, and should not be present before the task."
        )


def test_script_not_executable_yet():
    """
    If the script file is somehow present already, ensure it is *not*
    executable.  A premade executable would violate the clean-slate
    requirement for the assignment.
    """
    if SCRIPT_FILE.exists():
        is_exec = os.access(SCRIPT_FILE, os.X_OK)
        assert not is_exec, (
            f"{_fmt(SCRIPT_FILE)} is already executable. "
            "The student must set the executable bit themselves."
        )