# test_initial_state.py
#
# This pytest suite validates the initial filesystem state
# BEFORE the learner performs any actions.  It checks that:
#   1. The input directory /home/user/data exists and is a directory.
#   2. The CSV file /home/user/data/deployments.csv exists, is readable,
#      and its byte-for-byte contents match the specification given
#      in the exercise description.
#
# NOTE:
# * We purposefully do NOT test for the presence (or absence) of any
#   paths under /home/user/output because those are generated by the
#   learner’s solution.
# * Only Python’s standard library and pytest are used.

import os
import stat
import pytest

DATA_DIR = "/home/user/data"
CSV_PATH = os.path.join(DATA_DIR, "deployments.csv")

# The exact, canonical byte content of the CSV file (UTF-8, LF endings).
EXPECTED_CSV_BYTES = (
    b"namespace,app,image,replicas\n"
    b"default,api-server,nginx:1.21,3\n"
    b"prod,worker,python:3.10,5\n"
    b"dev,frontend,node:14,2\n"
)


def test_data_directory_exists_and_is_directory():
    """
    /home/user/data should exist and be a directory.
    """
    assert os.path.exists(DATA_DIR), (
        f"Required directory {DATA_DIR!r} is missing."
    )
    assert os.path.isdir(DATA_DIR), (
        f"{DATA_DIR!r} exists but is not a directory."
    )

    # Optional: basic permission sanity check (should be at least r-x for owner)
    mode = os.stat(DATA_DIR).st_mode
    assert bool(mode & stat.S_IRUSR), (
        f"{DATA_DIR!r} exists but is not readable by the current user."
    )
    assert bool(mode & stat.S_IXUSR), (
        f"{DATA_DIR!r} exists but is not searchable/executable by the current user."
    )


def test_csv_file_exists():
    """
    /home/user/data/deployments.csv should exist and be a regular file.
    """
    assert os.path.exists(CSV_PATH), (
        f"Required CSV file {CSV_PATH!r} is missing."
    )
    assert os.path.isfile(CSV_PATH), (
        f"{CSV_PATH!r} exists but is not a regular file."
    )

    # Optional: check that file is world-readable (644 is expected).
    file_mode = os.stat(CSV_PATH).st_mode & 0o777
    expected_mode = 0o644
    assert file_mode == expected_mode, (
        f"{CSV_PATH!r} permissions are {oct(file_mode)}, expected {oct(expected_mode)}."
    )


def test_csv_file_content_is_exact():
    """
    The CSV file's content must match the exact byte sequence specified
    in the task description (UTF-8, LF line endings, trailing newline).
    """
    with open(CSV_PATH, "rb") as fp:
        actual_bytes = fp.read()

    # Helpful diff in error message if the content is wrong.
    assert actual_bytes == EXPECTED_CSV_BYTES, (
        "CSV file content does not match specification.\n"
        f"Expected bytes:\n{EXPECTED_CSV_BYTES!r}\n"
        f"Actual bytes:\n{actual_bytes!r}"
    )


def test_csv_file_has_exactly_four_lines():
    """
    Sanity check: the CSV file must contain exactly four lines
    (header + three records).
    """
    with open(CSV_PATH, "r", encoding="utf-8") as fp:
        lines = fp.readlines()

    assert len(lines) == 4, (
        f"CSV file should have exactly 4 lines (including header); "
        f"found {len(lines)} line(s)."
    )