# test_initial_state.py
#
# Pytest suite that verifies the *initial* filesystem state required for the
# “release-manager” exercise.  These tests must pass *before* the student runs
# any commands.  They assert that the prerequisite directory and input file
# exist with the correct permissions and exact contents.
#
# IMPORTANT:
#   • DO NOT edit this file.
#   • DO NOT create the output file (`latest_versions.txt`) here; that is the
#     learner’s task.
#   • Only standard-library modules plus `pytest` are used.

import os
import stat
import pytest

HOME = "/home/user"
RELEASES_DIR = os.path.join(HOME, "releases")
VERSIONS_FILE = os.path.join(RELEASES_DIR, "versions.txt")

EXPECTED_VERSIONS_CONTENT = (
    "1.0.0\n"
    "2.0.0\n"
    "1.5.0\n"
    "2.1.0\n"
    "1.0.0\n"
    "3.0.0\n"
    "2.1.0\n"
    "1.2.0\n"
)

DIR_PERMS = 0o755
FILE_PERMS = 0o644


def _mode(path):
    "Return permission bits in the style of `0o755`."
    return stat.S_IMODE(os.stat(path).st_mode)


def test_releases_directory_exists_with_correct_permissions():
    assert os.path.exists(RELEASES_DIR), (
        f"Required directory missing: {RELEASES_DIR}"
    )
    assert os.path.isdir(RELEASES_DIR), (
        f"Expected {RELEASES_DIR} to be a directory."
    )

    perms = _mode(RELEASES_DIR)
    assert perms == DIR_PERMS, (
        f"{RELEASES_DIR} permissions are {oct(perms)}, expected {oct(DIR_PERMS)}."
    )


def test_versions_file_exists_with_correct_permissions_and_contents():
    assert os.path.exists(VERSIONS_FILE), (
        f"Required file missing: {VERSIONS_FILE}"
    )
    assert os.path.isfile(VERSIONS_FILE), (
        f"Expected {VERSIONS_FILE} to be a regular file."
    )

    perms = _mode(VERSIONS_FILE)
    assert perms == FILE_PERMS, (
        f"{VERSIONS_FILE} permissions are {oct(perms)}, expected {oct(FILE_PERMS)}."
    )

    with open(VERSIONS_FILE, "r", encoding="utf-8", newline="") as fh:
        data = fh.read()

    assert data == EXPECTED_VERSIONS_CONTENT, (
        f"{VERSIONS_FILE} contents do not match expected initial data.\n"
        "---- Expected ----\n"
        f"{EXPECTED_VERSIONS_CONTENT}"
        "------------------\n"
        "If the file was modified, restore it to the original 8-line list."
    )