# test_initial_state.py
#
# This pytest suite validates that the operating-system / filesystem
# is in the expected *clean* state **before** the student carries out
# any actions for the “FinOps network diagnostics” task.
#
# What we check:
#   1. The user’s home directory exists.
#   2. The summary directory *does NOT* yet exist.
#   3. The summary file *does NOT* yet exist.
#   4. The required networking tools (`ping`, `traceroute`) are available.
#   5. The local network behaves as expected so the student can succeed:
#        • Pinging 127.0.0.1 loses 0 % packets.
#        • Traceroute to 127.0.0.1 reveals exactly one hop.
#
# We purposely do *not* look for any output generated by the student.

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

HOME = Path("/home/user")
SUMMARY_DIR = HOME / "finops_diagnostics"
SUMMARY_FILE = SUMMARY_DIR / "network_validation.log"


def _run(cmd):
    """Helper to run a command and capture UTF-8 stdout/stderr."""
    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
    )
    return result.stdout


@pytest.mark.dependency(name="home_dir")
def test_home_directory_exists():
    assert HOME.exists(), f"Expected home directory {HOME} to exist"
    assert HOME.is_dir(), f"Expected {HOME} to be a directory"


@pytest.mark.dependency(name="no_summary_dir", depends=["home_dir"])
def test_summary_directory_does_not_exist():
    assert not SUMMARY_DIR.exists(), (
        f"The directory {SUMMARY_DIR} already exists but this should be created "
        "by the student’s solution. Please remove it before running the grader."
    )


@pytest.mark.dependency(depends=["no_summary_dir"])
def test_summary_file_does_not_exist():
    assert not SUMMARY_FILE.exists(), (
        f"The file {SUMMARY_FILE} already exists but this should be created "
        "by the student’s solution. Please remove it before running the grader."
    )


@pytest.mark.dependency(name="tools_present")
def test_required_tools_are_installed():
    missing = [tool for tool in ("ping", "traceroute") if shutil.which(tool) is None]
    assert not missing, (
        "The following required networking tool(s) are missing from the system: "
        f"{', '.join(missing)}"
    )


@pytest.mark.dependency(depends=["tools_present"])
def test_ping_loopback_has_zero_packet_loss():
    # Run exactly the same command specification given to the student
    out = _run(["ping", "-c", "3", "127.0.0.1"])
    # Look for the summary line: "3 packets transmitted, 3 received, 0% packet loss, time ..."
    m = re.search(r"(\d+)\s+packets transmitted,\s+(\d+)\s+received, "
                  r"(\d+)%\s+packet loss", out)
    assert m, (
        "Unable to parse packet-loss information from ping output; "
        "output was:\n" + out
    )
    pkt_loss = int(m.group(3))
    assert pkt_loss == 0, (
        f"Loopback ping unexpectedly reports {pkt_loss}% packet loss; "
        "it must be 0% for the task to pass."
    )


@pytest.mark.dependency(depends=["tools_present"])
def test_traceroute_loopback_has_single_hop():
    out = _run(["traceroute", "-n", "127.0.0.1"])
    # Count lines that start with an integer followed by at least one space.
    hop_lines = [ln for ln in out.splitlines()
                 if re.match(r"^\s*\d+\s", ln)]
    assert hop_lines, (
        "Unable to detect any hop lines in traceroute output; "
        "output was:\n" + out
    )
    assert len(hop_lines) == 1, (
        f"Traceroute to 127.0.0.1 should have exactly 1 hop, "
        f"but {len(hop_lines)} hop lines were detected:\n" + out
    )