# test_initial_state.py
#
# This test-suite validates the **initial** operating-system / filesystem
# state *before* the student performs any actions for the “quick baseline
# timing” task.  It purposefully checks only the resources that must already
# be present (the mock API directory and its JSON files) and verifies that
# nothing of the expected output (perf_logs directory, CSV log file) has been
# created yet.

import os
import json
import stat
import pytest
from pathlib import Path

# Constants for paths we care about
HOME_DIR = Path("/home/user")
MOCK_API_DIR = HOME_DIR / "mock_api"
PERF_LOGS_DIR = HOME_DIR / "perf_logs"
PERF_LOG_FILE = PERF_LOGS_DIR / "api_performance.log"

USERS_JSON = MOCK_API_DIR / "users.json"
POSTS_JSON = MOCK_API_DIR / "posts.json"
COMMENTS_JSON = MOCK_API_DIR / "comments.json"

MOCK_FILES = [USERS_JSON, POSTS_JSON, COMMENTS_JSON]


def _assert_mode_readable(path: Path, who: str):
    """
    Helper: ensure *path* is readable by the current user (and optionally by
    others).  `who` is only used for a clearer error message.
    """
    st_mode = path.stat().st_mode
    assert bool(st_mode & stat.S_IRUSR), f"{who} is not readable by user: {path}"


def test_mock_api_directory_exists_and_has_correct_mode():
    """The /home/user/mock_api directory must already exist and be readable."""
    assert MOCK_API_DIR.exists(), (
        f"Required directory missing: {MOCK_API_DIR}. "
        "The initial state must ship with the mock API resources."
    )
    assert MOCK_API_DIR.is_dir(), f"Expected {MOCK_API_DIR} to be a directory."
    _assert_mode_readable(MOCK_API_DIR, "Directory /home/user/mock_api")


@pytest.mark.parametrize("json_path", MOCK_FILES, ids=[p.name for p in MOCK_FILES])
def test_mock_api_json_files_exist_and_are_valid_json(json_path):
    """
    Each JSON file must exist, be a regular file, be readable, and contain
    syntactically valid JSON.  Contents are not otherwise inspected here.
    """
    assert json_path.exists(), f"Required file missing: {json_path}"
    assert json_path.is_file(), f"Expected regular file: {json_path}"
    _assert_mode_readable(json_path, f"File {json_path}")

    # Validate JSON syntax
    try:
        with json_path.open("r", encoding="utf-8") as fh:
            json.load(fh)
    except json.JSONDecodeError as e:
        pytest.fail(f"Invalid JSON in {json_path}: {e}")


def test_perf_logs_directory_does_not_exist_yet():
    """
    The performance-logging directory must *not* exist before the student
    runs their commands, because creating it is part of the assignment.
    """
    assert not PERF_LOGS_DIR.exists(), (
        f"{PERF_LOGS_DIR} already exists, but it should be created by the "
        "student's solution script, not be present beforehand."
    )


def test_performance_log_file_does_not_exist_yet():
    """
    Likewise, the output CSV log file must *not* exist at the start.
    """
    assert not PERF_LOG_FILE.exists(), (
        f"{PERF_LOG_FILE} already exists, but it should be generated by the "
        "student's solution script."
    )