# test_initial_state.py
"""
Pytest suite to verify the *initial* system / filesystem state **before**
the student performs any work for the “network-glitches diagnostic bundle”
exercise.

The checks ensure that:
1.  No artefacts that the student is supposed to create already exist.
2.  All external tools the student must invoke are available.
3.  The execution environment is POSIX-like (not Windows).

Only the standard library + pytest are used.
"""

import os
import stat
import sys
import shutil
import re
import pathlib
import pytest

# --------------------------------------------------------------------------- #
# Constants used throughout the test suite                                    #
# --------------------------------------------------------------------------- #
DIAG_DIR      = pathlib.Path("/home/user/diagnostics")
SCRIPT_PATH   = DIAG_DIR / "run_net_checks.sh"
LOG_PATH      = DIAG_DIR / "netcheck.log"
SHA256_PATH   = DIAG_DIR / "netcheck.sha256"
REQUIRED_CMDS = ("ping", "traceroute", "dig")


# --------------------------------------------------------------------------- #
# Helper functions                                                            #
# --------------------------------------------------------------------------- #
def _path_readable(path: pathlib.Path) -> bool:
    """Return True if *path* exists and the current user can read it."""
    return path.exists() and os.access(path, os.R_OK)

def _path_executable(path: pathlib.Path) -> bool:
    """Return True if *path* exists and is executable by the current user."""
    return path.exists() and os.access(path, os.X_OK)


# --------------------------------------------------------------------------- #
# Tests                                                                       #
# --------------------------------------------------------------------------- #
def test_running_on_posix():
    """The evaluation container must be POSIX-compatible (not Windows)."""
    assert os.name == "posix", (
        "The evaluation environment must be POSIX-compatible (os.name == 'posix')."
    )
    assert sys.platform != "win32", (
        "The assignment expects a non-Windows platform; got sys.platform == 'win32'."
    )


@pytest.mark.parametrize("cmd", REQUIRED_CMDS)
def test_required_commands_exist_in_path(cmd):
    """
    ping, traceroute and dig must be available on the SYSTEM PATH
    *before* the student writes their script.
    """
    found = shutil.which(cmd)
    assert found, f"Required command '{cmd}' not found on $PATH."
    # Extra: ensure the file is executable
    assert os.access(found, os.X_OK), f"Command '{cmd}' exists at {found} but is not executable."


def test_diagnostics_directory_not_present_yet():
    """
    The /home/user/diagnostics directory should NOT exist yet.  
    It is the student's responsibility to create it.
    """
    assert not DIAG_DIR.exists(), (
        f"Directory {DIAG_DIR} already exists, but the student is supposed to create it."
    )


def test_no_preexisting_script():
    """
    The diagnostic shell script must not exist beforehand.
    """
    assert not SCRIPT_PATH.exists(), (
        f"Script {SCRIPT_PATH} already exists, but the student has not created it yet."
    )


@pytest.mark.parametrize("artefact", [LOG_PATH, SHA256_PATH])
def test_no_preexisting_output_files(artefact):
    """
    Neither netcheck.log nor netcheck.sha256 may exist at the start.
    """
    assert not artefact.exists(), (
        f"Output artefact {artefact} already exists; it must be generated by the student's script."
    )


def test_home_directory_permissions():
    """
    Basic sanity check: /home/user must be readable and writable so that the
    student can create the diagnostics directory and files.
    """
    home = pathlib.Path("/home/user")
    assert home.exists(), "Expected home directory /home/user to exist."
    assert os.access(home, os.W_OK), "/home/user is not writable by the current user."
    assert os.access(home, os.R_OK), "/home/user is not readable by the current user."


def test_no_marker_lines_in_nonexistent_log():
    """
    Ensure that if /home/user/diagnostics/netcheck.log *does* exist for any
    unforeseen reason, it does NOT already contain BEGIN/END marker lines,
    otherwise the student's output could be appended to stale data.
    """
    if not LOG_PATH.exists():
        pytest.skip("Log file does not exist yet – OK (expected).")

    # If it exists, inspect its contents.
    marker_regex = re.compile(r"^===== (START|END) host=.* check=.* =====$", re.MULTILINE)
    with LOG_PATH.open("r", encoding="utf-8", errors="ignore") as fh:
        content = fh.read()
    assert not marker_regex.search(content), (
        f"{LOG_PATH} already contains marker lines. The file must start empty."
    )