# test_initial_state.py
#
# This pytest suite validates that the machine is in the **initial** state
# expected *before* the student runs any commands.  Any test failure means the
# environment is already incorrect and the follow-up automated grading will be
# unreliable.

import hashlib
from pathlib import Path
import pytest

HOME = Path("/home/user")
DEPLOY_DIR = HOME / "deployment"
CONFIGS_DIR = DEPLOY_DIR / "configs"

APP_ENV_PATH = CONFIGS_DIR / "app.env"
DB_ENV_PATH = CONFIGS_DIR / "db.env"

BACKUP_DIR = DEPLOY_DIR / "backup"
RELEASE_NOTES = DEPLOY_DIR / "release_notes.txt"
UPDATE_LOG = DEPLOY_DIR / "update_log.json"


@pytest.fixture(scope="module")
def expected_contents():
    """
    Return the exact byte strings that must be present in the original files.
    """
    app_env = (
        b"APP_NAME=SampleApp\n"
        b"APP_VERSION=1.3.4\n"
        b"APP_PORT=8080\n"
    )
    db_env = (
        b"DB_NAME=sampledb\n"
        b"DB_HOST=localhost\n"
        b"DB_PORT=5432\n"
        b"DB_USER=sampleuser\n"
        b"DB_PASSWORD=samplepass\n"
    )
    return {"app.env": app_env, "db.env": db_env}


def sha256(path: Path) -> str:
    """Compute a hex sha256 for a small text file."""
    data = path.read_bytes()
    return hashlib.sha256(data).hexdigest()


def test_directory_structure():
    assert CONFIGS_DIR.is_dir(), (
        f"Expected directory {CONFIGS_DIR} to exist. "
        "The initial deployment configs directory is missing."
    )


def test_required_files_exist():
    for p in (APP_ENV_PATH, DB_ENV_PATH):
        assert p.is_file(), f"Required file {p} is missing."


def test_original_file_contents(expected_contents, tmp_path):
    """
    Verify that the two config files contain exactly the original, pre-update
    contents.  This is done via byte-for-byte comparison so that whitespace,
    ordering, and line endings are enforced.
    """
    file_map = {
        APP_ENV_PATH: expected_contents["app.env"],
        DB_ENV_PATH: expected_contents["db.env"],
    }

    for path, expected_bytes in file_map.items():
        data = path.read_bytes()
        assert (
            data == expected_bytes
        ), (
            f"File {path} does not match the required initial contents.\n"
            "If this file was already modified, restore it to its original "
            "state before running the update steps."
        )


def test_no_backup_dir_yet():
    assert not BACKUP_DIR.exists(), (
        f"Backup directory {BACKUP_DIR} should NOT exist yet. "
        "It must be created by the student's script."
    )


def test_no_output_files_yet():
    for p in (RELEASE_NOTES, UPDATE_LOG):
        assert not p.exists(), (
            f"File {p} should NOT exist at the initial state. "
            "It must be generated by the student's script."
        )