# test_initial_state.py
#
# This pytest suite verifies that the system is in a *clean* (pre-task) state
# before the student begins their work.  Nothing required by the final
# specification should exist yet, and no environment variable line should have
# been pre-added to ~/.bashrc.  If any of these checks fail, the image the
# student receives is not pristine and the exercise would be unfair.

import os
from pathlib import Path

HOME = Path("/home/user")
MONITORING_DIR = HOME / "monitoring"
BASHRC_FILE = HOME / ".bashrc"
ALERT_RULES_FILE = MONITORING_DIR / "alert_rules.cfg"
SETUP_LOG_FILE = MONITORING_DIR / "setup.log"
EXPORT_LINE = "export ALERT_EMAIL=ops@example.com"


def test_home_directory_exists():
    """Sanity-check that /home/user itself is present."""
    assert HOME.is_dir(), "The base home directory /home/user is missing."


def test_monitoring_directory_absent():
    """The /home/user/monitoring directory must NOT exist at the start."""
    assert not MONITORING_DIR.exists(), (
        "The directory /home/user/monitoring already exists. "
        "The system should start in a clean state so the student can create it."
    )


def test_bashrc_does_not_contain_export_line():
    """
    ~/.bashrc may or may not exist, but it must NOT already contain the
    required export line.  That line is the student's responsibility to add.
    """
    if BASHRC_FILE.exists():
        bashrc_content = BASHRC_FILE.read_text(encoding="utf-8").splitlines()
        assert EXPORT_LINE not in bashrc_content, (
            f"The line '{EXPORT_LINE}' is already present in {BASHRC_FILE}. "
            "It should be added by the student, not pre-populated."
        )


def test_alert_rules_file_absent():
    """The alert rule configuration file should not pre-exist."""
    assert not ALERT_RULES_FILE.exists(), (
        f"The file {ALERT_RULES_FILE} already exists. "
        "It must be created by the student during the task."
    )


def test_setup_log_file_absent():
    """The setup log file should not pre-exist."""
    assert not SETUP_LOG_FILE.exists(), (
        f"The file {SETUP_LOG_FILE} already exists. "
        "It must be generated by the student during the task."
    )