# test_initial_state.py
#
# This test-suite verifies the *initial* filesystem state that must be
# present **before** the student begins work on the “storage administrator”
# exercise.  Do NOT modify this file.  If any of these tests fail, the
# sandbox is incorrectly set up.

import os
from pathlib import Path

ROOT = Path("/home/user")
LOGS = ROOT / "logs"
APP1 = LOGS / "app1"
APP2 = LOGS / "app2"

def _read(p: Path) -> str:
    """Return the full text of a file, raising AssertionError if it fails."""
    assert p.is_file(), f"Expected {p} to be a regular file."
    try:
        return p.read_text()
    except Exception as exc:  # pragma: no cover
        raise AssertionError(f"Could not read file {p}: {exc}") from exc


def test_logs_directory_structure_exists():
    """Verify /home/user/logs, app1, and app2 directories exist as directories."""
    assert LOGS.is_dir(), f"Missing directory: {LOGS}"
    assert APP1.is_dir(), f"Missing directory: {APP1}"
    assert APP2.is_dir(), f"Missing directory: {APP2}"


def test_app1_log_files_exist_with_expected_contents():
    """Check log1.txt and log2.txt exist in app1 with the correct contents."""
    log1 = APP1 / "log1.txt"
    log2 = APP1 / "log2.txt"

    assert log1.is_file(), f"Expected file not found: {log1}"
    assert log2.is_file(), f"Expected file not found: {log2}"

    exp1 = "Error ABC\n"
    exp2 = "Warning XYZ\n"
    got1 = _read(log1)
    got2 = _read(log2)
    assert got1 == exp1, f"Unexpected contents for {log1!s}: {got1!r} (expected {exp1!r})"
    assert got2 == exp2, f"Unexpected contents for {log2!s}: {got2!r} (expected {exp2!r})"


def test_app2_log_file_exists_with_expected_contents():
    """Check logA.txt exists in app2 with the correct content."""
    logA = APP2 / "logA.txt"
    assert logA.is_file(), f"Expected file not found: {logA}"

    exp = "Debug 123\n"
    got = _read(logA)
    assert got == exp, f"Unexpected contents for {logA!s}: {got!r} (expected {exp!r})"


def test_preconditions_absence_of_archive_and_audit():
    """Ensure items that must not exist yet are indeed absent."""
    archive = ROOT / "archive"
    symlink_audit = ROOT / "symlink_audit.log"

    assert not archive.exists(), (
        f"{archive} already exists but should be created by the student's solution."
    )
    assert not symlink_audit.exists(), (
        f"{symlink_audit} already exists but should be generated by the student's solution."
    )


def test_app2_is_directory_not_symlink():
    """The initial /home/user/logs/app2 must be a directory, not a symlink."""
    assert APP2.exists(), f"Missing {APP2}"
    assert APP2.is_dir(), f"{APP2} should be a directory."
    assert not APP2.is_symlink(), f"{APP2} should NOT be a symbolic link yet."


def test_old_latest_symlink_not_present():
    """The relative symlink 'old_latest' should not exist before the student action."""
    old_latest = APP1 / "old_latest"
    assert not old_latest.exists(), (
        f"{old_latest} should be created by the student's solution and must not exist beforehand."
    )