# test_initial_state.py
#
# A pytest suite that validates the *initial* operating-system /
# file-system state **before** the student performs any action for the
# “training-data rsync” exercise described in the task.  These tests
# must all pass *as delivered* by the exercise author.  They will begin
# failing as soon as the student’s solution modifies the directory
# tree, copies files, or creates the synchronisation log.

import os
from pathlib import Path

import pytest

# ---------------------------------------------------------------------
# Constant paths used throughout the tests
# ---------------------------------------------------------------------
HOME = Path("/home/user")

REMOTE_ROOT = HOME / "remote_server" / "training_data"
LOCAL_PROJECT_ROOT = HOME / "local_project"
LOCAL_DATA_DIR = LOCAL_PROJECT_ROOT / "data"

SYNC_LOGS_DIR = HOME / "sync_logs"
SYNC_LOG_FILE = SYNC_LOGS_DIR / "training_data_sync.log"

# Expected files & directories under the remote tree
REMOTE_EXPECTED_DIRS = {
    REMOTE_ROOT / "images",
    REMOTE_ROOT / "labels",
}

REMOTE_EXPECTED_FILES = {
    REMOTE_ROOT / "images" / "image1.jpg",
    REMOTE_ROOT / "images" / "image2.jpg",
    REMOTE_ROOT / "labels" / "image1.txt",
    REMOTE_ROOT / "labels" / "image2.txt",
    REMOTE_ROOT / "README.md",
}


# ---------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------
def assert_is_file(path: Path):
    assert path.exists(), f"Expected file {path} to exist, but it is missing."
    assert path.is_file(), f"Expected {path} to be a regular file."


def assert_is_dir(path: Path):
    assert path.exists(), f"Expected directory {path} to exist, but it is missing."
    assert path.is_dir(), f"Expected {path} to be a directory."


# ---------------------------------------------------------------------
# Tests for the *remote* training-data tree
# ---------------------------------------------------------------------
def test_remote_tree_exists_and_is_complete():
    """
    Verify that the remote training-data directory tree exists and
    already contains all required files & sub-directories *before* the
    student runs any commands.
    """
    # Remote root directory
    assert_is_dir(REMOTE_ROOT)

    # Required sub-directories
    for d in REMOTE_EXPECTED_DIRS:
        assert_is_dir(d)

    # Required files
    for f in REMOTE_EXPECTED_FILES:
        assert_is_file(f)

    # Sanity-check that files are non-empty (guards against zero-byte placeholders)
    empty_files = [str(f) for f in REMOTE_EXPECTED_FILES if f.stat().st_size == 0]
    assert not empty_files, (
        "The following expected data files are unexpectedly empty: "
        + ", ".join(empty_files)
    )


# ---------------------------------------------------------------------
# Tests for the *local* project area (before synchronisation)
# ---------------------------------------------------------------------
def test_local_project_exists_and_is_initially_empty():
    """
    The local project directory itself must already exist (the student
    will not have to create it), *but* the target data/ directory
    should **not** exist yet.  This confirms that synchronisation has
    not been performed before the exercise starts.
    """
    # Root of the local project must exist.
    assert_is_dir(LOCAL_PROJECT_ROOT)

    # The data directory must *not* exist yet.
    assert not LOCAL_DATA_DIR.exists(), (
        f"{LOCAL_DATA_DIR} should NOT exist before the student runs the "
        "rsync command, but it is already present."
    )


# ---------------------------------------------------------------------
# Tests for the absence of any pre-existing sync logs
# ---------------------------------------------------------------------
def test_no_sync_log_yet():
    """
    The synchronisation log directory (/home/user/sync_logs) and the
    specific log file must not exist at the outset.  Their creation is
    part of the student’s task.
    """
    assert not SYNC_LOGS_DIR.exists(), (
        f"The directory {SYNC_LOGS_DIR} already exists, "
        "but it should be created by the student's script."
    )
    assert not SYNC_LOG_FILE.exists(), (
        f"The log file {SYNC_LOG_FILE} already exists, "
        "but it should be generated by the student's script."
    )