# test_initial_state.py
#
# This test-suite verifies that the machine starts in the **pristine**
# state expected by the assignment *before* the student runs any code.
#
# It checks that:
#   • The required input directory and files are present **exactly** as
#     specified (content, row-count, header spelling, blank fields, etc.).
#   • The device registry JSON file is present and contains the correct
#     objects (order of keys inside each object is irrelevant).
#   • None of the output artefacts that the student is supposed to create
#     exist yet.  They must be generated by the student’s solution.
#
# Only the Python Standard Library and pytest are used.
#
# NOTE:  If any assertion here fails, it means the starting environment is
#        wrong and the student cannot reasonably complete the task.

from pathlib import Path
import csv
import json
import pytest


HOME = Path("/home/user")
INPUT_DIR = HOME / "iot_data"
REGISTRY_FILE = HOME / "device_registry.json"
OUTPUT_DIR = HOME / "iot_output"

EXPECTED_INPUT_FILES = {
    "device_A.csv": [
        "timestamp,temperature,humidity",
        "2023-07-01T00:00:00Z,25.4,60",
        "2023-07-01T01:00:00Z,,61",
        "2023-07-01T02:00:00Z,26.1,62",
    ],
    "device_B.csv": [
        "timestamp,temperature,humidity",
        "2023-07-01T00:30:00Z,24.0,",
        "2023-07-01T01:30:00Z,24.5,59",
        "2023-07-01T02:30:00Z,25.0,60",
    ],
    "device_C.csv": [
        "timestamp,temperature,humidity",
        "2023-07-01T00:15:00Z,23.9,58",
        "2023-07-01T01:15:00Z,24.3,59",
        "2023-07-01T02:15:00Z,,57",
    ],
}

EXPECTED_REGISTRY = [
    {"device_id": "device_A", "location": "Building1", "type": "sensor"},
    {"device_id": "device_B", "location": "Building2", "type": "sensor"},
    {"device_id": "device_C", "location": "Building3", "type": "sensor"},
    {"device_id": "device_D", "location": "Building4", "type": "sensor"},
]

# --------------------------------------------------------------------------- #
# Helper functions
# --------------------------------------------------------------------------- #
def read_lines(path: Path):
    """Return the file as a list of lines *without* trailing newline chars."""
    return path.read_text(encoding="utf-8").splitlines()


# --------------------------------------------------------------------------- #
# Tests
# --------------------------------------------------------------------------- #
def test_input_directory_exists():
    assert INPUT_DIR.is_dir(), (
        f"Required input directory {INPUT_DIR} is missing. "
        "The assignment cannot proceed."
    )


@pytest.mark.parametrize("filename,expected_lines", EXPECTED_INPUT_FILES.items())
def test_each_input_csv_present_and_correct(filename, expected_lines):
    file_path = INPUT_DIR / filename
    assert file_path.is_file(), f"Expected input file {file_path} is missing."

    # Read file as text (to keep blank fields intact) and compare line-by-line
    actual_lines = read_lines(file_path)
    assert (
        actual_lines == expected_lines
    ), (
        f"File {file_path} does not match the expected content.\n"
        f"Expected lines:\n{expected_lines!r}\n\nActual lines:\n{actual_lines!r}"
    )

    # Extra guard: ensure correct number of rows
    assert len(actual_lines) == 4, (
        f"File {file_path} should contain exactly 4 lines "
        "(header + 3 data rows).  Found: {len(actual_lines)}"
    )

    # Check header spelling explicitly
    assert (
        actual_lines[0] == "timestamp,temperature,humidity"
    ), f"Header row in {file_path} is incorrect."


def test_device_registry_present_and_correct():
    assert REGISTRY_FILE.is_file(), (
        f"Device registry file {REGISTRY_FILE} is missing."
    )

    try:
        registry = json.loads(REGISTRY_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        pytest.fail(f"Device registry JSON could not be parsed: {exc}")

    # The registry must be a list of dicts matching EXACTLY the expected objects
    assert isinstance(registry, list), "Device registry JSON is not a list."
    assert len(registry) == len(
        EXPECTED_REGISTRY
    ), f"Registry should contain {len(EXPECTED_REGISTRY)} objects."

    # Compare objects irrespective of internal key order
    for expected_obj in EXPECTED_REGISTRY:
        assert (
            expected_obj in registry
        ), f"Registry is missing expected object: {expected_obj}"


@pytest.mark.parametrize(
    "path_str",
    [
        "/home/user/iot_output/devices_sensors_clean.csv",
        "/home/user/iot_output/summary.json",
        "/home/user/iot_output/updated_registry.json",
        "/home/user/iot_output/process.log",
    ],
)
def test_output_files_do_not_exist_yet(path_str):
    """
    Prior to running the student's solution, *none* of the expected output
    artefacts should be present.  The student must create them.
    """
    path = Path(path_str)
    assert not path.exists(), (
        f"Output file {path} already exists before the task has been run. "
        "The environment is not in the expected initial state."
    )


def test_output_directory_is_empty_or_absent():
    """
    The /home/user/iot_output directory may or may not exist at the start,
    but if it does, it must be completely empty so the student can create the
    required artefacts without name conflicts.
    """
    if not OUTPUT_DIR.exists():
        # Directory absent → fine.
        return

    assert OUTPUT_DIR.is_dir(), f"{OUTPUT_DIR} exists but is not a directory."
    existing_items = list(OUTPUT_DIR.iterdir())
    assert (
        len(existing_items) == 0
    ), (
        f"{OUTPUT_DIR} should be empty at the beginning. "
        f"Found unexpected content: {[str(p) for p in existing_items]}"
    )