# test_initial_state.py
#
# This pytest suite validates that the operating-system / file-system
# is in the expected *initial* state **before** the student begins the
# task described in the assignment.  It intentionally fails if any of
# the task-generated artefacts are already present.
#
# Requirements verified:
#   • /home/user exists and is writable.
#   • /home/user/system_diagnostics does NOT yet exist.
#   • No task output files exist.

import os
import stat
import pytest


HOME_DIR = "/home/user"
DIAG_DIR = "/home/user/system_diagnostics"
EXPECTED_FILES = [
    "/home/user/system_diagnostics/diagnostics.log",
    "/home/user/system_diagnostics/memory_summary.csv",
    "/home/user/system_diagnostics/disk_root_usage.txt",
]


def test_home_directory_exists_and_writable():
    """
    The base directory /home/user must exist and be writable before the
    student starts.  This guarantees that the student can create the
    required sub-directory and files without elevated privileges.
    """
    assert os.path.isdir(HOME_DIR), (
        f"Expected {HOME_DIR} to exist as a directory, "
        "but it is missing."
    )

    mode = os.stat(HOME_DIR).st_mode
    writable = bool(mode & (stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH))
    executable = bool(mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH))

    assert writable and executable, (
        f"{HOME_DIR} must be writable and accessible by the current user."
    )


def test_system_diagnostics_directory_absent():
    """
    The target directory must NOT exist yet; creating it is part of the
    assignment.  If it already exists, the initial state is invalid.
    """
    assert not os.path.exists(DIAG_DIR), (
        f"The directory {DIAG_DIR} unexpectedly exists. "
        "It should be created by the student's solution."
    )


@pytest.mark.parametrize("file_path", EXPECTED_FILES)
def test_output_files_absent(file_path):
    """
    None of the expected artefacts should pre-exist in the file-system.
    """
    assert not os.path.exists(file_path), (
        f"The file {file_path} unexpectedly exists in the initial state. "
        "All task output files must be generated by the student's code."
    )