# test_initial_state.py
#
# Pytest suite that validates the *initial* state of the filesystem
# before the student begins working on the “tiny build system” task.
#
# The checks mirror the ground-truth specification:
#   • Only two dummy log files should exist so far.
#   • No Makefile, report, archive, or archives/ directory should be present.
#
# If any assertion fails the accompanying message pin-points
# the exact path that is either missing or unexpectedly present.
#
# NOTE:  This test file uses only the Python standard library + pytest.

import os
from pathlib import Path

HOME = Path("/home/user")
DISK_ADMIN = HOME / "disk_admin"
REPORTS_DIR = DISK_ADMIN / "reports"
ARCHIVES_DIR = REPORTS_DIR / "archives"
MAKEFILE = DISK_ADMIN / "Makefile"

OLD_LOG_1 = REPORTS_DIR / "old_app1.log"
OLD_LOG_2 = REPORTS_DIR / "old_app2.log"

LATEST_REPORT = REPORTS_DIR / "latest_report.log"
TAR_GZ = ARCHIVES_DIR / "disk_reports_archive.tar.gz"


def test_required_directories_exist():
    """The base directories /home/user/disk_admin and /reports/ must already exist."""
    assert DISK_ADMIN.is_dir(), f"Missing directory: {DISK_ADMIN}"
    assert REPORTS_DIR.is_dir(), f"Missing directory: {REPORTS_DIR}"


def test_archives_directory_absent_initially():
    """
    The archives/ directory should **NOT** exist yet.
    It must be created by the student's Makefile when needed.
    """
    assert not ARCHIVES_DIR.exists(), (
        f"The directory {ARCHIVES_DIR} should not exist at the initial state."
    )


def test_old_log_files_present_with_expected_content():
    """Both dummy log files must exist and hold the expected single-line content."""
    for path, expected in [
        (OLD_LOG_1, "dummy1"),
        (OLD_LOG_2, "dummy2"),
    ]:
        assert path.is_file(), f"Required log file missing: {path}"
        content = path.read_text(encoding="utf-8").strip()
        assert content == expected, (
            f"Unexpected contents in {path}. "
            f"Expected a single line with '{expected}', got '{content}'."
        )


def test_makefile_absent_initially():
    """
    The Makefile should not exist yet; writing it is part of the assignment.
    """
    assert not MAKEFILE.exists(), f"{MAKEFILE} already exists — the student must create it."


def test_latest_report_and_archive_absent():
    """
    Neither latest_report.log nor the tar.gz archive should exist before any Make target runs.
    """
    assert not LATEST_REPORT.exists(), (
        f"{LATEST_REPORT} already exists — it must be generated by the 'report' target."
    )
    assert not TAR_GZ.exists(), (
        f"{TAR_GZ} already exists — it must be created by the 'archive' target."
    )