# test_initial_state.py
#
# This pytest suite validates the expected *initial* state of the
# filesystem before the student’s solution is executed.  If any of these
# tests fail, the learner is starting from an unexpected environment and
# the grader will provide a clear error message about what is missing or
# what should *not* yet exist.

import os
import pytest
from pathlib import Path


HOME = Path("/home/user")
BASE_DIR = HOME / "cloud_costs"
RAW_DIR = BASE_DIR / "raw"
REPORTS_DIR = BASE_DIR / "reports"
ARCHIVE_DIR = BASE_DIR / "archive"

RAW_FILES = {
    RAW_DIR / "sep1.csv": [
        "service,region,amount",
        "EC2,us-east-1,120.50",
        "S3,us-east-1,30.00",
        "Lambda,us-east-1,10.50",
    ],
    RAW_DIR / "sep2.csv": [
        "service,region,amount",
        "EC2,us-east-1,100.00",
        "S3,us-east-1,25.00",
        "RDS,us-east-1,80.00",
    ],
    RAW_DIR / "sep3.csv": [
        "service,region,amount",
        "EC2,us-west-2,90.00",
        "S3,us-west-2,20.00",
        "RDS,us-west-2,60.00",
    ],
}


def _read_file_lines(path: Path):
    """
    Helper that reads a text file and returns a list of its lines
    *without* their trailing newline characters.
    """
    with path.open("r", encoding="utf-8") as fp:
        return [line.rstrip("\n") for line in fp.readlines()]


def test_base_and_raw_directories_exist():
    """The top-level and raw directories must already exist."""
    assert BASE_DIR.is_dir(), f"Expected directory {BASE_DIR} to exist"
    assert RAW_DIR.is_dir(), f"Expected directory {RAW_DIR} to exist"


def test_reports_and_archive_do_not_yet_exist():
    """
    These directories should NOT exist before the learner runs their code;
    they are supposed to be *created* by the solution.
    """
    assert not REPORTS_DIR.exists(), f"Directory {REPORTS_DIR} should NOT exist yet"
    assert not ARCHIVE_DIR.exists(), f"Directory {ARCHIVE_DIR} should NOT exist yet"


@pytest.mark.parametrize("csv_path,expected_lines", RAW_FILES.items())
def test_raw_csv_files_exist_with_exact_contents(csv_path: Path, expected_lines):
    """
    Each raw CSV file must be present with the exact expected contents.
    """
    assert csv_path.is_file(), f"Expected file {csv_path} to exist"

    actual_lines = _read_file_lines(csv_path)
    assert (
        actual_lines == expected_lines
    ), f"Contents of {csv_path} are not as expected.\nExpected:\n{expected_lines}\nActual:\n{actual_lines}"


def test_no_report_or_action_logs_present_yet():
    """
    The summary and actions log files should not yet exist; they will be
    generated by the learner's script.
    """
    summary_file = REPORTS_DIR / "summary_sep_2023.log"
    actions_file = REPORTS_DIR / "actions.log"

    assert not summary_file.exists(), f"{summary_file} should NOT exist before processing"
    assert not actions_file.exists(), f"{actions_file} should NOT exist before processing"


def test_no_archive_done_files_exist_yet():
    """
    The '.done' files must not exist before processing; they will be
    created when the raw files are moved.
    """
    for raw_path in RAW_FILES:
        done_path = ARCHIVE_DIR / (raw_path.name + ".done")
        assert not done_path.exists(), (
            f"{done_path} should NOT exist yet; it will be created "
            "when the raw files are moved to the archive directory"
        )