# test_initial_state.py
#
# Pytest suite to validate the initial filesystem / OS state
# BEFORE the student carries out the provisioning-summary task.
#
# The checks performed here guarantee that
#   1. the source log file exists and is well-formed, and
#   2. the target report directory / file do NOT yet exist.
#
# Only Python’s stdlib and pytest are used.

import os
from collections import Counter
import pytest

HOME = "/home/user"
LOG_FILE = os.path.join(HOME, "provisioning", "instance_requests.log")
REPORT_DIR = os.path.join(HOME, "provisioning", "report")
REPORT_FILE = os.path.join(REPORT_DIR, "instance_type_frequency.txt")


@pytest.fixture(scope="session")
def log_lines():
    """Read and return all lines from the instance_request log as a list of str.

    The fixture will fail fast with a clear message if the file cannot be read.
    """
    assert os.path.isfile(LOG_FILE), (
        f"Required log file missing: {LOG_FILE!r}. "
        "The test environment must ship this file *before* the exercise starts."
    )

    # Read the file; ensure UTF-8 decoding.
    with open(LOG_FILE, "r", encoding="utf-8") as fh:
        lines = fh.read().splitlines()

    return lines


def test_log_file_line_count(log_lines):
    """The log must contain *exactly* 7 lines."""
    expected_line_count = 7
    assert len(log_lines) == expected_line_count, (
        f"{LOG_FILE!r} should contain exactly {expected_line_count} lines, "
        f"but {len(log_lines)} line(s) were found."
    )


def test_log_file_no_whitespace(log_lines):
    """Each log line must be a single AWS instance-type string with no extra whitespace."""
    offending = [
        (idx + 1, line)
        for idx, line in enumerate(log_lines)
        if line.strip() != line or " " in line or "\t" in line
    ]
    assert not offending, (
        f"The following line(s) in {LOG_FILE!r} contain leading/trailing or "
        f"embedded whitespace:\n" +
        "\n".join(f"  line {lnum}: {txt!r}" for lnum, txt in offending)
    )


def test_log_file_expected_frequencies(log_lines):
    """Validate that the log contains the expected 4 distinct instance types and counts."""
    expected_counts = {
        "t2.micro": 3,
        "m5.large": 2,
        "c5.large": 1,
        "c5.xlarge": 1,
    }

    counts = Counter(log_lines)

    # First check we have exactly the same keys.
    assert set(counts) == set(expected_counts), (
        "The set of instance types present in the log file is incorrect.\n"
        f"Expected: {sorted(expected_counts)}\n"
        f"Found   : {sorted(counts)}"
    )

    # Now check each individual count.
    mismatches = {
        itype: (counts[itype], expected_counts[itype])
        for itype in expected_counts
        if counts[itype] != expected_counts[itype]
    }

    assert not mismatches, (
        "The following instance-type counts are wrong in the log file:\n" +
        "\n".join(
            f"  {itype}: found {found}, expected {exp}"
            for itype, (found, exp) in mismatches.items()
        )
    )


def test_report_directory_absent():
    """The /home/user/provisioning/report directory must NOT yet exist."""
    assert not os.path.exists(REPORT_DIR), (
        f"The report directory {REPORT_DIR!r} already exists, but it should be "
        "created by the student's solution, not be present in the initial state."
    )


def test_report_file_absent():
    """The target report file must NOT yet exist."""
    assert not os.path.exists(REPORT_FILE), (
        f"The report file {REPORT_FILE!r} already exists, but it should be "
        "generated by the student's solution, not be present in the initial state."
    )