# test_initial_state.py
#
# This test-suite validates that the starting filesystem state
# is exactly what the student instructions describe.
# It purposefully FAILS if:
#   • The three raw CSVs are not present with the exact expected
#     contents in /home/user/raw_costs/
#   • Any of the “output” artefacts/directories already exist.
#
# NOTE:  These tests must be run *before* the student performs
#        any actions.

import os
import pathlib
import pytest

HOME = pathlib.Path("/home/user")
RAW_DIR = HOME / "raw_costs"
DEST_DIR = HOME / "finops" / "project1"
ARCHIVE_DIR = DEST_DIR / "archive"

AWS_CSV = RAW_DIR / "aws_july2023.csv"
GCP_CSV = RAW_DIR / "gcp_july2023.csv"
AZURE_CSV = RAW_DIR / "azure_july2023.csv"

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
def read_lines(path: pathlib.Path):
    """
    Return the file’s contents as a list of lines *without*
    trailing newline characters.  Leading/trailing whitespace
    (other than newlines) is left intact to allow byte-for-byte
    comparison.
    """
    with path.open("r", encoding="utf-8") as fp:
        # .splitlines() removes the newline chars but keeps
        # blank lines as empty strings in the returned list.
        return fp.read().splitlines()


# -----------------------------------------------------------------------------
# Expected contents
# -----------------------------------------------------------------------------
AWS_EXPECTED = [
    "Cloud,Service,Environment,CostUSD",
    "AWS,EC2,Prod,123.45",
    "AWS,S3,Dev,45.67",
    "AWS,RDS,Prod,600.00",
    "AWS,Lambda,Dev,12.34",
    "AWS,DynamoDB,Prod,50.00",
]

GCP_EXPECTED = [
    "Cloud,Service,Environment,CostUSD",
    "GCP,Compute,Prod,200.11",
    "GCP,Storage,Dev,50.00",
    "GCP,BigQuery,Prod,700.00",
    "GCP,CloudFunctions,Dev,30.00",
]

AZURE_EXPECTED = [
    "Cloud,Service,Environment,CostUSD",
    "Azure,VM,Prod,400.00",
    "Azure,Blob,Dev,80.00",
    "Azure,SQLDB,Prod,650.00",
    "Azure,Functions,Dev,25.00",
]

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------
def test_raw_directory_and_files_exist():
    assert RAW_DIR.exists(), f"Expected directory {RAW_DIR} to exist."
    assert RAW_DIR.is_dir(), f"{RAW_DIR} exists but is not a directory."

    # Individual CSV presence
    for csv_path in (AWS_CSV, GCP_CSV, AZURE_CSV):
        assert csv_path.exists(), f"Expected file {csv_path} to be present."
        assert csv_path.is_file(), f"{csv_path} exists but is not a regular file."


@pytest.mark.parametrize(
    "csv_path,expected_lines",
    [
        (AWS_CSV, AWS_EXPECTED),
        (GCP_CSV, GCP_EXPECTED),
        (AZURE_CSV, AZURE_EXPECTED),
    ],
)
def test_raw_csv_contents(csv_path, expected_lines):
    actual = read_lines(csv_path)
    assert (
        actual == expected_lines
    ), f"Contents of {csv_path} differ from the expected template."


def test_no_destination_directories_exist_yet():
    assert not DEST_DIR.exists(), (
        f"Destination directory {DEST_DIR} already exists BEFORE the task starts. "
        "Student is expected to create it."
    )
    assert not ARCHIVE_DIR.exists(), (
        f"Archive directory {ARCHIVE_DIR} already exists BEFORE the task starts. "
        "Student is expected to create it."
    )


def test_no_output_files_exist_yet():
    """Ensure cost_summary.txt and run.log (and the CSV copies) are absent."""
    summary = DEST_DIR / "cost_summary.txt"
    runlog = DEST_DIR / "run.log"

    for output in (summary, runlog):
        assert not output.exists(), (
            f"File {output} already exists before the task starts. "
            "It should be generated by the student."
        )

    # Also ensure there are no CSVs in the prospective dest dir
    # (they’ll be copied there by the student).
    if DEST_DIR.exists():
        csvs_in_dest = list(DEST_DIR.glob("*_july2023.csv"))
        assert (
            not csvs_in_dest
        ), f"CSV files {csvs_in_dest} already found in {DEST_DIR}; none should exist yet."


def test_raw_directory_contains_only_expected_csvs():
    """
    For safety, verify there are no extra *_july2023.csv files
    that could interfere with downstream logic.
    """
    expected_names = {
        "aws_july2023.csv",
        "gcp_july2023.csv",
        "azure_july2023.csv",
    }
    actual_names = {p.name for p in RAW_DIR.glob("*_july2023.csv")}
    unexpected = actual_names - expected_names
    assert not unexpected, (
        f"Unexpected CSV files found in {RAW_DIR}: {sorted(unexpected)}. "
        "Only the three specified files should be present at start."
    )