# test_initial_state.py
#
# This pytest suite verifies that the **initial** filesystem state is
# exactly as described _before_ the student performs any tasks.
#
# It checks:
#   • Presence, permissions and exact contents of /home/user/logs/app.log
#   • Absence of any artefacts that the student is supposed to create
#     (the /home/user/logs/filtered directory and its files)

import os
import stat
from pathlib import Path

import pytest

LOG_DIR = Path("/home/user/logs")
APP_LOG = LOG_DIR / "app.log"
FILTERED_DIR = LOG_DIR / "filtered"
REGEX_CONF = FILTERED_DIR / "regex_filter.conf"
CRITICAL_LOG = FILTERED_DIR / "critical.log"
STATS_FILE = FILTERED_DIR / "critical.log.stats"

EXPECTED_APP_LOG_LINES = [
    "[2024-06-01 10:00:00] INFO  AuthService - User john.doe logged in.\n",
    "[2024-06-01 10:01:00] WARN  PaymentService - Timeout while processing transaction #872364.\n",
    "[2024-06-01 10:02:15] ERROR InventoryService - NullPointerException at line 231.\n",
    "[2024-06-01 10:03:42] DEBUG CacheService - Cache hit for key 192.168.1.15.\n",
    "[2024-06-01 10:04:01] INFO  AuthService - User jane.smith logged out.\n",
    "[2024-06-01 10:05:23] WARN  PaymentService - Retry attempt 1 for transaction #872365.\n",
    "[2024-06-01 10:06:47] ERROR InventoryService - ArrayIndexOutOfBoundsException at line 78.\n",
    "[2024-06-01 10:07:55] INFO  BillingService - Invoice #98234 generated successfully.\n",
]


def _mode(path: Path) -> int:
    """Return POSIX permissions (e.g., 0o644)."""
    return path.stat().st_mode & 0o777


def test_logs_directory_exists():
    assert LOG_DIR.is_dir(), f"Expected directory {LOG_DIR} does not exist."


def test_app_log_exists_and_permissions():
    assert APP_LOG.is_file(), f"Expected log file {APP_LOG} is missing."
    perm = _mode(APP_LOG)
    expected = 0o644
    assert (
        perm == expected
    ), f"Permissions for {APP_LOG} are {oct(perm)}, expected {oct(expected)}."


def test_app_log_contents_exact_match():
    with APP_LOG.open("r", encoding="utf-8") as fp:
        lines = fp.readlines()

    assert (
        lines == EXPECTED_APP_LOG_LINES
    ), (
        f"Contents of {APP_LOG} do not match the expected initial sample "
        "log file."
    )


def test_filtered_directory_does_not_exist_yet():
    assert not FILTERED_DIR.exists(), (
        f"{FILTERED_DIR} already exists, but it should be created by the "
        "student's solution, not be present in the initial state."
    )


@pytest.mark.parametrize(
    "path",
    [REGEX_CONF, CRITICAL_LOG, STATS_FILE],
)
def test_artifacts_do_not_exist(path: Path):
    assert not path.exists(), (
        f"Artifact {path} already exists, but it must be generated by the "
        "student's solution."
    )