# test_initial_state.py
#
# This test-suite validates the *initial* filesystem state that must be
# present **before** the student writes any automation.  It purposefully
# ignores every artefact that will be generated by the eventual solution
# (scripts, reports, archives, etc.).
#
# What we do assert:
#   • The log directory /home/user/logs exists.
#   • The three expected *.log files exist.
#   • Their contents are exactly the canonical ground-truth provided in the
#     task description (line-for-line, ignoring trailing new-lines).
#
# What we do NOT assert:
#   • Presence or absence of /home/user/tools or the shell script.
#   • Presence or absence of /home/user/archive or any *.gz files.
#
# Only the Python standard library and pytest are used.

from pathlib import Path
import pytest

LOG_DIR = Path("/home/user/logs")

# Canonical file contents taken verbatim from the task description.
EXPECTED_LOG_CONTENTS = {
    "app1.log": [
        "[2023-08-01 10:00:00] INFO Starting service",
        "[2023-08-01 10:05:00] ERROR Failed to connect to database",
        "[2023-08-01 10:06:00] WARN Cache miss",
        "[2023-08-01 10:07:00] ERROR Timeout while reading from socket",
        "[2023-08-01 10:08:00] INFO Service running",
        "[2023-08-01 10:09:00] ERROR Failed to connect to database",
    ],
    "app2.log": [
        "[2023-08-01 09:00:00] INFO Booting",
        "[2023-08-01 09:01:00] ERROR NullPointerException at line 42",
        "[2023-08-01 09:02:00] ERROR NullPointerException at line 42",
        "[2023-08-01 09:03:00] INFO Ready",
    ],
    "app3.log": [
        "[2023-08-01 11:00:00] INFO Starting cron",
        "[2023-08-01 11:01:00] WARN Slow query",
        "[2023-08-01 11:02:00] INFO Tick",
    ],
}


def read_file_lines(path: Path):
    """
    Helper that returns a file's contents as a list of lines *without*
    trailing newline characters.
    """
    # Replace CRLF with LF just in case; then rsplitlines() to keep last blank if any.
    return path.read_text().replace("\r\n", "\n").splitlines()


def test_log_directory_exists():
    assert LOG_DIR.exists(), f"Required directory {LOG_DIR} is missing."
    assert LOG_DIR.is_dir(), f"{LOG_DIR} exists but is not a directory."


@pytest.mark.parametrize("filename", sorted(EXPECTED_LOG_CONTENTS.keys()))
def test_each_log_file_exists(filename):
    file_path = LOG_DIR / filename
    assert file_path.exists(), f"Expected log file {file_path} is missing."
    assert file_path.is_file(), f"{file_path} exists but is not a regular file."
    assert file_path.stat().st_size > 0, f"{file_path} is empty."


@pytest.mark.parametrize("filename,expected_lines", EXPECTED_LOG_CONTENTS.items())
def test_log_file_contents_are_canonical(filename, expected_lines):
    """
    Validate that each log file contains exactly the canonical lines.
    This guards against accidental modification of the seed data.
    """
    file_path = LOG_DIR / filename
    actual_lines = read_file_lines(file_path)
    assert (
        actual_lines == expected_lines
    ), (
        f"Contents of {file_path} differ from the expected initial state.\n"
        f"Expected lines ({len(expected_lines)}):\n{expected_lines}\n\n"
        f"Actual lines ({len(actual_lines)}):\n{actual_lines}"
    )