# test_initial_state.py
#
# This pytest suite validates that the filesystem is in the expected
# “clean” state *before* the student creates the diagnostic bundle.
#
# Nothing related to /home/user/diag_collect should exist yet.

from pathlib import Path

DIR_PATH = Path("/home/user/diag_collect")
README_PATH = DIR_PATH / "README.md"
SYSINFO_PATH = DIR_PATH / "system_info.log"
COLLECT_LOG_PATH = DIR_PATH / "collection.log"


def _human(p: Path) -> str:
    """Return a friendly description of a filesystem path for error messages."""
    return f"'{p}' (type: {'directory' if p.is_dir() else 'file'})"


def test_diagnostic_directory_absent():
    """
    /home/user/diag_collect must NOT exist prior to running the student's
    collection script.  The directory (or file) will be created by the student.
    """
    assert not DIR_PATH.exists(), (
        f"{_human(DIR_PATH)} already exists. "
        "The diagnostic directory should be created by the student's solution, "
        "so it must be absent beforehand."
    )


def test_readme_absent():
    """
    README.md must NOT exist yet. It will be created inside diag_collect later.
    """
    assert not README_PATH.exists(), (
        f"{_human(README_PATH)} already exists. "
        "This README should be generated by the student; "
        "remove it to start from a clean slate."
    )


def test_system_info_log_absent():
    """
    system_info.log must NOT exist yet.
    """
    assert not SYSINFO_PATH.exists(), (
        f"{_human(SYSINFO_PATH)} already exists. "
        "This file should be generated by the student's script."
    )


def test_collection_log_absent():
    """
    collection.log must NOT exist yet.
    """
    assert not COLLECT_LOG_PATH.exists(), (
        f"{_human(COLLECT_LOG_PATH)} already exists. "
        "This file should be generated by the student's script."
    )