# test_initial_state.py
#
# Pytest suite that validates the **initial** operating-system / file-system
# state before the student performs any actions for the “release-manager”
# assignment.

import csv
from pathlib import Path
import pytest

HOME = Path("/home/user")
CSV_PATH = HOME / "releases" / "releases.csv"
DEPLOY_DIR = HOME / "deployment"
DEPLOY_JSON = DEPLOY_DIR / "deploy.json"
PROCESS_LOG = DEPLOY_DIR / "process.log"


@pytest.fixture(scope="module")
def csv_rows():
    """
    Load and return all rows from releases.csv as a list of dicts.
    This fixture fails fast with a clear message if the file is missing.
    """
    assert CSV_PATH.is_file(), (
        f"Required CSV file not found at {CSV_PATH}. "
        "The initial environment must provide this file."
    )

    with CSV_PATH.open(newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # Basic structural sanity check
    expected_fields = ["service", "environment", "version", "status"]
    assert reader.fieldnames == expected_fields, (
        f"{CSV_PATH} must have header columns exactly "
        f"{expected_fields}, found {reader.fieldnames}"
    )
    return rows


def test_release_csv_content(csv_rows):
    """
    Verify the exact rows that are expected to be present in the CSV.
    """
    # Expected full set of rows (order-sensitive)
    expected_all_rows = [
        {"service": "auth",          "environment": "staging",    "version": "1.4.3", "status": "ready"},
        {"service": "payments",      "environment": "production", "version": "2.1.0", "status": "hold"},
        {"service": "orders",        "environment": "staging",    "version": "3.0.1", "status": "ready"},
        {"service": "notifications", "environment": "production", "version": "1.9.5", "status": "ready"},
        {"service": "analytics",     "environment": "staging",    "version": "2.2.8", "status": "hold"},
    ]

    assert csv_rows == expected_all_rows, (
        "Content of releases.csv is not what the exercise specification "
        "describes.  The initial state must match exactly so the subsequent "
        "tasks can be graded deterministically."
    )

    # Derive "ready" rows and verify they are the three specified ones
    ready_rows = [row for row in csv_rows if row["status"] == "ready"]
    expected_ready_rows = [
        {"service": "auth",          "environment": "staging",    "version": "1.4.3", "status": "ready"},
        {"service": "orders",        "environment": "staging",    "version": "3.0.1", "status": "ready"},
        {"service": "notifications", "environment": "production", "version": "1.9.5", "status": "ready"},
    ]
    assert ready_rows == expected_ready_rows, (
        "The set (and order) of rows whose status is 'ready' does not match "
        "the specification.  These rows will be required to build deploy.json."
    )


def test_deployment_artifacts_absent():
    """
    Ensure that the deployment directory and its artifacts are *not* present
    before the student runs their solution.
    """
    assert not DEPLOY_DIR.exists(), (
        f"{DEPLOY_DIR} should NOT exist at the start of the task. "
        "It must be created by the student's solution."
    )
    # Even if the directory exists for some reason, its files must not exist
    assert not DEPLOY_JSON.exists(), (
        f"{DEPLOY_JSON} should not exist yet; it will be generated by the task."
    )
    assert not PROCESS_LOG.exists(), (
        f"{PROCESS_LOG} should not exist yet; it will be generated by the task."
    )