# test_initial_state.py
#
# This pytest suite verifies that the workstation is in a **clean** state
# before the student begins work on the “small heartbeat-style metric
# collector” exercise.  Nothing that belongs to the final solution should
# exist yet:
#
#   • /home/user/observability                 must NOT exist
#   • /home/user/observability/collect_metrics.sh
#   • /home/user/observability/metrics.log
#   • /home/user/observability/cron_validation.log
#   • the user’s crontab must NOT contain the line
#       "*/5 * * * * /home/user/observability/collect_metrics.sh"
#
# If any of the above items are already present, the test suite will fail
# with a clear, actionable message.

import os
import subprocess
import sys
from shutil import which

import pytest


HOME_DIR = "/home/user"
OBSERVABILITY_DIR = f"{HOME_DIR}/observability"
SCRIPT_PATH = f"{OBSERVABILITY_DIR}/collect_metrics.sh"
METRICS_LOG = f"{OBSERVABILITY_DIR}/metrics.log"
VALIDATION_FILE = f"{OBSERVABILITY_DIR}/cron_validation.log"
EXPECTED_CRON_LINE = "*/5 * * * * /home/user/observability/collect_metrics.sh"


def _read_crontab() -> str:
    """
    Return the current user's crontab as text.  If the user has
    no crontab yet, return an empty string.
    """
    if which("crontab") is None:
        # crontab binary is not present; treat as empty crontab
        return ""

    proc = subprocess.run(
        ["crontab", "-l"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    # According to the crontab(1) man page, exit status 1 means “no crontab for
    # USER”.  We treat that as an empty crontab, not an error.
    if proc.returncode == 0:
        return proc.stdout
    if proc.returncode == 1:
        return ""
    # Any other non-zero return code is unexpected.
    pytest.fail(
        f"Unexpected error while reading crontab:\n"
        f"stdout: {proc.stdout}\nstderr: {proc.stderr}"
    )
    return ""  # pragma: no cover


def test_observability_directory_absent():
    assert not os.path.exists(
        OBSERVABILITY_DIR
    ), (
        f"The directory {OBSERVABILITY_DIR} already exists. "
        "The workstation must be in a pristine state before the student starts."
    )


def test_script_file_absent():
    assert not os.path.exists(
        SCRIPT_PATH
    ), (
        f"The script file {SCRIPT_PATH} already exists. "
        "It must be created by the student."
    )


def test_metrics_log_absent():
    assert not os.path.exists(
        METRICS_LOG
    ), (
        f"The metrics log {METRICS_LOG} already exists. "
        "It should be created only after the student runs the script."
    )


def test_validation_file_absent():
    assert not os.path.exists(
        VALIDATION_FILE
    ), (
        f"The validation file {VALIDATION_FILE} already exists. "
        "It should be generated by the student at the end of the task."
    )


def test_cron_entry_absent():
    crontab_text = _read_crontab()
    matching_lines = [
        line for line in crontab_text.splitlines() if line.strip() == EXPECTED_CRON_LINE
    ]
    assert not matching_lines, (
        "The user's crontab already contains the line:\n"
        f"    {EXPECTED_CRON_LINE}\n"
        "The environment must not be pre-configured before the assignment begins."
    )