# test_initial_state.py
"""
Pytest suite that validates the *initial* state of the filesystem for the
“CSV disk-usage snapshot” exercise.

DO NOT modify the state of the filesystem here—only assert its current shape.
"""

import os
import stat
import pytest
from pathlib import Path

# Constants ------------------------------------------------------------------

HOME = Path("/home/user")
CSV_DIR = HOME / "data" / "csv"
REPORTS_DIR = HOME / "reports"
REPORT_FILE = REPORTS_DIR / "csv_disk_usage_report.txt"

# Expected CSV files and their exact apparent sizes (bytes).
EXPECTED_CSV_INFO = {
    "marketing.csv": 30_720,   # 0x7800
    "sales_q1.csv": 10_240,    # 0x2800
    "sales_q2.csv": 20_480,    # 0x5000
}


# Helper ---------------------------------------------------------------------

def _comma_list(items):
    """
    Helper for pretty-printing sets/lists in assertion messages.
    """
    return ", ".join(sorted(map(str, items))) or "<none>"


# Tests ----------------------------------------------------------------------

def test_csv_directory_exists():
    """
    /home/user/data/csv/ must exist and be a directory.
    """
    assert CSV_DIR.exists(), f"Required directory {CSV_DIR} does not exist."
    assert CSV_DIR.is_dir(), f"{CSV_DIR} exists but is not a directory."


def test_expected_csv_files_present_and_only_those():
    """
    The CSV directory must contain *exactly* the three expected files and no
    others.
    """
    present_files = {p.name for p in CSV_DIR.iterdir() if p.is_file()}
    expected_files = set(EXPECTED_CSV_INFO.keys())

    missing = expected_files - present_files
    extra = present_files - expected_files

    assert not missing, (
        f"Missing expected file(s) in {CSV_DIR}: {_comma_list(missing)}"
    )
    assert not extra, (
        f"Unexpected extra file(s) found in {CSV_DIR}: {_comma_list(extra)}"
    )


@pytest.mark.parametrize("filename,expected_size", EXPECTED_CSV_INFO.items())
def test_each_csv_has_exact_expected_size(filename, expected_size):
    """
    Every CSV file must have the exact apparent size prescribed by the task.
    (stat -c%s value, not on-disk allocation).
    """
    file_path = CSV_DIR / filename
    assert file_path.exists(), f"Expected CSV file is missing: {file_path}"

    # Use st_size for apparent size in bytes (same as `stat -c%s`).
    actual_size = file_path.stat().st_size
    assert actual_size == expected_size, (
        f"{file_path} has size {actual_size} bytes; "
        f"expected {expected_size} bytes."
    )


def test_reports_directory_absent():
    """
    /home/user/reports/ must NOT exist before the student runs their solution.
    """
    assert not REPORTS_DIR.exists(), (
        f"Reports directory {REPORTS_DIR} already exists; "
        "it should be created by the student's code."
    )


def test_report_file_absent():
    """
    The final artefact csv_disk_usage_report.txt must not pre-exist.
    """
    assert not REPORT_FILE.exists(), (
        f"Report file {REPORT_FILE} already exists; "
        "it should be generated by the student's code."
    )