# test_initial_state.py
#
# This pytest suite validates the *initial* filesystem / OS state **before**
# the student begins the cleaning task.  It asserts that the raw data file
# exists exactly as specified and that the output artefact directories/files
# are not present yet.  Clear assertion messages are provided so that any
# discrepancy is obvious.

import json
import os
from pathlib import Path

RAW_DIR = Path("/home/user/raw_data")
RAW_FILE = RAW_DIR / "people_raw.json"

CLEAN_DIR = Path("/home/user/clean_data")
CLEAN_FILE = CLEAN_DIR / "people_clean.json"

LOG_DIR = Path("/home/user/logs")
LOG_FILE = LOG_DIR / "cleaning_report.log"


def test_raw_directory_exists():
    assert RAW_DIR.is_dir(), f"Required directory {RAW_DIR} is missing."


def test_raw_file_exists():
    assert RAW_FILE.is_file(), f"Required file {RAW_FILE} is missing."


def test_raw_file_exact_contents():
    """
    The grader relies on the raw file being byte-for-byte identical to the
    expected six JSON-Lines listed in the task description.  We therefore check
    the exact content, including newlines.
    """
    expected_lines = [
        '{"id": 1, "name": "Alice", "age": 34}\n',
        '{"id": 2, "name": "Bob", "age": 28}\n',
        '{"id": 3, "name": "Charlie"}\n',
        '{"name": "Faythe", "age": 29}\n',
        '{"id": 4, "name": "Dana", "age": 45}\n',
        '{"id": 5, "name": "Evan", "age": 31}\n',
    ]

    with RAW_FILE.open("r", encoding="utf-8") as fh:
        actual_lines = fh.readlines()

    assert (
        actual_lines == expected_lines
    ), f"Contents of {RAW_FILE} differ from the expected baseline."


def test_raw_file_is_valid_json_lines():
    """
    Each line of the raw file must be independently parseable JSON.
    This ensures the student can safely use jq without syntax errors.
    """
    with RAW_FILE.open("r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, start=1):
            try:
                json.loads(line)
            except json.JSONDecodeError as exc:
                assert (
                    False
                ), f"Line {lineno} of {RAW_FILE} is not valid JSON: {exc}"


def test_output_directories_do_not_yet_exist():
    """
    The student has not performed any action yet, so the clean_data and logs
    directories (and their files) must NOT exist.  Their presence would imply
    that prior work has already been executed.
    """
    assert not CLEAN_DIR.exists(), f"{CLEAN_DIR} already exists—should be created by the student."
    assert not LOG_DIR.exists(), f"{LOG_DIR} already exists—should be created by the student."


def test_output_files_do_not_yet_exist():
    """
    Ensure that the artefact files are not present before the cleaning script
    runs.  This prevents stale or leftover files from previous runs from
    influencing the grading.
    """
    assert not CLEAN_FILE.exists(), f"{CLEAN_FILE} already exists—it must be generated by the student."
    assert not LOG_FILE.exists(), f"{LOG_FILE} already exists—it must be generated by the student."